### ISSUE TITLE
[BUG] [Blood] Some custom voxels are floating.

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#1000]
### Raze version

1.7.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some custom bottle voxels are floating despite they shouldn't. Tested in Fresh Supply and NBlood, it works correctly there.

### Steps to reproduce the behaviour.

Load Blood Voxel Pack and go to the specific E1L1 area shown in the screenshot.

![Blood_0004](https://github.com/ZDoom/Raze/assets/17529329/9845ba40-6c14-48ec-b0ba-e6caecb02ec5)

**Comment by coelckers** [comment]
fixed in 6eae603d2090395fc369f4d7ff03cab25da834ae
