### ISSUE TITLE
[BUG] [Duke] Raze 1.7.1 is unable to detect and launch some addons from ZOOM Platform release of Atomic Edition

### ISSUE THREAD

**Issue by ArhumMK** [ZDoom/Raze#1001]
### Raze version

Raze 1.7.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Zoom Platform release of Duke Nukem 3D Atomic Edition has recently updated it's set of AddOns to fix certain issues which has lead to some of them not being recognized by Raze, even when you drag and drop the .grp itself into raze.exe (located in the same folder). Here is the addons provided by the Zoom release vs. the ones recognized.

![dlclist](https://github.com/ZDoom/Raze/assets/70807030/c8bcae5d-ad4d-4b2e-b15d-fed5a901d0ca)

![gamelist](https://github.com/ZDoom/Raze/assets/70807030/c8701d2e-c21d-48ca-9fd5-f85ff054443f)

Below is the list of MD5 and CRC32 for the all addon files if it can help add support for these variants:

VACATION.GRP 
CRC32 - ``64CF2351``
MD5 - ``b16da02cff18c8fcf7c4200572c1e4a5``

DUKEDC.GRP 
CRC32 - ``C63B6A8B``
MD5 - ``c13140416db17586fc4c36c3388ddaa1``

PENTHOUS.GRP
CRC32  - ``CF928A58``
MD5 -  ``6a5a1505e38070ac0ab75eb60835988d``

NWINTER.GRP
CRC32  - ``F1CAE8E4``
MD5 - ``1250f83dcc3588293f0ce5c6fc701b43``

ZEROGAME.GRP 
CRC32 - ``C704BCA4``
MD5 -  ``cbd7f66b3fa6101f964c72eb27169d93``

DUKE!ZON.GRP 
CRC32 - ``1E9516F1``
MD5 - ``4cd0e3d3f170107b97aeafe4ade09ecf``

D3DZONE.iso 
CRC32 - ``C65B1BB7``
MD5 - ``5461d2cd7f93583a5ea2e6828e219b15``

Optional/Low priority - A way to detect/launch Duke! ZONE I or II would be nice.

I hope the information provided is helpful, thanks.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Duke Nukem 3D Atomic Edition from Zoom Platform
2. Install the DLC Pack (Addons) and Community Spotlight pack (ZEROGAME.GRP/CON)  from Zoom Platform
3. Extract contents of the Raze archive into the Installation directory and run.

**Comment by mjr4077au** [comment]
Where did `ZEROGAME.GRP` come from? It's not in the latest DLC from what I can see.

![image](https://github.com/ZDoom/Raze/assets/48643140/e54e8c2e-fa27-4cba-aa24-21a3b19520ae)

**Comment by coelckers** [comment]
I just confirmed that it loads everything except ZEROGAME, which is not an officially supported add-on and not present in the latest Zoom install I got and the .iso file, of course. So all that should work does work.

**Comment by ArhumMK** [comment]
ZEROGAME is for Duke It's Zero Hour! which is an unofficial total conversion included in Zoom Platform's "Community Spotlight pack". 
![image](https://github.com/ZDoom/Raze/assets/70807030/5f2d1194-73ae-4613-8906-795c830f50cc)

Thank you for looking into the official addons and fixing them! I look forward to the next release,
