### ISSUE TITLE
[BUG] Crash when loading game

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#1004]
### Raze version

Latest build 10/10/2023 - raze-x64-1.8pre-915-g8bb286abe.7z

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

1060 - 6GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When trying to launch Duke Nukem 3D , I get a crash. See crashreport.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/Raze/files/13054597/CrashReport.zip)

**Comment by coelckers** [comment]
The cause of this has already been fixed, it was just that the devbuild process had stopped and didn't produce new ones for more than a week.
