### ISSUE TITLE
[BUG] DN3D - Lights no longer destructible

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#1005]
### Raze version

raze-x64-1.8pre-926-g4135e460e.7z

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

W10 Home

### Relevant hardware info

1060 - 6GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In E1M1 "Hollywood Holocaust" it is no longer possible to destroy the lights in the bathroom.

See screenshot
![Duke_0000](https://github.com/ZDoom/Raze/assets/71838912/abb74b48-cd98-4008-97a6-6aea6c358100)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E1M1
2. Go to the bathroom
3. Try to destroy the lights

**Comment by coelckers** [comment]
fixed in 8545a2e74d07e722d9638a7b54a1144d91d4847a
