### ISSUE TITLE
[BUG] 1.8.0 crashes with "zmusic.dll was not found" error

### ISSUE THREAD

**Issue by fgsfds** [ZDoom/Raze#1011]
### Raze version

1.8.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

 1.8.0 crashes on start with the following error

![image](https://github.com/ZDoom/Raze/assets/4870330/80330205-df0c-4b46-9baa-16af731822e6)

Renaming zmusiclite.dll to zmusic.dll fixes the issue

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Unpack raze_1.8.0.zip into a game directory
2. Run raze.exe

### Provide a Log

There's no log

**Comment by coelckers** [comment]
Damn, that build script I copied from GZDoom didn't account for that. I'll do a new build ASAP. For now you can rename zmusiclite.dll to zmusic.dll to get it working

**Comment by coelckers** [comment]
1.8.1 should work.
