### ISSUE TITLE
[Feature] Linux versions for 1.8

### ISSUE THREAD

**Issue by mrmatteastwood** [ZDoom/Raze#1013]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Failing to build Raze, it seems to require programming skills.

### Describe the solution you'd like

Would you consider releasing a portable Linux build for Raze 1.8.1 like previous versions had?

### Describe alternatives you've considered

Tried building with appimage builder and got "RuntimeError: Unable to determine the bundle architecture". Also tried following the guide on the Zdoom wiki, but it's very intimidating and I don't know what "use this repository instead of GZDoom's" means and how to do that.

**Comment by michaelneverwins** [comment]
It looks like it was added shortly after this issue was opened.

https://github.com/ZDoom/Raze/releases/download/1.8.1/raze-v1.8.1-linux-portable.tar.xz

**Comment by mrmatteastwood** [comment]
Got it. Awesome, thanks so much!
