### ISSUE TITLE
[BUG] GLIBC_2.38 not found 

### ISSUE THREAD

**Issue by freeze19** [ZDoom/Raze#1014]
### Raze version

Raze v1.8.1 linux portable

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Raze does not start, it just shows the error "GLIBC_2.38 not found".
glibc 2.38-7 is installed on the system

### Provide a Log

libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libasound.so.2)
libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libglib-2.0.so.0)

**Comment by madame-rachelle** [comment]
Release has been updated with libc.so.6 removed.
