### ISSUE TITLE
Exhumed / Powerslave in Raze: Command-Line Option to Go Straight to Main Menu on Startup?

### ISSUE THREAD

**Issue by MasterO2** [ZDoom/Raze#1016]
@coelckers 

PCExhumed has a command line switch called `-quick` that goes straight to the main menu on startup, skipping all company logos, the intro movie, and pharaoh's laugh.

**Does Raze have an equivalent for this?** If so, what is it called? If not, can Raze add that as a feature?

**Comment by coelckers** [comment]
Well, it's called "-quick" ...
