### ISSUE TITLE
[BUG...?] Raze 1.8.1 using OpenGL ES when Vulkan is selected

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#1017]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Various (Duke Nukem 3D, Blood, Shadow Warrior, Exhumed)

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21.2

### Relevant hardware info

It's old (AMD Radeon HD 7950)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the potential bug is.

Raze 1.8.1 appears to be using OpenGL ES even when I have Vulkan selected.

Rather than a Raze bug, this _might_ just be a matter of inadequate Vulkan support for my hardware (see above), given that my GPU is quite outdated (and I had to [this](https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support) to get half-decent Vulkan support in the first place). I just don't know, because I don't have another PC to test at the moment. What I _do_ know is that, even on this machine, Vulkan mode _was_ working as expected in several previous versions of Raze. Moreover, I've used DXVK for plenty of games, so this isn't just a case of having no Vulkan support at all.

When running Raze 1.8.1, I don't see any errors or warnings about it having _failed_ to use Vulkan (see full log at the end). It just goes ahead and uses GL:
```
michael@linuxmint:~/.local/lib/raze/raze-v1.8.1-linux-portable$ grep vid_preferbackend ~/.config/raze/raze.ini
vid_preferbackend=1
michael@linuxmint:~/.local/lib/raze/raze-v1.8.1-linux-portable$ ./raze -gamegrp duke3d.grp | egrep 'Vulkan device:|GL_RENDERER:'
GL_RENDERER: AMD Radeon HD 7900 Series (tahiti, LLVM 15.0.7, DRM 3.42, 5.15.0-88-generic)
```
Meanwhile, this does _not_ occur with Raze 1.7.1 (the most recent other version I installed), which does use Vulkan:
```
michael@linuxmint:~/.local/lib/raze/Raze.v1.7.1.LinuxPortable$ grep vid_preferbackend ~/.config/raze/raze.ini
vid_preferbackend=1
michael@linuxmint:~/.local/lib/raze/Raze.v1.7.1.LinuxPortable$ ./raze -gamegrp duke3d.grp | egrep 'Vulkan device:|GL_RENDERER:'
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Vulkan device: AMD Radeon HD 7900 Series (RADV TAHITI)
```
GZDoom 4.11.3 (latest) is also able to use Vulkan.
```
michael@linuxmint:~$ gzdoom -iwad doom.wad | egrep 'GZDoom version|Vulkan device:|GL_RENDERER:'
WARNING: radv is not a conformant Vulkan implementation, testing use only.
GZDoom version g4.11.3
Vulkan device: AMD Radeon HD 7900 Series (RADV TAHITI)
```
Yes, I do see the warnings that print out when Vulkan mode _does_ work.

MangoHud agrees that GZDoom and Raze 1.7.1 are using Vulkan, while Raze 1.8.1 is using OpenGL (and it must actually be "OpenGL ES" rather than "OpenGL" because I run into the #966 bug if I actually try to use Raze's "OpenGL" mode).

### Steps to reproduce the behaviour.

If it can be reproduced without buying one of my GPU at a yard sale, the steps would just be:
1. install Raze 1.8.1 on Linux;
2. configure it for Vulkan mode;
3. run a game and check* if it's using Vulkan.

(* Don't trust the in-game "video mode" menu, because that says Vulkan even when the console output and MangoHud say it's using OpenGL.)

### Your configuration
The result was the same when I renamed my configuration file and let it create a default one, but I believe the relevant part would be:
```
vid_preferbackend=1
```

### Provide a Log
Full output of running `raze -gamegrp duke3d.grp` (with version 1.8.1), skipping the intro videos, and quitting:
```
Raze 1.8.1 - 2023-11-12 14:35:34 +0100 - SDL version
Compiled on Nov 15 2023

Log started: 2023-11-18 17:17:46
OS: Linux Mint 21.2, Linux 5.15.0-88-generic on x86_64
adding /home/michael/.local/lib/raze/raze-v1.8.1-linux-portable/raze.pk3, 3763 lumps
adding /home/michael/.config/raze/Duke.Data/duke3d.grp, 456 lumps
adding /home/michael/.config/raze/Duke.Data/, 4 lumps
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  Family 6, Model 60, Stepping 3
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
Loading "engine/widescreen.def"

I_InitSound: Initializing OpenAL
  Opened device Built-in Audio Analog Stereo
  EFX enabled
No GENMIDI lump found. OPL playback not available.
script parsing took 76.18 ms
Compiling: 'game.con'.
  * WARNING.(GAME.CON, line 3330) Expected an identifier, got a numeric literal 1.
Compilation time:46.99 ms, Code Size:59280 bytes. 1795 labels. 0/512 Variables.
Using video driver x11
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon HD 7900 Series (tahiti, LLVM 15.0.7, DRM 3.42, 5.15.0-88-generic)
GL_VERSION: 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
GL_SHADING_LANGUAGE_VERSION: 4.60
GL Version parsed = 4.600000
GL_MAX_TEXTURE_SIZE: 16384
GLES choosing mode: GLES_MODE_OGL3
Resolution: 640 x 480
player 1 of 1 (1 nodes)
```

**Comment by michaelneverwins** [comment]
From the Raze 1.8.1 release notes:
>Vulkan backend updated.

I suspect that maybe the old Vulkan backend likes my system and the new Vulkan backend doesn't. But I'm generally ignorant about how such things work, so don't go and close the issue just based on my wild speculation. Go ahead and close it if I'm actually right and if there's nothing to be done about it, though.

**Comment by coelckers** [comment]
Your card is one of the first generations supporting Vulkan, Bzut having it work on GZDoom 4.11 and not Raze 1.8 is strange - the backends should be identical

**Comment by michaelneverwins** [comment]
Well I've got some more information which might clear things up a bit.

While I had installed Raze 1.7.1 and Raze 1.8.1 from their "portable" packages (`Raze.v1.7.1.LinuxPortable.tar.xz` and `raze-v1.8.1-linux-portable.tar.xz` respectively), my copy of GZDoom 4.11.3 was installed via APT from [DRD Team's Debian repo](https://debian.drdteam.org/) (or, rather, I had installed some previous version a while ago and it updated to 4.11.3). This GZDoom package was "compiled under Ubuntu 18.04 LTS" according to that page; I'll assume this is not necessarily the case for the "portable" releases.

For a better comparison between Raze and GZDoom, I tried the "portable" release of the latter, and I did get the same result as with Raze 1.8.1. In other words, Vulkan works with GZDoom 4.11.3 from DRD Team's Debian repo, but not with GZDoom 4.11.3 from the GitHub release assets.
```
michael@linuxmint:~$ which gzdoom
/usr/games/gzdoom
michael@linuxmint:~$ dpkg -S /usr/games/gzdoom
gzdoom: /usr/games/gzdoom
michael@linuxmint:~$ apt policy gzdoom
gzdoom:
  Installed: 4.11.3
  Candidate: 4.11.3
  Version table:
 *** 4.11.3 500
        500 https://debian.drdteam.org stable/multiverse amd64 Packages
        100 /var/lib/dpkg/status
michael@linuxmint:~$ gzdoom -iwad doom.wad | egrep 'GZDoom version|Vulkan device:|GL_RENDERER:'
WARNING: radv is not a conformant Vulkan implementation, testing use only.
GZDoom version g4.11.3
Vulkan device: AMD Radeon HD 7900 Series (RADV TAHITI)
```
```
michael@linuxmint:~$ wget -q https://github.com/ZDoom/gzdoom/releases/download/g4.11.3/gzdoom-g4.11.3-linux-portable.tar.xz -P ~/Downloads/
michael@linuxmint:~$ mkdir -p ~/.local/lib/zdoom
michael@linuxmint:~$ tar -xJf ~/Downloads/gzdoom-g4.11.3-linux-portable.tar.xz -C ~/.local/lib/zdoom/
michael@linuxmint:~$ cd ~/.local/lib/zdoom/gzdoom-g4.11.3-linux-portable/
michael@linuxmint:~/.local/lib/zdoom/gzdoom-g4.11.3-linux-portable$ ./gzdoom -iwad doom.wad | egrep 'GZDoom version|Vulkan device:|GL_RENDERER:'
GZDoom version g4.11.3
GL_RENDERER: AMD Radeon HD 7900 Series (tahiti, LLVM 15.0.7, DRM 3.42, 5.15.0-88-generic)
```
In both cases, while GZDoom was running, I went to the "video mode" menu and confirmed that Vulkan was shown as the preferred rendering API there.

So this isn't a GZDoom-versus-Raze thing anymore, but rather may have something to do with how the portable releases were compiled, and compiling GZDoom/Raze is another subject about which I know very little. I'm curious as to whether I'd have working Vulkan support if I compiled Raze on my machine, but I've never tried it and I don't think I'll have time to figure it out this weekend.

**Comment by michaelneverwins** [comment]
(Ubuntu 18.04 is pretty old now, right? So I wonder if the text on that DRD Team page is up-to-date. But it was apparently compiled on something close enough to Linux Mint 21.2 in any case.)

**Comment by michaelneverwins** [comment]
It's a bit late, but I did finally get around to compiling Raze myself on Linux Mint. I didn't bother with trying to compile Raze 1.8.1 or any other non-latest version, because I wasn't specifically trying to debug this issue, but rather just wanted to try the latest version. However, I did see that Raze 1.10.2 as compiled on my machine does appear to be using Vulkan.
```
michael@linuxmint:~/.local/lib/raze/raze-v1.10.2-compiled$ ./raze -gamegrp duke3d.grp | egrep 'Vulkan device:|GL_RENDERER:'
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Vulkan device: AMD Radeon HD 7900 Series (RADV TAHITI)
```
I'm on Linux Mint 21.3 now, whereas before I was using 21.2, but I don't think that's relevant, because I still have Raze 1.8.1 installed and it still uses OpenGL even when the video backend is set to Vulkan.
```
michael@linuxmint:~/.local/lib/raze/raze-v1.8.1-linux-portable$ grep vid_preferbackend ~/.config/raze/raze.ini
vid_preferbackend=1
michael@linuxmint:~/.local/lib/raze/raze-v1.8.1-linux-portable$ ./raze -gamegrp duke3d.grp | egrep 'Vulkan device:|GL_RENDERER:'
GL_RENDERER: AMD Radeon HD 7900 Series (tahiti, LLVM 15.0.7, DRM 3.42, 5.15.0-116-generic)
```
So either Raze 1.10.2 works as expected because I compiled it on Mint, or it works just because 1.10.2 fixed something (but I can't confirm that because there's no portable Linux release of this version and therefore compiling it myself is the only way I can test it).

**Comment by madame-rachelle** [comment]
Check that your video drivers are properly installed and that any relevant Mesa/Vulkan packages available are also in place.

I do see the warning `WARNING: radv is not a conformant Vulkan implementation, testing use only.` - Raze as of late may require Vulkan extensions, or even a Vulkan version, that is not currently available in those drivers.

If you are using manufacturer drivers, you might try switching to the Mesa drivers for that card. It should be old enough that Mesa should run really well on it, by now.

**Comment by coelckers** [comment]
I am closing this because we have no means to ensure the engine works with drivers that declare themselves non-conformant.+
