### ISSUE TITLE
[BUG]  SW: Game Crash at Serpent God 50% HP (Shareware Level)

### ISSUE THREAD

**Issue by jrugia** [ZDoom/Raze#1018]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Debian 9

### Relevant hardware info

CPU: Ryzen 5800X / GPU: RX 6800 [Mesa 23.1.9]

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Game crashes upon fighting the Serpent God, once you damage it to 50% HP game should play a cutscene but instead crashes. I tried different all renderers OpenGL/ES/Vulkan, as well as ran the game with LLVMPIPE (CPU rendering), same issue.

As far as cutscenes go, the intro plays just fine. I didn't have any issues with the game up until now.

**EDIT:** Re-Tested same level with 1.7.1 and cutscene played fine.

### Steps to reproduce the behaviour.

Explain how to reproduce:

1. Load Savegame and get boss to 50% HP

Copy of Savegame: [ShadowWarrior.ShadowWarrior.zip](https://github.com/ZDoom/Raze/files/13444730/ShadowWarrior.ShadowWarrior.zip)

### Provide a Log

[raze.log](https://github.com/ZDoom/Raze/files/13444723/raze.log)

**Comment by coelckers** [comment]
This is already fixed in master for the next release.
