### ISSUE TITLE
[Feature] Ability to turn off view centering when landing after a fall?

### ISSUE THREAD

**Issue by NastyFlytrap** [ZDoom/Raze#1019]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Not really. Maybe slope tilting, but not sure.

### Describe the solution you'd like

When i land after a fall, the angle of my view stays the same as it was when falling (unless i choose to change it myself)

### Describe alternatives you've considered

Eduke? There arent really alternatives for this within raze, and voidsw doesnt have it either

**Comment by coelckers** [comment]
added in 93bc496494510084d60f6e85acccc173cc84204c
