### ISSUE TITLE
[Feature] Ability to have a portable configuration like in GZDoom

### ISSUE THREAD

**Issue by NastyFlytrap** [ZDoom/Raze#1021]
### Raze version

1.8.1

### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I dont like the default settings of either GZDoom or RAZE and like GZDoom i'd like to be able to have the configuration right next to the exe, like with GZDoom's portability mode.

### Describe the solution you'd like

gzdoom_portable.ini but for raze, storing raze's settings.

**Comment by coelckers** [comment]
You can already do that exactly the same way, i.e. put raze_portable.ini next to the EXE.

**Comment by NastyFlytrap** [comment]
> You can already do that exactly the same way, i.e. put raze_portable.ini next to the EXE.

Alright, but unlike GZDoom, RAZE overwrites the ini file every time the port gets closed, which is an issue because my cloud saving application starts uploading the file as soon as the game is closed, and then i launch it again, the file is locked because its being uploaded, and raze automatically goes for the fallback option of creating a new one in the documents.

It'd be neat if it didnt 'update' the file if nothing was actually changed. This is just making it a hassle for me for no benefit, atleast not as far as i can tell

**Comment by madame-rachelle** [comment]
There is no way to track if the .ini file actually needs to change or not, plus this is such a niche scenario that it's really not worth the development time for what is a mere hobby project. Fixing at least 10 bugs would be more worth the development time than what it would take to get something like this working - and I am not trying to be mean, or unsympathetic to your use case, but surely there's a better way to file sync your .ini file than using cloud storage?

**Comment by NastyFlytrap** [comment]
> There is no way to track if the .ini file actually needs to change or not, plus this is such a niche scenario that it's really not worth the development time for what is a mere hobby project. Fixing at least 10 bugs would be more worth the development time than what it would take to get something like this working - and I am not trying to be mean, or unsympathetic to your use case, but surely there's a better way to file sync your .ini file than using cloud storage?

To be fair im just syncing the entire folder because why not, but the two source ports still handle this differently and if its not intentional then i dont know why RAZE is doing this
