### ISSUE TITLE
[BUG] SW: Uzi spread is only horizontal

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#1022]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The bullet spread from uzis will always only be horizontal, the spread just makes a horizontal line as there is no vertical spread. This is not how it works in the original game.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. get uzi
2. shoot uzi at wall and look at the sparks and bullet holes, they are only a vertical line
3.

### Your configuration

```ini
default config
```

**Comment by coelckers** [comment]
fixed in be4bebaa3bac36692ccb0c916ab57680c8bfe952
