### ISSUE TITLE
 [BUG] [Blood] Mini calebs and spiders are either unable or inconsistently able to do damage to the player

### ISSUE THREAD

**Issue by gnollidiot** [ZDoom/Raze#1024]
### Raze version

1.8.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Mini calebs appear to be shooting the floor beneath them and spiders can give you the poison screen effect but with no draining health.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to any map with Mini calebs or spiders
2. Let them hit you
3.

### Your configuration

```ini
Default installation
```

**Comment by FitzRoyX** [comment]
confirmed in latest master. attached saves for e2m8 area (spiders) and e6m2 area (mirror must be broken to spawn little calebs).

[bugs1.zip](https://github.com/ZDoom/Raze/files/13696167/bugs1.zip)

**Comment by coelckers** [comment]
Caleb is fixed in 0ad7e198d8b059ac7726e476aa94f2cf0d3ac01e

**Comment by coelckers** [comment]
Spider is fixed in 3dbc67150d25048b6b91565d413d0bfe609ea723
