### ISSUE TITLE
[BUG] SW: Ghosts go all the way back into their corpse on the final frame of exiting it

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#1027]
### Raze version

raze-x64-1.9pre-27-g4644bfcbc

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the last frame of the animation of ghosts leaving a coolie corpse, you will instead see the first frame which causes the ghost to go all the way back inside the corpse before the animation finishes.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. let coolie blow itself up
2. watch ghost come out
3. it goes back in
4. animation finishes

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
I rolled back the change causing this problem.
