### ISSUE TITLE
[BUG] [Duke] Duke Vacation: Elevator muzak SFX no longer plays

### ISSUE THREAD

**Issue by heesemonster** [ZDoom/Raze#1030]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

13th Gen Intel(R) Core(TM) i7-13700KF / NVIDIA RTX 4070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Normally in Duke: Vacation the elevators play a muzak soundbite when you use them, for comedic effect. In the most recent version of raze, 1.8.1, this no longer functions and there is instead silence.

The correct version playing the sound effect can be seen here:
https://youtu.be/opqeU6BTE8M?list=PLXBVjp8y90nFSn5kihxX1XgXFIiSgd5DO&t=119 (~1:58)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start up Duke: Vacaction
2. Use any elevator in the first level (After grabbing Yellow card key - two open for progression)
3. Normally a quick elevator muzak sound effect plays, but it is mute in this version

**Comment by coelckers** [comment]
fixed in 8d4631eee9ebbf01c36dfb06f6c3f4736076f833
