### ISSUE TITLE
[BUG] [SW] Crashes

### ISSUE THREAD

**Issue by Monkeyboyxbox** [ZDoom/Raze#1031]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

10700k rtx 3080 32gbram 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Crashes when using weapons nuke, gas canister. Crashes when fighting bosses sumo and serpent. Crashes when quick saving. And random crashes

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Fire nuke 
2.crash
3.

**Comment by Monkeyboyxbox** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by FitzRoyX** [comment]
This seems to be fixed in the latest master, could only get it to happen on 1.8.1 release build.

**Comment by Monkeyboyxbox** [comment]
ok brilliant how do i use the master build to run the game?, no obvious file in there i swap

**Comment by sinisterseed** [comment]
> ok brilliant how do i use the master build to run the game?, no obvious file in there i swap

Either compile the master from source yourself, or use one of the daily autobuilds - https://devbuilds.drdteam.org/raze/

Extract them to a new directory if you want to start fresh, or overwrite existing files.
