### ISSUE TITLE
[BUG] [SW] Crash when throwing Gas Bomb

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/Raze#1032]
Raze 1.8.1, Win10-64, data files from Shadow Warrior Redux. Didn't happen on 1.7.1.

Log attached.

[CrashReport.zip](https://github.com/ZDoom/Raze/files/13662438/CrashReport.zip)

**Comment by FitzRoyX** [comment]
This seems to be fixed in the latest master, could only get it to happen on 1.8.1 release build.
