### ISSUE TITLE
[BUG] [Duke Nukem 3D] Geishas from the level Raw Meat don't show off anymore (when you press action)

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1033]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On the level Raw Meat (E3L1) there are two Geisha statues (?, not sure what they are supposed to be because they shatter like glass), in the original game if you press action they show off their breasts, in raze nothing happens.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Load E3L1
2. Go to any of the statues (there are two of them, one interesting detail is that each one is a unique sprite, each one has one color) and press use.
3.

### Your configuration

```ini
default
```

**Comment by FitzRoyX** [comment]
confirmed latest master

**Comment by coelckers** [comment]
fixed in 1299a373defaf2c97a81686fe8afd51d6187a44d
