### ISSUE TITLE
[BUG] [Blood] Gargoyles from statues are immortal (normal and boss)

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1034]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Gargoyles (normal ones and the boss/grey one) that spawn from statues are immortal. Tested on three difficulties.
Gargoyles that don't come from statues seems to be working fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a map that have a gargoyle statue (like E4M6, in the start there are 2 statues, one summon a normal gargoyle, the other summon a boss one, or E1M5 theres one in the start).
2. Try to kill it (Napalm strike the normal one, should kill it in one hit when working).
3.

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
This is already fixed in master
