### ISSUE TITLE
[BUG?][Redneck Rampage] Route 66 ending behavior

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1036]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Im not sure if this one is a bug because i could not find for sure what is supposed to happen.
When you beat route 66, it plays the sound of the original ending cutscene of Redneck Rampage (i know its very short) over the route 66 cutscene, its very confusing/weird.
It seems that this should not happen, the route 66 cutscene (is just a slide show) seems to don't have any sound or song (i saw very old youtube videos played on DOS where in some it was silent and others it continued playing the level song).

The route66.zip file was created following the instructions on the "[How to make Build games work with Raze]" forum thread.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the map "alien", rush and kill the boss. (play with caution to avoid pressing a button and skipping the cutscene). Use god and give all.
2.
3.

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
fixed in adfbae8fbe782ad637b654f0f855d84902e00594
