### ISSUE TITLE
[BUG] [Blood] Loading a save removes inventory items

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1038]
### Raze version

1.8pre-942-g860a0c290

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you load a savegame in this version, all your inventory items are removed and on their place you get an medkit and a boot with 0 ammo/durability.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open any map, use "give all", save the game and then load.
2.
3.

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
Fixed in 3b44c50dfd665db6d97e5bd5b985dcf0eab282b9

I already had this on 1.8, but when doing a reset forgot this commit.
