### ISSUE TITLE
[BUG] [NAM/WWIIGI/PLATOON] The games crash while starting/launching

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1039]
### Raze version

1.8pre-942-g860a0c290

### Which game are you running with Raze?

NAM

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

All three games crash on start/launch/load screen.
(I decided to report all three at the same time given their nature, tell me if is ok to do so).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open any of the games;
2.
3.

### Your configuration

```ini
default
```

### Provide a Log

[PLATOONLEADER_CrashReport.zip](https://github.com/ZDoom/Raze/files/13718039/PLATOONLEADER_CrashReport.zip)
[NAM_CrashReport.zip](https://github.com/ZDoom/Raze/files/13718040/NAM_CrashReport.zip)
[WWIIGI_CrashReport.zip](https://github.com/ZDoom/Raze/files/13718042/WWIIGI_CrashReport.zip)

**Comment by coelckers** [comment]
fixed in 27da9b6b79c05a4e9afd1d1e0bb6cd223507ee0d
