### ISSUE TITLE
[BUG] Several Errors in several games

### ISSUE THREAD

**Issue by orderorder** [ZDoom/Raze#1043]
### Raze version

Raze git 485ad27

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

ENDEAVOUR OS Last Version (Arch Linux)

### Relevant hardware info

AMD 1700 / AMD RX580

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

**Blood Fresh Supply:**

When I run Raze there is no options menu. It is not visible. I have attached a file.

**Blood One Unit Whole Blood:**

No work i have attached the error

**Duke Nukem World Tour:**

Similar error attached

Other games like **Duke Nukem Omega Edition, Powerslave, Shadow Warrior** works well

### Steps to reproduce the behaviour.

Execute raze in the folder game

### Your configuration

```ini
Default configuration
```

### Provide a Log

![image](https://github.com/ZDoom/Raze/assets/7293829/39b21639-a11e-473b-8508-04e5a71ae881)
[blood_one_unit_whole_blood_raze-crash.log](https://github.com/ZDoom/Raze/files/13759967/blood_one_unit_whole_blood_raze-crash.log)
[Duke_Nukem_World_Tour_raze-crash.log](https://github.com/ZDoom/Raze/files/13759969/Duke_Nukem_World_Tour_raze-crash.log)

**Comment by coelckers** [comment]
I cannot do anything with crash logs from a symbol-less release build. You'll have to post ones from a debug build with symbols.

**Comment by orderorder** [comment]
How should I compile it? I am using the debug version

**Comment by daemonspudguy** [comment]
@coeleckers how do we compile a debug build? We have no instructions at all for that.

**Comment by orderorder** [comment]
> @coelckers how do we compile a debug build? We have no instructions at all for that.

I think that if we dont use -DCMAKE_BUILD_TYPE=Release then we are compiling a DEBUG build. At this time Raze in Arch Linux bases distros dont work well. It fails in Manjaro too

**Comment by daemonspudguy** [comment]
I've noticed, figured out how to compile a debug, and filed a new issue.

**Comment by orderorder** [comment]
Bugs fixed in the cab73b8 build. Tnanks

**Comment by mjr4077au** [comment]
Thank you for confirming! :)
