### ISSUE TITLE
[BUG] [SW] WAV sounds are not loaded

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#1044]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi, I read a comment on moddb page where it said my addon no longer works in ver 1.8.1. I tested that and I confirm that it indeed no longer works. Please investigate what happened between version 1.7 and 1.8. Thanks!

https://www.moddb.com/mods/shadow-warrior-high-quality-sound-effects

**Comment by Dzierzan** [comment]
Today I discovered that vanilla SW game supports sounds sample rated to 44 kHz, encoded to 16 bit depth, which was a big suprise to me. I converted all sounds to VOC and Raze loads that correctly now.

Nevertheless, loading WAVs is broken, so IMO you should still try to fix it.

**Comment by coelckers** [comment]
fixed in 5b4aa573b1244abb6ff94cb9edbe6fb4eca81b14
