### ISSUE TITLE
[BUG] [Duke Nukem 3D] Clipping trough the map in certain maps (VACATION)

### ISSUE THREAD

**Issue by JarDrh99** [ZDoom/Raze#1045]
### Raze version

1.8pre-946-g485ad27a5

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Duke Caribbean i found two locations where you can clip trough the wall, both in vents.
I provided a save file for each location.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. In VACA1, while going trough this path, if you stand up for a second when theres enough space (becase theres a vent up) it will go trough the wall (it kinda teleports you).
2. In VACA4, if you enter this vent while pressing crouch, it will clip trough the wall and throw you off the map/ship. It's a bit tricky to make it happen.
3.

### Your configuration

```ini
default
```

### Provide a Log

[Duke.Vacation.15.zip](https://github.com/ZDoom/Raze/files/13761936/Duke.Vacation.15.zip)

**Comment by coelckers** [comment]
Welcome to the wonderful world of Build engine physics. Yes, Duke is doing that in certain places, and thanks to the extremely broken code at play here (that cannot be replaced unless you want the games to stop working) it occasionally will fail to do the right thing.
