### ISSUE TITLE
[BUG] [SW] Missile projectile yaw is wrong.

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#1048]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Just shoot a missile from the rocket launcher to notice that bug. Disclaimer, I turned off my autoload addons.

![missile-bug](https://github.com/ZDoom/Raze/assets/17529329/6b7c83e0-8c9d-42ab-b0a4-a12a56e78b48)

**Comment by prof-hastig** [comment]
Looks like a duplicate: https://github.com/ZDoom/Raze/issues/1023
