### ISSUE TITLE
[BUG] [SW] Darts item pickup is shown as smaller shuricans.

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#1049]
### Raze version

1.8.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When Darts are selected, shuricans weapon, projectiles and pickup item should be changed to darts. It appears the item is not. GIF below:

![darts](https://github.com/ZDoom/Raze/assets/17529329/f9467d5d-391c-4618-86bd-d05a229af71a)

**Comment by prof-hastig** [comment]
This works correctly in current master. It seems to be another duplicate but I cannot find a commit that addresses it.
