### ISSUE TITLE
[BUG] Duke Nukem 3D: autoaim set to "hitscan only" is broken

### ISSUE THREAD

**Issue by bfg01** [ZDoom/Raze#1050]
### Raze version

Raze 1.8.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Debian 12

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An effective way of dispatching the battlelord sentries is with the shrinker weapon, but specifically aiming for its lower part/half.
However this has always worked only by turning off autoaiming (ever since eduke32 or probably original binaries), or setting it to "hitscan only" on Raze.

In Raze 1.8.0 this worked correctly, but in 1.8.1 this no longer works: autoaim set to either always or hitscan work exactly the same, and the only way to go is by setting it to never, but this also disables it for all weapons.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Menu > Options > Gameplay Options > Autoaim to "Hitscan only"
2. Load a level where a battlelord sentry appears; example E2L3
3. Go through level until encountering the sentry, equip shrinker weapon
4. Try aiming the sentry's lower part and shoot: the shot will always the middle part as if autoaim=always

### Your configuration

```ini
cl_autoaim=2
```

**Comment by coelckers** [comment]
fixed in 9315c8b30798902c39310bed637563956579ae43
