### ISSUE TITLE
[BUG]  [Blood] No midi music and Death Wish add-on crashes the engine

### ISSUE THREAD

**Issue by Zerodarkage** [ZDoom/Raze#1053]
### Raze version

1.9.1 and 1.9.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

Intel Core I5, Intel HD Graphics 530,  32GB Ram DDR4

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting a new Blood episode there is no music playing during the level. When loading Deathwish ADD-ON and starting a new episode the engine crashes during the intro with the message "Execution could not continue. Ran out of data in zlib stream"

### Steps to reproduce the behaviour.

Explain how to reproduce 
Midi Bug:
1. Start Raze and choose Blood
2. Choose an episode to play
3. After the level starts no MIDI music is playing
Deathwish crash Bug:
1. Load Deathwish ADD-ON with Raze
2. After starting Blood choose an episode
3. As soon the intro starts the engine crashes with the message "Execution could not continue. Ran out of data in zlib stream"

### Your configuration

[raze_portable.ini.txt](https://github.com/ZDoom/Raze/files/13804209/raze_portable.ini.txt)

### Provide a Log

[raze.log](https://github.com/ZDoom/Raze/files/13804160/raze.log)

**Comment by Zerodarkage** [comment]
P.S.
Episode 4 intro does not play! (Tested with multiple versions of Raze)

**Comment by coelckers** [comment]
Music fixed in e2048bd8bddbcf9dc7bc9aa76f71affd20c08194

**Comment by coelckers** [comment]
Cutscene sound fixed in fb6beb905ab47d06b21d59f05b3a9b1a62704744
This was already fixed but got accidentally reverted somehow.

**Comment by coelckers** [comment]
I cannot say much about the Death Wish bug. It works for me right now

**Comment by Zerodarkage** [comment]
Next time, I'll report only one bug per ticket!

**Comment by Zerodarkage** [comment]
> Cutscene sound fixed in [fb6beb9](https://github.com/ZDoom/Raze/commit/fb6beb905ab47d06b21d59f05b3a9b1a62704744) This was already fixed but got accidentally reverted somehow. Please note that the E4 video plays before E4M8, not before E4M1!

DOS version plays this video on start of Episode 4. Maybe it's a bug with DOS version.
Thanks for the clarification!

**Comment by sinisterseed** [comment]
> > Cutscene sound fixed in [fb6beb9](https://github.com/ZDoom/Raze/commit/fb6beb905ab47d06b21d59f05b3a9b1a62704744) This was already fixed but got accidentally reverted somehow. Please note that the E4 video plays before E4M8, not before E4M1!
> 
> DOS version plays this video on start of Episode 4. Probably it's a bug with DOS version. Thanks for the clarification!

Very much so, yes.

If you watch the cutscene, it clearly sets the ground for the battle against Tchernobog, there's no reason for it to play this early (Caleb even replies to him after the map starts that he's already dead, it makes no sense for him to say this for no apparent reason). DOS, and by extension NBlood when it last checked it ages ago, did replicate this behavior, but it's definitely a bug considering the context it occurs in.
