### ISSUE TITLE
[BUG] Killing chicks no longer spawns "punishment" monsters

### ISSUE THREAD

**Issue by bfg01** [ZDoom/Raze#1057]
### Raze version

Raze 1.9.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Debian 12

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Still back in 1.8.1 killing chicks, both captive and normal, triggered spawning of monsters in the surroundings.
I think at least since 1.9.0 this is no longer the case; for some reason the additional monsters are no longer triggered.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load any level with chicks present and try killing them; notably e3l9 and e3l10 should summon assault commanders and battlelord sentries respectively.
2. See that nothing is summoned.

**Comment by coelckers** [comment]
fixed in 663bc0f18b26434aca86e97cf1d6e9dad0533d32
