### ISSUE TITLE
[Feature] Start Shadow Warrior addons from command line

### ISSUE THREAD

**Issue by fgsfds** [ZDoom/Raze#1061]
### Raze version

1.9.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Currently, there's no way to start Shadow Warrior addons from command line. Unlike Duke 3D, that has `-addon 0/1/2/3` command

### Describe the solution you'd like

Add `-swaddon 0/1/2` that starts base Shadow Warrior, Wanton Destruction and Twin Dragon respectively.

**Comment by coelckers** [comment]
I chose not to because unlike Duke there is no naming convention here. I've seen Wanton.grp, WT.grp, TwinDrag.grp and TD.grp.
The -addon switch doesn't do more than -gamegrp with the respective files, so adding it here seems rather pointless.

**Comment by fgsfds** [comment]
> I chose not to because unlike Duke there is no naming convention here. I've seen Wanton.grp, WT.grp, TwinDrag.grp and TD.grp. The -addon switch doesn't do more than -gamegrp with the respective files, so adding it here seems rather pointless.

There's some hardcoded stuff for SW addons, like episode and map names. It won't work if addons are loaded with -file parameter.
