### ISSUE TITLE
[BUG] "Very fatal error" when trying to play user map

### ISSUE THREAD

**Issue by axredneck** [ZDoom/Raze#1063]
### Raze version

Tried both 1.9.1 and commit g48977265a, both are from AUR.
Edit: also tried "Linux Portable" build from Github (deleted it's libc.so.6 because else it doesn't run at all), and it gives the same "fatal error".

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

Ryzen 5 2600, Geforce GTX 1050, 32Gb RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

That's it: Raze crashes when i try to play a user map
Also i think it's a regression because i successfully played user maps in Raze a few months ago.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Select Duke Nukem 3D in Start Window
2. Select "New Game", then "User Map"

### Your configuration

```ini
Default config
```

### Provide a Log

[raze.log](https://github.com/ZDoom/Raze/files/13907879/raze.log)

[And a window with this error appears](https://gist.github.com/axredneck/64785ffc77cdbaac3b432b2343b33e04)

**Comment by axredneck** [comment]
I also tried [Linux build from Github](https://github.com/ZDoom/Raze/releases/download/1.9.1/raze-v1.9.1-linux-portable.tar.xz) (in case AUR versions are built incorrectly somehow) but it gives this error:
```
./linux-portable/raze: /home/redneck/games/raze/linux-portable/libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libasound.so.2)
./linux-portable/raze: /home/redneck/games/raze/linux-portable/libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libglib-2.0.so.0)
```

**Comment by madame-rachelle** [comment]
Try and `rm` the libc.so.6 from the raze-linux-portable folder does that fix the glibc errors?

**Comment by axredneck** [comment]
@madame-rachelle i already tried, see above.

**Comment by coelckers** [comment]
It doesn't crash on Windows so at the very least I need a crash log with symbols.

**Comment by axredneck** [comment]
How can i get these symbols?

**Comment by axredneck** [comment]
Edit: i built `raze-git` from AUR with CMAKE_BUILD_TYPE=Debug, now it crashes immediately (no need to try to run user maps), here is [raze-crash.log](https://github.com/ZDoom/Raze/files/13920669/raze-crash.log)

**Comment by axredneck** [comment]
Meanwhile Windows version (under Wine) doesn't crash so i'll stick to it for now.

**Comment by coelckers** [comment]
I think this all sounds related to the filename case sensitivity bug with loaded directory content.
