### ISSUE TITLE
[BUG] MIDI in Blood no longer plays since v1.9.0

### ISSUE THREAD

**Issue by BurningFishNL** [ZDoom/Raze#1064]
### Raze version

Raze 1.9.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

Roland UM-ONE

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The MIDI music from Blood does not play anymore since v1.9.0 onward. I tested v1.8.1 and the MIDI music plays. It appears that just Blood is affected, MIDI's from Duke 3D and WW2GI play fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Blood with Raze 1.9.0+
2. Disable CD emulation
3. Play the game

**Comment by coelckers** [comment]
It's already fixed
