### ISSUE TITLE
[BUG][Blood] Mini calebs still aren't behaving right

### ISSUE THREAD

**Issue by FitzRoyX** [ZDoom/Raze#1069]
### Raze version

latest master

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Mini calebs should be hitting the player with their shots for small damage. Instead, they are more likely to hit each other or a nearby wall than the player.

raze:
<video src="https://github.com/ZDoom/Raze/assets/57089001/a455e8fb-64ca-4f33-a684-cd806c8d3c1d" width="300" />

bloodgdx:
<video src="https://github.com/ZDoom/Raze/assets/57089001/9d0e0a5e-6a0a-4595-92b3-eff080620160" width="300" />

### Steps to reproduce the behaviour.

Go to the level "they are here" and break mirror.

**Comment by coelckers** [comment]
Should be fixed now. There was still a problem with the randomization scale that got applied here.
