### ISSUE TITLE
[BUG] Some Duke mods won't start because of eduke.con

### ISSUE THREAD

**Issue by fgsfds** [ZDoom/Raze#1071]
### Raze version

1.9.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When `eduke.con` is present in the duke mod zip, it's loaded instead of `game.con` https://github.com/ZDoom/Raze/blob/b383a99065589d8b2b600cf74f66eb5143b19777/source/games/duke/src/gamedef.cpp#L3159

This is not a good idea since `eduke.con` usually contains EDuke32 specific syntax which is not supported by Raze and the mod won't launch at all. Example: https://github.com/ZDoom/Raze/issues/123

It would be a better idea to ignore `eduke.con` or introduce Raze's own `raze.con` that will be loaded by default.

**Comment by coelckers** [comment]
The irony here being, of course, that this was a feature from EDuke 2.0 which Raze does mostly support
You are right, of course. The way things developed it better be disabled.

**Comment by coelckers** [comment]
Unfortunately, this won't help with dukehard. It has no fallback for other engines, although the maps themselves might work perfectly fine.
