### ISSUE TITLE
[BUG] [Duke WT] `Code: C0000005 (Access Violation - tried to read address 0000000000000000)`

### ISSUE THREAD

**Issue by flesh420** [ZDoom/Raze#1080]
### Raze version

1.9.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

Ryzen 7 3800x 8-core; Radeon RX 5500 XT

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Was just using the incinerator on aliens.

### Steps to reproduce the behaviour.

Not sure other than using incinerator.

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/Raze/files/14927549/CrashReport.zip)

**Comment by coelckers** [comment]
Unable to reproduce with latest master
