### ISSUE TITLE
[BUG] [Blood] Acid pod doesn't cause damage

### ISSUE THREAD

**Issue by markanini** [ZDoom/Raze#1088]
### Raze version

1.10.2

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Win 11 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Acid pods don't cause damage

### Steps to reproduce the behaviour.

Explain how to reproduce
1. In console type "levelwarp 6 6"
2. Go through the initial gate, dispatch the the human enemies.
3. Stand in front of the acid pod behind the right side wall, it should damage you.

**Comment by markanini** [comment]
NBlood vs Raze 

https://github.com/ZDoom/Raze/assets/15148553/f5eec09d-9db9-4d18-aa67-7f0356844b9a


https://github.com/ZDoom/Raze/assets/15148553/d044998a-af22-4227-954c-105794ae584a

**Comment by coelckers** [comment]
fixed in f9e4ce89fa8c06e9ef363bc818a122e4365761c5
