### ISSUE TITLE
[BUG] [SW] Enemy sounds are scrambled (wrong sounds play for what the enemy is doing)

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#1093]
### Raze version

Raze 1.10.2

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Enemies will sometimes play their death sound in place of their damage sound. It will sometimes get spammed as an enemy takes damage.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get dual uzis
2. Fire short bursts on evil ninjas
3. They will spam their death sound as if it was their hurt sound

### Your configuration

```ini
default
```

**Comment by ninjakitty844** [comment]
Does not happen on 1.9.2, but happens on all official releases after that.

**Comment by ninjakitty844** [comment]
Also to add to this issue, sometimes the coolie ghosts play their spawning noise when dying...? It kind of seems like the enemy sounds are scrambled.

**Comment by ninjakitty844** [comment]
Renaming this issue to more accurately reflect what is happening.

**Comment by coelckers** [comment]
fixed in 053a6875bf615aeff21f59e3c45b5531c9c5b1e8
