### ISSUE TITLE
[Feature] Support for .kpf files.

### ISSUE THREAD

**Issue by Nick1202897** [ZDoom/Raze#1096]
### Raze version

1.10.2

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I wanted to run Blood Fresh Supply with the Extra Crispy mod on Raze but features from the mod won't work due to no support for .kpf files.

### Describe the solution you'd like

Support for .kpf files added into Raze.

**Comment by coelckers** [comment]
Cannot be done. Fresh Supply is an entirely incompatible engine.
