### ISSUE TITLE
[Feature] SteamAPI/Achievement Support for Duke3D World Tour

### ISSUE THREAD

**Issue by IrisWasTaken1** [ZDoom/Raze#1098]
### Raze version

1.10.2

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Duke Nukem 3D's World Tour version has Steam achievements, which are not supported by raze.

### Describe the solution you'd like

Adding support for Duke3d achievements using Steam's API

### Describe alternatives you've considered

Could also just not even bother, I guess.

### Add any other context or screenshots about the feature request here.

This would be a really nice feature to have, allowing people to gain achievements without using the randy greasefork version, and a similar idea has been done for other games before. ([ex](https://gtaforums.com/topic/957432-steam-achievements-for-1070-1080/))

**Comment by madame-rachelle** [comment]
As far as we are aware, this is not allowed due to conflict between the Steam API license and the GPL - and there is yet to be a court case tested on this matter. Unfortunately we aren't able to afford fancy attorneys so we're not willing to wade into those murky waters. :)

**Comment by coelckers** [comment]
This is not just a GPL matter. I don't think Steam would accept if some third party software replacement messed with their achievement system - we do not even know what precisely the game does because we do not have its source.
