### ISSUE TITLE
[Question] Contributing widescreen game assets

### ISSUE THREAD

**Issue by AvinashReddy3108** [ZDoom/Raze#1101]
# Question
What's the correct way to submit widescreen versions of game assets/resources pulled in from other versions of the game?

# Context
I want to submit the widescreen version of Shadow Warrior's menu background (pulled from the Classic Redux version of the game.)

I have the tile PNG file and have managed to make it work in Raze (by slightly modifying the `sw-redux.def` file that comes with the Redux files), see Screenshot below.

![image](https://github.com/ZDoom/Raze/assets/27774996/bda898e6-55bf-490f-a31d-91928f0945ad)

# The way forward?
Should I go ahead with making a pull request which patches in the tile PNG and the respective `def` edit?
[something like this (by Phredreeke)](https://github.com/ZDoom/Raze/blob/f3cad8426cd808be5ded036ed12a497d27d3742e/wadsrc/static/filter/shadowwarrior/engine/widescreen.def#L52)

**Comment by coelckers** [comment]
Yes, just make a pull request.
