### ISSUE TITLE
[BUG] nearest sound interpolation inaccurate 

### ISSUE THREAD

**Issue by SpelzR2** [ZDoom/Raze#1103]
### Raze version

Raze 1.10.2

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It's difficult to tell whether this is a bug or should be a feature request but with nearly every Duke Nukem 3D source port the "Nearest" sound interpolation isn't as accurate to the original DOS Version as it should be. Raze is no exception. This isn't a call to change the default setting to nearest as a [previous request](https://github.com/ZDoom/Raze/releases/tag/1.10.2) suggested and more of an attempt to get closer to the original. I've made 3 clips featuring almost all weapons. Nearest (which is also the default in Eduke32) is closer to DOS but is definitely harsher in the high frequencies, while linear (default in Raze) sounds darker than DOS. Is it possible to get closer to the original DOS sound interpolation and providing a better alternative for those you'd like to use the nearest sound interpolation? I've used DosBox-X to record the DOS sounds, in the dos setup I've chosen the highest settings for the sound blaster option.

DOS sound (original):
[dos_sound.zip](https://github.com/user-attachments/files/16134935/dos_sound.zip)

Nearest (default in Eduke32, identical to Raze):
[eduke32_sound.zip](https://github.com/user-attachments/files/16134936/eduke32_sound.zip)

Linear (default in Raze, HRTF turned off):
[razesound.zip](https://github.com/user-attachments/files/16134937/razesound.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
The sound interpolation is done entirely inside OpenAL and outside the engine's control.
