### ISSUE TITLE
[Feature] A.W.O.L Support 

### ISSUE THREAD

**Issue by cutting6** [ZDoom/Raze#1108]
### Which game are you running with Raze?

Other

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

The game A.W.O.L does not show up in theseceltion menu so don't think Raze supports it or it's a bug.

### Describe the solution you'd like

I would like to be able to play A.W.O.L using the Raze source port

### Describe alternatives you've considered

I have considered using eduke32 but see how slow it is with Duke nukes on any graphic setting other than software I don't think A.W.O.L will run smoothly.

### Add any other context or screenshots about the feature request here.

https://shotsparkstudios.itch.io/awol?download

**Comment by coelckers** [comment]
Can't do, this game requires full EDuke32 feature support.

**Comment by cutting6** [comment]
This was expected
