### ISSUE TITLE
[BUG] How to show kill and secrets counters?

### ISSUE THREAD

**Issue by ksio89** [ZDoom/Raze#1109]
### Raze version

1.10.2

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

Intel Core i5-1135G7 // Intel Xe Graphics 80EUs

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I can't find any option on menu that makes secrets and kills counters to be shown like on VoidSW. Is there any associated console variable or this is a feature that hasn't been implemented yet?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by ArhumMK** [comment]
It should be in the HUD options? There should be a toggle that allows you to display level stats on screen, on automap or both.

**Comment by ksio89** [comment]
> It should be in the HUD options? There should be a toggle that allows you to display level stats on screen, on automap or both.

It is, how did I miss it lol, thanks!
