### ISSUE TITLE
[BUG] This door doesn't open in Roch 3

### ISSUE THREAD

**Issue by axredneck** [ZDoom/Raze#1112]
### Raze version

1.11pre-9-gf3cad8426 (a.k.a. latest current devbuild) 

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux. Tried both Windows devbuild under Wine and `raze-git` from AUR.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It's 03-ROCH3.MAP from https://www.moddb.com/games/duke-nukem-3d/addons/roch-series-1-8
This door doesn't open:
![Снимок экрана_20240918_202929](https://github.com/user-attachments/assets/49643a82-e2b3-4b58-a5c5-c4d6c256233a)
![Снимок экрана_20240918_202908](https://github.com/user-attachments/assets/08c52c4a-32bf-4210-a5b1-de3ba1d144cd)
But it opens in EDuke32. Also i believe it should open in DOS because the map is from pre-EDuke32 era, though i didn't try.

**Comment by coelckers** [comment]
fixed in 97a71bad5d69aa582654142dc134822967aa74be

This was one of those cases where the precision of floats was too high and had to be brought down to Build's original.
