### ISSUE TITLE
[BUG] Invalid data encountered for texture with xxx MOD

### ISSUE THREAD

**Issue by Sol1vaN** [ZDoom/Raze#1121]
### Raze version

1.10.2

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There's a problem loading xxx mod from fgsfds.
Raze shows "Invalid data encountered for texture".
Maybe because fgsfds made this on 2019 to run on eduke32.
If we check def file, this contain some like this:

```
tilefromtexture 568 { file "xxx/568.png" xoffset 0 yoffset 0 ifcrc -1065649055 }
tilefromtexture 577 { file "xxx/577.png" xoffset 0 yoffset 0 ifcrc -406725463 }
tilefromtexture 603 { file "xxx/603.png" xoffset 0 yoffset -85 ifcrc 2033971612 }
tilefromtexture 766 { file "xxx/766.png" xoffset 0 yoffset 0 ifcrc 365003540 }
tilefromtexture 869 { file "xxx/869.png" xoffset 0 yoffset 0 ifcrc 2514069626 }
tilefromtexture 963 { file "xxx/963.png" xoffset 0 yoffset 0 ifcrc -968642346 }
tilefromtexture 964 { file "xxx/964.png" xoffset 0 yoffset 0 ifcrc -1517118080 }
tilefromtexture 965 { file "xxx/965.png" xoffset 0 yoffset 0 ifcrc -867632416 }
tilefromtexture 1054 { file "xxx/1054.png" xoffset 0 yoffset 0 ifcrc -1314137471 }
```

So I think I need to change some but I don't know what.
Can someone give a hand with this?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. the original repo from fgsfds is down (i don't know why)
https://github.com/fgsfds/Duke-Nukem-3D-Nude-Patch
3. download the mod from here: 
[dukexxx.zip](https://github.com/user-attachments/files/17608980/dukexxx.zip)
4. try to load on raze and check the console log, I've attached my own log here:
[raze.log](https://github.com/user-attachments/files/17608983/raze.log)

### Provide a Log

Invalid data encountered for texture K:/Add-Ons Juegos/Duke Nukem 3D/Ports/Raze/raze-1.10.2/duke3d/:sprites/dukexxx.zip

**Comment by coelckers** [comment]
Your setup is wrong. 'sprites' is a reserved folder name for the engine, Every file you put there will be tried to be loaded as an image. And your zip file isn't an image so it will result in an error.

**Comment by Sol1vaN** [comment]
many thanks for the aclaration.
but...
the mod still can't be loaded on raze, look:
![1](https://github.com/user-attachments/assets/e48cc82e-d707-4361-9628-a5fc6a99b6a8)

the same exact file, on eduke32 work fine, look:
![2](https://github.com/user-attachments/assets/0e25a576-ace6-4074-b0c7-ba894ced33ca)

i think is a problem of compatibility, but i don't be sure.
what i need to change to make this compatible with raze?
