### ISSUE TITLE
[BUG] [Blood] Not enough ammo with guns akimbo causes the guns to go to a single state

### ISSUE THREAD

**Issue by michaeljhkim** [ZDoom/Raze#115]
I only tested on the shotguns, but other weapons probably apply. So when you don't have enough ammo for the shotguns (less then four shells), the sprites will revert back to a single shotgun while the akimbo timer still goes on.

**Comment by coelckers** [comment]
Sounds very much like this should behave. If you cannot fire two guns it makes no sense to keep both on screen
Since you are reporting several such issues, please do us a favor and before reporting, cross check with either NBlood or BloodGDX if they show the same behavior..

**Comment by Mechanical-sanity** [comment]
> Sounds very much like this should behave. If you cannot fire two guns it makes no sense to keep both on screen
> Since you are reporting several such issues, please do us a favor and before reporting, cross check with either NBlood or BloodGDX if they show the same behavior..

Okay, I just checked this one, and I can confirm that this was expected behavior. Strange because I can swear that this was not in other engines. But the other stuff are things that I can't find in one engine or another
