### ISSUE TITLE
[BUG] [Duke 3D] High res title textures load zoomed and stretched

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#240]
This is from Duke's HRP but it also happens with GZDoom as well as can be seen with [this upscale pack](https://www.doomworld.com/forum/topic/99021-doom-neural-upscale-2x-v-10/), indicating a backend issue (can do a separate report if required).

![image](https://user-images.githubusercontent.com/48643140/103256510-a59e0d00-49e1-11eb-9f82-f91d7946a742.png)

![image](https://user-images.githubusercontent.com/48643140/103256562-d8480580-49e1-11eb-8e58-74dd17ece6c7.png)

**Comment by coelckers** [comment]
Can't do much about it. It's a classic case of incompatible resources fighting for the same data. You have to disable hires replacements when loading these packs.

**Comment by mjr4077au** [comment]
Is that for GZDoom as well?

**Comment by mjr4077au** [comment]
Thanks, yes confirming works fine with -nowidescreen passed at runtime. Apologies for the noise 😄.
