### ISSUE TITLE
[BUG] [SW] Potential FAF issues

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#243]
While testing out [swc20.grp](https://www.moddb.com/games/shadow-warrior/downloads/swc20/) when looking at #239, I observed some glitchy FAF action which I'm unsure is an issue with our port or something to do with the mod.

Video from swc20.grp: https://youtu.be/23TtI1lXz4I

EDIT: Removed erroneous information I thought might have been related which is only isolated to VoidSW's FOV implementation.

**Comment by mjr4077au** [comment]
Sorry, tested in SWP (like I should have) and its definitely the mod.

**Comment by coelckers** [comment]
Yeah, it's very easy to screw this up - the potential issues are very much the same as with ZDoom's original stacked sector code (i.e. if some view blocking geometry gets in the way on the portal layer the view clipping will not work properly.)

There's one map in the mission packs that also produces quite extreme HOM when standing in the wrong place.

**Comment by sinisterseed** [comment]
Emergency Room's roof, basically.
