### ISSUE TITLE
[Duke]: 3D actor model walking is rough.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#248]
We discussed this at some point in the past somewhere, but when an actor is walking (let's use a Liztrooper at the start of E1L1), its walking movement is rough and gives the appearance I'd expect if it was being interpolated with the wrong smoothratio or something.

I've tried to work out what's going on, but can't. What I know is:

- Only occurs when the actor is on the ground. If the Liztrooper is flying, seems fine.
- If you open the console which pauses the game, the actor keeps animating, but the glitch isn't apparent.
- If you drop the fps down to 30 to match the console (factoring in the above), it does not fix the issue.

From this, I thought it was game-side, but there's strange movement in SW as well.

I can't exactly get a video of it as the Windows recorder only does 30fps and its not enough to see it properly, but should be pretty apparent when a/b'ing between us and EDuke32.

**Comment by coelckers** [comment]
Models again...
