### ISSUE TITLE
[Duke]: E1L1 fan isn't replaced with model from HRP.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#249]
Just noticed this as well.

![image](https://user-images.githubusercontent.com/48643140/103476400-47ba5c80-4e09-11eb-80ae-7be3a862c531.png)

![image](https://user-images.githubusercontent.com/48643140/103476394-3f622180-4e09-11eb-8cc9-9b1a6948b9e6.png)

**Comment by mjr4077au** [comment]
So, turns out I accidentally was loading the Polymer HRP with Polymost 😢. However, it still works in EDuke32 and not with us:

![image](https://user-images.githubusercontent.com/48643140/103476515-bd72f800-4e0a-11eb-82d2-a5db0115360a.png)

**Comment by coelckers** [comment]
More models...
