### ISSUE TITLE
[Question] Build licensing

### ISSUE THREAD

**Issue by poperigby** [ZDoom/Raze#257]
Hey, I see that Build uses a weird custom license. Would it be possible to use the [code from Duke Nukem 3D](https://github.com/videogamepreservation/dukenukem3d) to make this source port fully open source?

**Comment by mjr4077au** [comment]
The code that constitutes the game is in two parts, the engine code (under the BUILD license) and the game code (under the GPL 2.0 or newer). What you've linked there is the game code and does not include engine code. We need the engine code and as such we're still bound to the Build license, just like EDuke32 and other ports.

**Comment by PopeRigby** [comment]
Ah I see. That sucks. Maybe somebody can clean room reverse engineer the code at one point.

**Comment by coelckers** [comment]
Sadly that is very unlikely. This code is in a class of its own and that's not a compliment.
