### ISSUE TITLE
[BUG] [Powerslave/Exhumed] Flying spiders

### ISSUE THREAD

**Issue by RavenMacDaddy** [ZDoom/Raze#274]
I think it's the second map, maybe the third, don't remember, but one of the spiders that was coming out of hole suddenly was crawling in the sky.

I couldn't hit it and it couldn't hit me, but it was constantly aggro.

Edit: I was supposed to have a screenshot of it, but somehow I must have overwritten it... anyhow, hopefully there's some technical reason why this bug might occur, and I will of course update with a screenshot if I run into it again.

**Comment by coelckers** [comment]
This sounds like it somehow got stuck somewhere. Unfortunately without anything to check there's not much that can be done., A savegame would have been nice.

**Comment by sinisterseed** [comment]
I think he is talking about this tunnel on Dendur:

![Exhumed_0000](https://user-images.githubusercontent.com/57503728/109548908-e5fb3380-7ad5-11eb-8249-a7547b1dfd16.png)

Just had a spider which did indeed exit "into the sky" briefly, but then it just magically dropped on the ground. It was not invulnerable though. So not sure what to make of it.

**Comment by coelckers** [comment]
Build physics at work, no doubt about that. I don't think there's anything here that could be fixed without introducing far worse problems.

**Comment by RavenMacDaddy** [comment]
Probably so since I didn't encounter it when I played the game previously on Raze. 

I'll see if I can get some examples at a later date.
