### ISSUE TITLE
[BUG] [Duke 3D] Warning in GAME.CON when loading in Raze 0.9

### ISSUE THREAD

**Issue by mortimerprime** [ZDoom/Raze#285]
I get the following WARNING when loading up Duke 3d in Raze (0.9) >>> see attached

![GAME_CON](https://user-images.githubusercontent.com/57038268/110722445-42e6a000-81e0-11eb-8b12-b76e212c2b7d.png)

Is this something work investigating? Know how/whether I can fix it?

Thanks!
(keep up the awesome work!)
Alex

**Comment by sinisterseed** [comment]
Nope, it's not a real issue.

**Comment by coelckers** [comment]
The real issue is that the original CON compiler had such poor syntax checks that some errors slipped through.
Despite that, in this case the script still works as intended, but removing the compile message would be a disservice to modders.
