### ISSUE TITLE
Force Timidity because Fluidsynth shows a segment fault error

### ISSUE THREAD

**Issue by orderorder** [ZDoom/Raze#293]
With the "Fluidsynth" plugin in "Duke Nukem" the music play at the begining but the game freezes when im going to start a episode and shows a "segment fault". The same occurs me when i play Doom with "Gzdoom" because of that i change to "Timidity" plugin but in "Raze" i cant change or force to "Timidity". How can i do that?

Thanks for this great project.

**Comment by sinisterseed** [comment]
Works fine for me, so need more info.

What operating system? The other MIDI players are not available in Raze because of licensing concerns.

**Comment by alexey-lysiuk** [comment]
Is it on Ubuntu 20.04 or probably on any other distro that has FluidSynth built with libinstpatch support? If so, this problem has nothing to do with Raze.
You need to rebuild ZMusic with dynamic loading disabled by setting `DYN_FLUIDSYNTH` to `OFF`.

**Comment by coelckers** [comment]
If that solves the crashing issue, shouldn't it be the default for building ZMusic on Linux, then?

Anyway, we cannot set ZMusic to Timidity for Raze because due to licensing conflicts it cannot use any of the others aside from FluidSynth.

**Comment by alexey-lysiuk** [comment]
> If that solves the crashing issue, shouldn't it be the default for building ZMusic on Linux, then?

In my opinion, disabled dynamic loading for third-party library is a reasonable default for all platforms except Windows.

**Comment by orderorder** [comment]
> Is it on Ubuntu 20.04 or probably on any other distro that has FluidSynth built with libinstpatch support? If so, this problem has nothing to do with Raze.
> You need to rebuild ZMusic with dynamic loading disabled by setting `DYN_FLUIDSYNTH` to `OFF`.

Im using Manjaro Linux in his last version. Following your instructions the game runs well
