### ISSUE TITLE
[Blood] Option to load user content/read .ini's

### ISSUE THREAD

**Issue by NineKain** [ZDoom/Raze#312]
To run Blood's Death Wish mod I have to drag and drop the ini file to Raze.exe, not terribly annoying, but I wish there was a better way of doing it.

**Comment by coelckers** [comment]
Define 'better'.

**Comment by NineKain** [comment]
Loading the inis via a menu, like NBlood does, or creating a "user content" tab in the chapter select screen, like BloodGDX

**Comment by NightFright2k19** [comment]
In BloodGDX you can for example load any custom .ini through the menu. You could e.g. load Death Wish's dw.ini and have the mod content zipped as e.g. dw.zip and the mod would be loaded ingame.

**Comment by mjr4077au** [comment]
I nominated myself to do a GUI frontend for Raze but with work commitments at the moment, I have not been able to give it the time and attention it needs which is a real let-down for the team and the project.

I'm hoping to start back up on that next week but we're ridiculously short-staffed at present.  The intention of the new GUI would be to ease mod loading, it would also scan zip files for INIs and in the event there are multiple, allow the user to pick what to load.

**Comment by mjr4077au** [comment]
An in-game map loader has since been added.
