### ISSUE TITLE
[BUG] [Duke 3D/SW] Linux reflections are broken when using Vulkan and open source AMD drivers

### ISSUE THREAD

**Issue by FurtiveDolus** [ZDoom/Raze#313]
Running in an up-to-date Manjaro with a Vega 56 GPU running Mesa and Radv for Vulkan. The reflections in mirrors are corrupted/bugged and happens in the two supported games I have: Duke3D and Shadow Warrior from GOG. Reflections work fine in OpenGL. Version tested was compiled from the AUR. 

![Screenshot from 2021-04-13 17-19-15](https://user-images.githubusercontent.com/49626275/114628396-69cf4080-9c7c-11eb-91c9-7be96ab6205e.png)

**Comment by Cacodemon345** [comment]
The new renderer fixes this mirror reflection glitch.

**Comment by coelckers** [comment]
Closing because Polymost no longer exists.
