### ISSUE TITLE
[DukeDC] Interpolation doesn't work when on some elevators in Smithsonian Terror map when jumping/crouching

### ISSUE THREAD

**Issue by Cacodemon345** [ZDoom/Raze#384]
As the title says.

If you jump/crouch on some elevators (especially the ones where the elevator will actually take you to a different area of the map), the camera will jitter.

**Comment by coelckers** [comment]
Now, if this code was even close to being manageable... :cry:

**Comment by mjr4077au** [comment]
Tested this and it's been there as far back as 0.7.0.

Save game is from 326a0798a1c1d14955fb466e89a4fd0a9f1f8c1d for convenience. [save0000.zip](https://github.com/coelckers/Raze/files/6721503/save0000.zip)

**Comment by coelckers** [comment]
@mjr4077au 

Please check if your fix for the warp elevators fixes this. Your commit description makes it very likely

**Comment by mjr4077au** [comment]
> @mjr4077au
> 
> Please check if your fix for the warp elevators fixes this. Your commit description makes it very likely

@coelckers confirmed fixed now 😁

**Comment by coelckers** [comment]
Funny. When I fixed the other bug in here I immediately noticed the bogus interpolation stuff which I had planned to revisit later.

**Comment by mjr4077au** [comment]
I was irked by it as well but it wasn't an issue with the branch so I didn't report it. The setup in these SEs are pretty rough, but the elevator is 100% now.
