### ISSUE TITLE
[Feature] Please add in OPL3/FM Synth emulation

### ISSUE THREAD

**Issue by toddfraser88** [ZDoom/Raze#408]
Please add in OPL3/FM Synth emulation - I prefer the old school SB16 FM synth sound over Fluidsynth.

**Comment by coelckers** [comment]
This is not possible due to licensing restrictions. The OPL synth in EDuke32 i not compatible with the rest of the music system and the OPL synths I have in GZDoom are not compatible with the Build license.

Any such package would be impossible to distribute.

**Comment by Gaerzi** [comment]
Perhaps Aaron Giles' [YMFM](https://github.com/aaronsgiles/ymfm) could be useful here? It's under the BSD license, which AFAIK should make them possible to include in ZMusicLite.
