### ISSUE TITLE
[Question] Shadow Warrior alt fire option missing

### ISSUE THREAD

**Issue by P33P33M4NTRUE** [ZDoom/Raze#412]
Simple enough, the alt fire option for Shadow Warrior seems to be missing from the Controls menu. Please take a look into this as I cannot really properly play the game without specific alt fire modes.

**Comment by coelckers** [comment]
SW has no alt fire option. It works by switching the weapon to an alt-fire mode by re-selecting the weapon slot and then using the primary fire to shoot.
