### ISSUE TITLE
Crash on Ubuntu 20.04.02 LTS with Fluidsynth

### ISSUE THREAD

**Issue by m210** [ZDoom/Raze#452]
I'm getting crashes after the intro logo on Ubuntu 20.04.02 LTS with KDE Plasma. Place "raze.sf2" in the game folder doesn't help. 
[raze-crash.log](https://github.com/coelckers/Raze/files/6739802/raze-crash.log)

**Comment by alexey-lysiuk** [comment]
Update ZMusic to 1.1.8.

**Comment by mjr4077au** [comment]
@alexey-lysiuk I'm going to re-open this for now. m210 and I were discussing it on Discord just now, he did not have `raze.sf2` in a `soundfonts/` subdirectory. When he correctly placed the file, it worked fine. The SDL frontend for Raze/GZDoom should properly handle the lack of sf2 file like the win32 frontend does.

**Comment by alexey-lysiuk** [comment]
Where does Windows backend handle this? I have a suspicion that it doesn't crash just because of old FluidSynth without libinstpatch support.

**Comment by mjr4077au** [comment]
I'm sorry, you're probably right. Under windows it says "Could not find patch set raze", but this originates from ZMusic and not the game. I'll re-close again for now.

**Comment by coelckers** [comment]
Let's wait and see if upgrading to newer ZMusic will fix the crash. Obviously it should report a proper error and not outright crash when no patch set can be found.

Still, we really need a better Linux setup so that these issues don't even happen.

**Comment by alexey-lysiuk** [comment]
The given crash is inside libinstpatch function that loads DLS sound font. Indeed, it's different from "usual" crashes because of FluidSynth library reloading. However, it's a mystery why it touches DLS loading code at all.
