### ISSUE TITLE
[Powerslave/Exhumed, Raze v1.1.3] Game ignores autoaim setting in options. Also, no hitscan-only option.

### ISSUE THREAD

**Issue by Shockwave508** [ZDoom/Raze#499]
In Powerslave/Exhumed, the game ignores your current autoaim setting, even when you literally have it turned off. In addition, there is no "Hitscans Only" option for autoaim.

**Comment by coelckers** [comment]
Let's just say that aiming in this game is so totally screwed up that I'm not even sure it can all be fixed...

**Comment by arrowgent** [comment]
commit that seems to break the aiming

https://github.com/coelckers/Raze/commit/395de23b2136434c727a880cfb6c05d133cbdd1d

compared v 1.1.0, 1.1.2, to 1.1.3 and 1.2.0 and 1.4.1

v 1.1.2 and before the aim works correctly (autoaim off)

if you want manual aiming (or any aiming at all) then use v1.1.2 until a fix can be made

im going to look to see if reverting this commit in the current release v1.4.1 seems to "fix" the aim

**Comment by arrowgent** [comment]
just comparing to the changes since nblood/eduke32

https://github.com/nukeykt/NBlood/blob/master/source/exhumed/src/bullet.cpp
https://github.com/nukeykt/NBlood/blob/master/source/exhumed/src/gun.cpp

i understand trying to clean up the code, looking at the commits

**Comment by coelckers** [comment]
This was fixed recently but is still in a work branch
