### ISSUE TITLE
Voxels do not render properly

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#508]
Looks like voxels in Raze have either holes or weird lines. This is "old" renderer and this issue has been with Raze since its beginning . And it seems the more thin a voxel model is, the more visable this issue is.

Examples:

![image](https://user-images.githubusercontent.com/17529329/129479049-0b0e6148-45db-4e41-b2b6-b05bca9fa7e2.png)
![Duke_0002](https://user-images.githubusercontent.com/17529329/129479083-6dde8318-69c5-4f7e-a76c-9b258a6dc8c8.png)

**Comment by Talon1024** [comment]
I think I've seen it happen in the new renderer with the [Blood voxel pack](https://www.moddb.com/mods/blood-voxel-pack/downloads/blood-voxel-pack-094-bloodgdx-nblood-raze1) and some of the flare boxes.

**Comment by coelckers** [comment]
Since Polymost has been removed, so has this issue.
