### ISSUE TITLE
[Feature] Support for Witchaven 1 & 2

### ISSUE THREAD

**Issue by AntonZab** [ZDoom/Raze#552]
### Raze version

1.1.3

### What Operating System are you using?

Windows 7

### Which game are you running with Raze?

Other

### Is your feature request related to a problem? Please describe.

Hello. Please add 2 games on buid Engine.  Witchaven 1 and 2.
Source codes are available on the internet.

**Comment by coelckers** [comment]
Do you have the magic wand to make the available source usable? Unless you say 'yes' the answer is 'no'.

**Comment by AntonZab** [comment]
BuildGDX used this. And made a port of this games
