### ISSUE TITLE
[Feature] Please enable actions artifacts for Linux

### ISSUE THREAD

**Issue by nesper8** [ZDoom/Raze#570]
### Raze version

Git and Release

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora 34

### Is your feature request related to a problem? Please describe.

Please do enable actions artifacts for linux gcc and/or clang

**Comment by mjr4077au** [comment]
Agreed with \_mental\_, they're of no use unless your environment is set up identically to our CI environment. If you need assistance building Raze on your device, please ask on the ZDoom forums or move to Linux distribution that makes building code easier (Arch Linux et, al.).
