### ISSUE TITLE
[BUG] [Duke 3D] Shotgun firing animation - vanilla bug

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#585]
### Raze version

Latest DEV version 9/11/2021

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

A known issue and recently been posted on the EDuke32 discord by Babby_32, is the fact that when firing the shotgun in Duke3D it actually uses the wrong tile. There is an unused muzzle flash of the shotgun that is not being used (2614). Instead when firing, it uses 2615 twice. 

Is this something that could be fixed in Raze? It's an original "bug" but it looks quite stupid when you're focused on the firing animation. 

![01](https://user-images.githubusercontent.com/71838912/140953861-d731f60d-d1da-44c1-98f4-3676988e6b72.png)

![02](https://user-images.githubusercontent.com/71838912/140953879-69e1359f-f32b-40e4-810f-d4bddd286d90.png)

### Describe the solution you'd like

Use the first muzzleflash 2614 and then 2615.

**Comment by mjr4077au** [comment]
Like what Terminx said not too far down on the Discord post about the freeze weapon, fixing in the source could cause problems for a number of mods that replace art but rely on original mechanics. For that reason, we'll leave this as it is as well.

![image](https://user-images.githubusercontent.com/48643140/142387440-91a4a401-bfea-4d85-8594-addc40e09707.png)

**Comment by coelckers** [comment]
Doom has a similar issue with the plasma gun and it won't get fixed for the same reason.
