### ISSUE TITLE
[BUG] Weird shade value on enemy actor in Duke Penthouse Paradise with GLES + Palette Emulation

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#599]
### Raze version

1.4pre

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

One for @emileb when he has a moment of time.

There is an actor in Duke Nukem's Penthouse Paradise which under a combination of OpenGL ES and Palette Emulation does not have any light until the actor has completed their first cycle.

https://youtu.be/kKX3uvTSaAg

In this video, we can see toggling the difference Palette Emulation on/off makes. We can also see after the actor has shot me, its fine again. This doesn't happen under OpenGL.

### Steps to reproduce the behaviour.

1. Launch the game with OpenGL ES renderer.
2. Enable Palette Emulation if its disabled.
3. Load below save.
4. Go to the actor in question and witness the occurrence

[save0001.zip](https://github.com/coelckers/Raze/files/7698059/save0001.zip)

I can confirm also that its not limited to this save. If you start a fresh game and go to this spot, the issue occurs.

If I go to the actor while he's broken, have him shoot me and return to normal, if I reload the save the issue never occurs. It's just on the initial launch of the game.

**Comment by mjr4077au** [comment]
Same thing as this can be seen in Exhumed (assuming its the same thing). It rights itself when you get closer to it.

![Exhumed_0011](https://user-images.githubusercontent.com/48643140/147631840-046a4034-edb7-4b45-ba16-b5eadfb87e33.png)

![Exhumed_0012](https://user-images.githubusercontent.com/48643140/147631849-2d50857c-dd8c-42e8-ad61-e768dcdab9ff.png)

https://user-images.githubusercontent.com/48643140/147631901-72ad3e12-56c8-4d1d-afb0-522f492ae692.mp4

**Comment by emileb** [comment]
Sorry I took too long to look at this, seems the savegame is too old to load on the latest code. Is this still and issue do you know?

**Comment by mjr4077au** [comment]
Hmmmm it loaded fine for me yesterday? Do you have Penthouse Paradise? It's not an original map.

**Comment by emileb** [comment]
> Hmmmm it loaded fine for me yesterday? Do you have Penthouse Paradise? It's not an original map.

Oops sorry I missed that part, I will find it and try again. Thanks

**Comment by mjr4077au** [comment]
PM me on the ZDoom forums if you get stuck

**Comment by mjr4077au** [comment]
Doesn't appear to be occurring anymore, closing off.

**Comment by mjr4077au** [comment]
Re-opening this as I was able to get the Exhumed issue to occur again in a successive test.

To repeat the above, just start Exhumed with GLES and P/E enabled, play the first level and observe the torches not far from the start are white until you get close to them.
