### ISSUE TITLE
[BUG] Sprite flickering in Duke WT E5L1 with all render backends.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#600]
### Raze version

1.4pre

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

NVIDIA GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Another one for @emileb when he has a chance. For Emile, please let me know if this is the best place for reports for you to look at or whether the ZDoom forums are.

GLES backend:
![image](https://user-images.githubusercontent.com/48643140/145699576-7cc5a03b-ac4d-410c-82b4-4ea38fc998e1.png)

OpenGL backend:
![Duke_0035](https://user-images.githubusercontent.com/48643140/145699585-66012857-73fa-49f7-8e59-c4b674d53c7f.png)

### Steps to reproduce the behaviour.

1. Load up game with GLES backend.
2. Load below save.
3. Observe issue.

You can get closer to the problem spot if you noclip out of the map's bounds to get there. Its probably a corner case issue, especially given its location in the map, but whatever this issue is could manifest itself in any number of ways or spots.

[save0007.zip](https://github.com/coelckers/Raze/files/7698078/save0007.zip)

**Comment by emileb** [comment]
Thanks @mjr4077au I'll take a look. Yes this is the best place to report, I don't get notifications on ZDoom so I can easily miss stuff

**Comment by mjr4077au** [comment]
This appears to be occurring with all render backends now...

**Comment by coelckers** [comment]
fixed in 6c3d03cd48b2d46924d8b6f2b42aaacf4701d9b6

This is actually a map bug, but Polymost didn't choke on it.
