### ISSUE TITLE
[BUG] Window glitch in Blood's E1M1 on new renderer and GLES backend.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#607]
On the roof of the crypt outside the mortuary, if you jump in place, the windows partially lose their transparency. This only occurs in combination of the new renderer and the GLES backend. OpenGL on either renderer doesn't exhibit the issue, nor does Polymost on GLES as well.

New renderer on GLES:

https://user-images.githubusercontent.com/48643140/146329916-c4a0ea86-daa3-4462-afbd-79edc09caa97.mp4

Polymost:

https://user-images.githubusercontent.com/48643140/146329950-dbcef1db-b086-4ccb-a209-ee12a98f8cd5.mp4

This save will bring you to the location, but please note this save was taken against the `develop` branch and not master.
[save0000.zip](https://github.com/coelckers/Raze/files/7725424/save0000.zip)

**Comment by coelckers** [comment]
My suspicion here is that it has something to do with the hardware clip planes. That area is a portal setup and if clip planes are not used it may glitch a bit.

**Comment by mjr4077au** [comment]
Cannot reproduce anymore.
