### ISSUE TITLE
Raze 1.3.1: Broken mirrors on macOS + Vulkan

### ISSUE THREAD

**Issue by warrex1979** [ZDoom/Raze#608]
Mirrors do not work on macOS (M1 SoC) when using the Vulkan renderer (e.g. in the bathroom in E1M1 of Duke3D). In OpenGL this works and Windows + Vulkan also works fine.

**Comment by coelckers** [comment]
I wonder what MoltenVK did wrong then...

**Comment by warrex1979** [comment]
Are you sure that MoltenVK ist the culprit? Just saw that #313 might be related.

**Comment by arrowgent** [comment]
indeed, works fine on nvidia + linux vulkan

**Comment by mjr4077au** [comment]
@warrex1979 any updates on this with a current developer build? https://devbuilds.drdteam.org/raze-mac/

There's been a lot of Vulkan work behind the scenes, with our ZVulkan library etc. The issue may be resolved by happenstance.

**Comment by mjr4077au** [comment]
On second thoughts, I'm going to close this. It's unclear whether this was with Polymost or our new renderer. The former is gone and as per the previous message, a lot's changed RE: Vulkan recently. I'd have heard from Rachael or Candice if this was ongoing as they're both on macOS.

**Comment by warrex1979** [comment]
> @warrex1979 any updates on this with a current developer build? https://devbuilds.drdteam.org/raze-mac/
> 
> There's been a lot of Vulkan work behind the scenes, with our ZVulkan library etc. The issue may be resolved by happenstance.

Mirrors work now. Thank you.
