### ISSUE TITLE
[Feature] Two voxels placed in the exact same spot should not render together

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#609]
### Raze version

Raze 1.3.1

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Mappers sometimes place two sprites in the exact same spot for shading purposes. So one side is bright, the other is dark. The problem emerges when voxels join the party. Both will be rendered in the same spot, causing ZOffset fighting issue.

### Describe the solution you'd like

This problem exists in Polymost and your new renderer. Interestingly enough, in the classic renderer (which Raze doesn't have, but eduke32 does) only ONE side is rendered, depending on where is the player.  It would be great to see such feature in either Polymost or in your new renderer if it's even feasible to do.

### Add any other context or screenshots about the feature request here.

![Duke_0003](https://user-images.githubusercontent.com/17529329/146686902-dfc914e8-4383-4c0e-9bac-dce464719661.png)

![Duke_0004](https://user-images.githubusercontent.com/17529329/146686904-ff18ead4-d2fc-4e69-984e-04506e2859fd.png)

![Duke_0005](https://user-images.githubusercontent.com/17529329/146687170-a51907fb-6efe-4d19-86d1-eaf4ab792425.png)

**Comment by Dzierzan** [comment]
And this is how it looks like in eduke32 classic renderer:

![duke0003](https://user-images.githubusercontent.com/17529329/146688787-91db8fc4-15a9-461a-af32-236fa355eed9.png)
![duke0004](https://user-images.githubusercontent.com/17529329/146688788-0f3c7620-70b2-4425-a181-ac24a5559f5a.png)

**Comment by coelckers** [comment]
This is plain and simply impossible. The software renderer has no depth buffer, it just renders both voxels and the second one overdraws the first. With depth buffering this cannot work.
