### ISSUE TITLE
[Duke] [Duke 3D] Compatibility with KickAss

### ISSUE THREAD

**Issue by tatude** [ZDoom/Raze#611]
When trying to play Duke Nukem with the [KickAss Duke mod](https://www.moddb.com/mods/kickass-duke/downloads), the first (eventually fatal) error is `maximum number of game variables exceeded`.

The maximum value is apparently set here:
https://github.com/coelckers/Raze/blob/fefc9e91dadccb4a47e4dc7493c679fc11e6698e/source/games/duke/src/gamevar.h#L12

Could the value be increased e.g. to 1024, or could it at least be modifiable via a startup argument?

**Comment by coelckers** [comment]
Extending the number of gamevars won't help you - this mod makes heavy use of EDuke32 features and is not compatible with other ports.
