### ISSUE TITLE
[BUG] Loading an expansion like RR Route 66 or Blood Cryptic Passage doesn't get remembered in the launcher.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#616]
Loading something like Route 66 as below will make the launcher use the first item in the list on successive launches.

![image](https://user-images.githubusercontent.com/48643140/148664564-b71f8076-23a8-4ab8-91e0-4fdedf8c2997.png)

![image](https://user-images.githubusercontent.com/48643140/148664572-08c3f14e-f6ac-4ef3-a27a-745f4e9dd85b.png)

**Comment by coelckers** [comment]
Unfortunately I do not have any setup anymore where I could load such a thing. I have cleanly zipped them all up and then deleted the GOG folders.
The code to check the default game is in gamecontrol.cpp SetupGame(), line 721 and on. Apparently the saved name and what's internally present don't match in these cases.
