### ISSUE TITLE
[BUG] vid_scalemode overrides cause issues

### ISSUE THREAD

**Issue by madame-rachelle** [ZDoom/Raze#617]
### Raze version

1.4pre-1251-ga50430bf6

### What Operating System are you using?

Windows 11

### Relevant hardware info

NVidia GTX 1650 - AMD Ryzen 7 3800X 8-Core Processor 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running Raze with `vid_scalemode 2` - two bad things happen:

First - if it is already set during the menu sequence (before entering a game) the game will freeze when trying to start a new game.

Second - the HUD is squished in all games I've tried so far.

![image](https://user-images.githubusercontent.com/18584402/148683693-45c1fb97-7ae1-4266-9e27-6a729ee01e59.png)
^ Native ^
![image](https://user-images.githubusercontent.com/18584402/148683703-47a0a82b-1efc-41f4-86bb-3751df2ccc71.png)
^ HUD is squished in scaled mode ^

### Steps to reproduce the behaviour.

Explain how to reproduce
1. `vid_scalemode 2` ccmd

### Your configuration

```ini
https://cdn.discordapp.com/attachments/384932761984696321/929725644655431700/message.txt
```

### Provide a Log

https://cdn.discordapp.com/attachments/384932761984696321/929725719955779624/message.txt

**Comment by coelckers** [comment]
This doesn't look 100% correct in GZDoom as well. But I have to admit I'm at a loss how this works. I haven't written this code. It looks like it treats 640x400 as a 16:10 resolution for rendering some things.
I was unable to reproduce the freeze.

**Comment by madame-rachelle** [comment]
I'll try and take a look at this, myself, but no guarantees I can come up with anything. It's possible I may have to recompile the entire project from scratch, though, if you can't get the freeze.

**Comment by madame-rachelle** [comment]
Okay I can't be 100% sure of this but this seems awkward - it seems like the freeze is because I was in Vulkan, and Raze is still sending commands to the OpenGL driver, which obviously would not work since it has no context. I'm not able to get much out of the stack trace because it's full from its own internal dll calls.

**Comment by coelckers** [comment]
I still cannot get the freeze, even on Vulkan.

**Comment by madame-rachelle** [comment]
Might be related to my config then, I just did a build-from-scratch and am still getting the freeze.

**Comment by mjr4077au** [comment]
I've fixed the HUD aspect ratio and have kind of assumed the hanging doesn't occur anymore 😅😁.
