### ISSUE TITLE
[BUG] [Duke 3D] Launch Facility Remake - inaccessible sector

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#623]
### Raze version

Latest devbuild15/1/2022

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm playing the Lauch Facility remake map downloaded from here : https://msdn.duke4.net/hotlaunchfacility.php

On top of the stairs, the stairs suddenly stop and the room further is not accessible. It is however in EDuke32.

Eduke32

![duke0002](https://user-images.githubusercontent.com/71838912/149636405-cb8228dd-49fa-4086-9e19-70eddcdfaf0f.png)

Raze

![Duke_0000](https://user-images.githubusercontent.com/71838912/149636419-4021877e-74c8-4fca-8cdf-63d2e49ceb2e.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the user map: https://msdn.duke4.net/hotlaunchfacility.php
2. Load the savegame provided:
[save0000.zip](https://github.com/coelckers/Raze/files/7875818/save0000.zip)
3. compare with EDuke32

**Comment by coelckers** [comment]
This map uses EDuke32's TROR feature which Raze does not support.
