### ISSUE TITLE
[BUG] Crash near end of map 2 in SW

### ISSUE THREAD

**Issue by markanini** [ZDoom/Raze#631]
### Raze version

1.4pre-1319-gc11000e4c

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

A crash happens when I enter the last area in map02 Zilla construction in the main SW campaign.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load save file
2. Enter underwater 
3. Proceed through the underwater area
[save0000.dsave.txt](https://github.com/coelckers/Raze/files/7919172/save0000.dsave.txt)

**Comment by coelckers** [comment]
I've tried several times and was unable to get a crash there.

**Comment by markanini** [comment]
Can I upload a dump or something?

**Comment by markanini** [comment]
Here a crash report anyway
[CrashReport.zip](https://github.com/coelckers/Raze/files/7921893/CrashReport.zip)
.

**Comment by mjr4077au** [comment]
@markanini is there any chance you can test this one again, please? There's been tonnes of work, it's likely resolved.

**Comment by markanini** [comment]
With https://github.com/ZDoom/Raze/actions/runs/3668247426 It lets me proceed to the end level screen as expected.
