### ISSUE TITLE
[BUG] Wrong Sprite Render Order

### ISSUE THREAD

**Issue by madame-rachelle** [ZDoom/Raze#645]
### Raze version

1.5pre-51-gb7cb878ad

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 11

### Relevant hardware info

NVidia GTX 1650 - AMD Ryzen 7 3800X 8-Core Processor

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Wrong sprite render order.

To put it quite simply: a sprite on a more distant wall is rendered in front of the vent sprite here:
![image](https://user-images.githubusercontent.com/18584402/152476199-448fd12b-096c-4c83-9a01-da8baa51433b.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load attached save game. Base: DukeDC.grp (over Atomic Edition 1.5)
[wrong-render-order.zip](https://github.com/coelckers/Raze/files/8000295/wrong-render-order.zip)

### Your configuration

```ini
https://cdn.discordapp.com/attachments/384932761984696321/939027945601790012/raze-config.zip
```

**Comment by coelckers** [comment]
This was fixed several months ago
