### ISSUE TITLE
[BUG] Blood: Rotating platforms don't rotate player view

### ISSUE THREAD

**Issue by carnivoroussociety** [ZDoom/Raze#656]
### Raze version

Raze 1.5pre-103-gb6eadbccb

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The rotating platform in E6M4 does not rotate the player's yaw angle as it's supposed to. I have checked with both DOS 1.21 and NBlood and confirm that they function the same.

While `TranslateSector()` does update the sprite's angle it does not account for player sprites, and may need updating like how [teleporter triggers were fixed](https://github.com/coelckers/Raze/issues/515) in a similar report. I've attached a video of the latest version of Raze vs NBlood.

https://user-images.githubusercontent.com/38839485/156319818-75061c63-52be-4fcb-87a7-d7fddddcbb61.mp4

https://user-images.githubusercontent.com/38839485/156319908-149b0273-580b-4b50-96e5-7e691189ab90.mp4

### Steps to reproduce the behaviour.

1. Load level E6M4
2. Progress to rotating platform area of level
3. Stand on platform and trigger platform lever to rotate

**Comment by coelckers** [comment]
Added in a work branch
