### ISSUE TITLE
[BUG] Shadow warrior and Blood shadows not working properly with fog off

### ISSUE THREAD

**Issue by Swordman14** [ZDoom/Raze#660]
### Raze version

raze-x64-1.5pre-54-g0d54237ee

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU: Intel i3 9100f GPU: Radeon Rx 550 Ram: 12 gb

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Turning the fog off makes the shadows look like reflections. Tested with Raze 3d renderer on Vulkan, didn't test with other renderers
https://imgur.com/a/kKLMKCT
This doesn't happen with Duke Nukem 3D, but happens with Blood too

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open Shadow Warrior or Blood
2. Turn off fog
3. See the enemies shadows

### Your configuration

```ini
https://mega.nz/file/LYtFWQCb#M_T1bO_wFctZetnjjVMZbWcvUShhRYiAHNiStsVQ1_8
```

**Comment by coelckers** [comment]
Works correctly in current master.
