### ISSUE TITLE
[BUG] Shadow Warrior shadows not working properly

### ISSUE THREAD

**Issue by Swordman14** [ZDoom/Raze#661]
### Raze version

raze-x64-1.5pre-54-g0d54237ee

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU: i3 9100f GPU: Radeon rx 550 4gb ram: 12 gb

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The shadows in Shadow Warrior aren't behind the enemy, but rather blocking their feet. This is using the raze 3d renderer on Vulkan. Didn't test on other renderers
How it looks: https://imgur.com/a/GWCrwkm
How it should look (Taken from Dosbox): https://imgur.com/a/JZRwbD7

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play Shadow Warrior
2. Look at the shadows

### Your configuration

```ini
https://mega.nz/file/DE0EnCQQ#GVH3sk18mVMPw-zqDbQEuf1irVnP5kf_BFQmCQgxFvQ
```

**Comment by coelckers** [comment]
Works correctly in current master.
