### ISSUE TITLE
[BUG] Graphical glitches with Polymost on Vulkan

### ISSUE THREAD

**Issue by Swordman14** [ZDoom/Raze#662]
### Raze version

raze-x64-1.5pre-54-g0d54237ee

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU: Intel i3 9100f GPU: Radeon Rx 550 Ram: 12 gb

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When selecting the renderer Polymost while using Vulkan, there are a lot of graphical glitches:
https://imgur.com/a/6cIh8gE
It also happens with Duke3d and Blood

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open Duke3d, Shadow Warrior or Blood
2. Activate Vulkan and Polymost (And reste the game if needed)

### Your configuration

```ini
https://mega.nz/file/DE0EnCQQ#GVH3sk18mVMPw-zqDbQEuf1irVnP5kf_BFQmCQgxFvQ
```

**Comment by coelckers** [comment]
What graphics card do you have?

**Comment by Swordman14** [comment]
An AMD Radeon RX 550 4 gb

**Comment by madame-rachelle** [comment]
The last time I solved this problem it was due to a buffer/texture format mismatch.

**Comment by sinisterseed** [comment]
With the recent removal of the Polymost render recently, I don't think keeping the report open serves any further use.
