### ISSUE TITLE
[BUG] Twin Dragon, level 5, first secret not triggering when close to wall

### ISSUE THREAD

**Issue by Froyd1** [ZDoom/Raze#667]
### Raze version

Raze 1.4.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 8

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the beginning of level 5, the wall is supposed to explode when you get really close to it, to reveal the first secret by the train tracks, but it doesn't. Is there any way to fix this bug?
![ShadowWarrior_0003](https://user-images.githubusercontent.com/80136749/158731011-5d3ea587-f430-4220-9c1d-6ef96e024437.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
fixed in f1bdee015d84c14e2b4c086c1c8b66b44dccefac

This proved to be quite elusive
