### ISSUE TITLE
[BUG] Shadow Warrior, Flash bomb does not appear to effect NPCs. 

### ISSUE THREAD

**Issue by Jamie-WD** [ZDoom/Raze#668]
### Raze version

Raze 1.4.1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Relevant hardware info

Lenovo ThinkPad  T495, AMD Ryzen 5 Pro 3500U, Radeon Vega Mobile, 24GB RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Flash Bomb inventory item does not seem to have any discernable effect on NPCs. In other versions of Shadow Warrior, the Flash Bomb will cause enemy NPCs to stop attacking and instead run around in a panicked state. When I play Shadow Warrior Classic Redux, the Flash Bombs have the correct effect. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Position player character near NPCs. 
2. Press the hotkey for Flash Bomb or select it in the inventory and press the use inventory key. 
3. Observe the behavior of NPCs. 

### Your configuration

```ini
[ShadowWarrior.AutoExec]
Path=$PROGDIR/autoexec.cfg

[ShadowWarrior.Player]
cl_autoaim=2
cl_weaponswitch=1
combatmacro0=Burn baby burn...
combatmacro1=You make another stupid move.
combatmacro2=Blocking with your head again?
combatmacro3=You not fight well with hands!
combatmacro4=You so stupid!
combatmacro5=Quit jerking off. Come fight me!
combatmacro6=What the matter you scaredy cat?
combatmacro7=Did I break your concentration?
combatmacro8=Hope you were paying attention.
combatmacro9=ITTAIIIUUU!!!
playercolor=0
playergender=0
playername=Player
rtsname=

[ShadowWarrior.ConsoleVariables]
adl_bank=160574336
adl_custom_bank=
adl_use_custom_bank=true
adult_lockout=false
am_followplayer=true
am_linealpha=1
am_linethickness=1
am_nameontop=false
am_onesidedcolor=aa aa aa
am_ovonesidedcolor=aa aa aa
am_ovplayercolor=aa aa aa
am_ovtwosidedcolor=aa aa aa
am_playercolor=aa aa aa
am_rotate=true
am_showlabel=false
am_textfont=false
am_twosidedcolor=aa aa aa
chat_substitution=false
cl_automsg=false
cl_autorun=true
cl_autosave=true
cl_autosavedeletion=true
cl_bloodoldweapbalance=false
cl_bloodqavinterp=true
cl_bloodvanillabobbing=true
cl_bloodvanillaenemies=false
cl_bloodvanillaexplosions=false
cl_bloodvanillarun=true
cl_bloodweapinterp=false
cl_crosshair=true
cl_idplayers=true
cl_maxautosaves=8
cl_nomeleeblur=false
cl_obituaries=true
cl_resumesavegame=true
cl_runmode=false
cl_showmagamt=false
cl_sointerpolation=true
cl_swsmoothsway=true
cl_viewhbob=true
cl_viewvbob=true
classic_scaling_factor=1
classic_scaling_pixelaspect=1.2000000476837158
con_alpha=0.75
con_centernotify=false
con_notablist=false
con_notify_advanced=false
con_notifyscale=1
con_notifytime=3
con_pulsetext=false
con_scale=0
crosshair=0
crosshaircolor=ff 00 00
crosshairgrow=false
crosshairhealth=2
crosshairscale=0.5
gl_aalines=false
gl_bloom=false
gl_bloom_amount=1.399999976158142
gl_exposure_base=0.3499999940395355
gl_exposure_min=0.3499999940395355
gl_exposure_scale=1.2999999523162842
gl_exposure_speed=0.05000000074505806
gl_fogmode=2
gl_menu_blur=-1
gl_paltonemap_powtable=2
gl_paltonemap_reverselookup=true
gl_precache=false
gl_scale_viewport=true
gl_tonemap=0
hud_bgstretch=false
hud_ctf_vanilla=false
hud_flashing=1
hud_messages=true
hud_position=false
hud_powerupduration=true
hud_scalefactor=1
hud_size=8
hud_statscale=0.6000000238418579
hud_textfont=false
hw_lightmode=0
hw_weaponlight=8
m_quickexit=false
menu_sounds=true
msg=0
msg0color=11
msg1color=5
msg2color=2
msg3color=3
msg4color=3
msgmidcolor=11
msgmidcolor2=4
mus_redbook=true
mus_restartonload=false
nocheats=false
opn_custom_bank=
opn_use_custom_bank=false
r_drawfuzz=1
r_voxels=true
safe_spritelist=false
screenshot_dir=
screenshotname=
snd_menuvolume=0.6000000238418579
snd_pitched=false
snd_speech=1
transsouls=0.75
ui_screenborder_classic_scaling=true
uiscale=0
usermapfolder=
vid_allowtrueultrawide=1

[ShadowWarrior.VideoSettings]

[ShadowWarrior.UnknownConsoleVariables]

[ShadowWarrior.ConsoleAliases]

[ShadowWarrior.Bindings]
1=slot 1
2=slot 2
3=slot 3
4=slot 4
5=slot 5
6=slot 6
7=slot 7
8=slot 8
9=slot 9
0=slot 10
-=sizedown
Equals=sizeup
Backspace=turnaround
Tab=togglemap
W=+Move_Forward
E=+Open
T=messagemode
Y=show_weapon
I=toggle cl_crosshair
LeftBracket=invprev
RightBracket=invnext
Enter=invuse
Ctrl=+Crouch
A=+Strafe_Left
S=+Move_Backward
D=+Strafe_Right
F=useitem 6
G=useitem 5
J=fly
K=coop_view
'=weapnext
`=toggleconsole
Shift=+Run
C=useitem 7
B=useitem 3
N=useitem 4
M=useitem 1
/=+Jump
RShift=+Run
Alt=+Strafe
Space=+Jump
CapsLock=toggle cl_autorun
F1=openhelpmenu
F2=opensavemenu
F3=openloadmenu
F4=openmenu SoundOptions
F5=openmenu OptionsMenu
F6=quicksave
F7=third_person_view
F8=togglemessages
F9=quickload
F10=menu_endgame
Scroll=HolsterWeapon
KP7=+Aim_Up
KP8=+Move_Forward
KP9=+Look_Up
KP-=sizedown
KP4=+Turn_Left
KP5=centerview
KP6=+Turn_Right
KP+=sizeup
KP1=+Aim_Down
KP2=+Move_Backward
KP3=+Look_Down
KP0=+Look_Left
F11=bumpgamma
F12=screenshot
KP-Enter=invuse
RCtrl=+Fire
RAlt=+Strafe
Pause=pause
Home=+Aim_Up
PgUp=+Look_Up
LeftArrow=+Turn_Left
RightArrow=+Turn_Right
End=+Aim_Down
PgDn=+Look_Down
Ins=+Look_Left
Del=+Look_Right
Mouse1=+Fire
Mouse2=weapalt
MWheelUp=weapprev
MWheelDown=weapnext
DPadUp=togglemap
DPadDown=invuse
DPadLeft=invprev
DPadRight=invnext
Pad_Start=pause
Pad_Back=menu_main
LThumb=crouch
LShoulder=weapprev
RShoulder=weapnext
LTrigger=+altattack
RTrigger=+attack
Pad_A=+open
Pad_Y=+jump

[ShadowWarrior.DoubleBindings]

[ShadowWarrior.AutomapBindings]
-=+Shrink_Screen
Equals=+Enlarge_Screen
W=+am_panup
R=togglerotate
A=+am_panleft
S=+am_pandown
D=+am_panright
F=togglefollow
KP8=+am_panup
KP-=+Shrink_Screen
KP4=+am_panleft
KP6=+am_panright
KP+=+Enlarge_Screen
KP2=+am_pandown
MWheelUp=am_zoom 1.2
MWheelDown=am_zoom -1.2
```

### Provide a Log

Log started: 2022-03-22 16:25:55
OS: Windows 11 (or higher) (NT 10.0) Build 22000
    
 adding C:/Users/jamie/Games/Build Engine/raze_1.4.1/raze.pk3, 2713 lumps
 adding C:/Program Files (x86)/Steam/steamapps/common/Shadow Warrior Classic/gameroot/SW.GRP, 693 lumps
 adding C:/Program Files (x86)/Steam/steamapps/common/Shadow Warrior Classic/gameroot/, 958 lumps
CPU speed: 2096 MHz
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx
  Family 23 (23), Model 24, Stepping 1
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
Loading "engine/widescreen.def"

I_InitSound: Initializing OpenAL
  Opened device OpenAL Soft on Speakers (Realtek(R) Audio)
  EFX enabled
No GENMIDI lump found. OPL playback not available.
script parsing took 55.80 ms
SHADOW WARRIOR(tm) Version 1.2
Copyright (c) 1997 3D Realms Entertainment
I_InitInput
I_StartupMouse
I_StartupKeyboard
I_StartupXInput
I_StartupRawPS2
I_StartupDirectInputJoystick
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon(TM) Vega 8 Graphics
GL_VERSION: 4.6.13596 Core Profile Context 20.10.12.09 27.20.11012.9001 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60
GL_EXTENSIONS: GL_AMDX_debug_output GL_AMD_blend_minmax_factor GL_AMD_conservative_depth GL_AMD_debug_output GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_sample_positions GL_AMD_gcn_shader GL_AMD_gpu_shader_half_float GL_AMD_gpu_shader_half_float_fetch GL_AMD_gpu_shader_int16 GL_AMD_gpu_shader_int64 GL_AMD_interleaved_elements GL_AMD_multi_draw_indirect GL_AMD_name_gen_delete GL_AMD_occlusion_query_event GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_sample_positions GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_atomic_counter_ops GL_AMD_shader_stencil_export GL_AMD_shader_stencil_value_export GL_AMD_shader_trace GL_AMD_shader_trinary_minmax GL_AMD_sparse_texture GL_AMD_sparse_texture_pool GL_AMD_stencil_operation_extended GL_AMD_texture_cube_map_array GL_AMD_texture_texture4 GL_AMD_transform_feedback3_lines_triangles GL_AMD_transform_feedback4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_snorm GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_envmap_bumpmap GL_ATI_fragment_shader GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_buffer GL_EXT_copy_texture GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_histogram GL_EXT_memory_object GL_EXT_memory_object_win32 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_semaphore GL_EXT_semaphore_win32 GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texgen_reflection GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_bptc GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_texture_mirrored_repeat GL_INTEL_fragment_shader_ordering GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_explicit_multisample GL_NV_float_buffer GL_NV_half_float GL_NV_primitive_restart GL_NV_shader_atomic_int64 GL_NV_texgen_reflection GL_NV_texture_barrier GL_OES_EGL_image GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint WGL_EXT_swap_control
Max. texture size: 16384
Max. texture units: 32
Max. varying: 128
Max. combined shader storage blocks: 64
Max. vertex shader storage blocks: 64
Resolution: 1920 x 1080
player 1 of 1 (1 nodes)
$bullet: Seppuku Station
Shurikens
Nuclear Warhead
You found a secret area!
Shurikens
Shurikens
UZI Clip
MedKit +20
MedKit +20
UZI Clip
UZI Clip
Shurikens
Gas Bomb
Shurikens
UZI Submachine Gun
UZI Clip
UZI Clip
Flash Bomb
Shurikens
Shurikens
Press 'Use' to continue
$bullet: Seppuku Station
Shurikens
Shurikens
Nuclear Warhead
You found a secret area!
Shurikens
Shurikens
UZI Clip
MedKit +20
UZI Submachine Gun
Shotshells
UZI Clip
Gas Bomb
UZI Clip
UZI Clip
MedKit +20
MedKit +20
Flash Bomb
Got the GOLD master key!
You found a secret area!
Sticky Bombs
Grenade Launcher
MedKit +20

**Comment by coelckers** [comment]
fixed in f307e22f4b0184adb82b8adc778428d6215b185b
