### ISSUE TITLE
[BUG] [Powerslave/Exhumed] Excessively long jumps

### ISSUE THREAD

**Issue by orderorder** [ZDoom/Raze#670]
### Raze version

Raze 1.5pre-115-g16c81f0b1-m

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 7 - RTX3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

in various levels we can access certain areas that should be inaccessible through the jump. For example at the beginning of level 8 we find a column that goes up and down that allows us to see the totem that allows us to finish the level. If we try to jump, in some of those attempts we can reach it without having a single key.

### Steps to reproduce the behaviour.

I have to rename my savegame save000.dsave to save000.dsave.zip to attach it.

In this savegame I find myself next to the totem without having a single key in my possession. A short distance in front of the totem is the column that goes up and down

[save0000.dsave.zip](https://github.com/coelckers/Raze/files/8392776/save0000.dsave.zip)

**Comment by mjr4077au** [comment]
Apologies that no one has got back to you for so long on this. I've tested this spot in PCExhumed and its very easy to strafe jump across this ledge. Just bad mapping, sorry.
