### ISSUE TITLE
[BUG] Major Bug - Blood - Dynamite Alt fire doesn't work properly

### ISSUE THREAD

**Issue by Axer128** [ZDoom/Raze#671]
### Raze version

1.4.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Relevant hardware info

I7-8700K , RTX 2060 Super 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In dos blood / most other source ports the dynamite alt fire is very useful as it allows you to kill enemies around corners.. EG: normal fire, it explodes on impact. Alt fire - with special set up, it does not.

Default alt fire is working normal, if you just press and release. That just drops dynamit at your feet, explodes a while later, rarely useful.

The trick is you hold right click (altfire) - keep it pressed down than hold left click to power up the throw, same as normal fire. The power meter should appear in the hud now, release when charged to your preference.
Difference: It does not explode on impact, so you can bounce it off walls around corners.

In Raze: I couldn't figure out any way to charge the throw power.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Hold RClick (alt fire), Than hold LClick - primary fire
2. Charge bar should display (does not)
3. Even if UI not implemented, it should toss further with a long hold and release of both, does not.

### Your configuration

```ini
defaults, just installed and tested latest build today
```

**Comment by valter12437** [comment]
You don't need to hold both buttons down as you described. Just press alt-fire **once**, let go of alt-fire, and then hold primary-fire to charge your throw. That's the same behavior as vanilla.

**Comment by Axer128** [comment]
Oh okay aye i tested in nblood and yea it's like that too. I guess the ability to hold down both at once is exclusive to fresh supply.

Personally like holding it down, feels more intuitive, so guess it's not a bug but could be a feature request.
