### ISSUE TITLE
[BUG] [Powerslave/Exhumed] Switch Bug

### ISSUE THREAD

**Issue by orderorder** [ZDoom/Raze#674]
### Raze version

Raze 1.5pre-115-g16c81f0b1-m

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro Linux 86_64 / Windows 10

### Relevant hardware info

AMD A10-7850K Radeon R7 / RTX 3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Pressing a switch which lowers a platform. This switch goes down when it should be stationary on the wall

### Steps to reproduce the behaviour.

![Switch_Bug webm](https://user-images.githubusercontent.com/7293829/163040562-de40da28-268a-46da-ad4e-e8b90df31b02.gif)

Savegame

[save0021.dsave.zip](https://github.com/coelckers/Raze/files/8476301/save0021.dsave.zip)

**Comment by coelckers** [comment]
This looks like a mapping bug. With some of these games moving sprites along with a sector can be a tricky thing.
What do the other ports do here?

**Comment by mjr4077au** [comment]
@orderorder thank you for the bug report on this one. We were just wondering whether this issue occurs in other ports, like PCExhumed or ExhumedGDX? There's been a tonne of refactoring over the last ~9 months so just wondering whether it's something accidentally introduced.

**Comment by coelckers** [comment]
Whatever GDX does (can't check because its cheat system is so bad), this is definitely the result of some code that is designed to move sprites along with an elevator.

**Comment by orderorder** [comment]
Forgive the tardiness. I have tested the level with the executable of the NBlood project (pcexhumed). The button goes down as it happens with Raze but at the moment it disappears so it is not floating in the air. When I have time I will try BuildGDX

**Comment by coelckers** [comment]
The non-disappearing button may just mean a bugfix on our side affecting the setup here.
