### ISSUE TITLE
[Feature] AppImage Package Builder

### ISSUE THREAD

**Issue by fang64** [ZDoom/Raze#678]
### Raze version

1.4.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Ubuntu 22.04 LTS

### Is your feature request related to a problem? Please describe.

It would be great to have a AppImage Package auto-built on release, maybe on commit. 

### Describe the solution you'd like

I'd like to add a workflow to build one automatically, so releases can happen, as it seems you already have build logic in Github Actions already. I want to provide a pull request once I get the github action to build the AppImage assuming you guys can validate it.

**Comment by mjr4077au** [comment]
@fang64 thank you for the time you've spent on this so far! How are things looking from your end?

**Comment by madame-rachelle** [comment]
Here is some relevant info from `readelf -d` for Raze 1.5.0:

```
Dynamic section at offset 0xcea938 contains 39 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libvpx.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libzmusiclite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
```

I've cut out the less relevant info.

**Comment by fang64** [comment]
@mjr4077au I have gotten it to build locally with docker doing the appimage. I wanted to make sure that it works well enough. I did the readelf trick after figuring out the rpath is fixed. I think I'll just move the libraries after it's built and just setup the AppImage structure manually. I didn't really want to modify the build that drastically, probably just script this in github actions instead.

**Comment by madame-rachelle** [comment]
I would love to start distributing both GZDoom and Raze as AppImages. So I am eager to see how this works out.

(Though I haven't the foggiest clue how to use Docker)

**Comment by fang64** [comment]
@madame-rachelle if you want to give this a look to potentially use for building AppImages for Raze, I originally intended to use (AppImageCrafters/appimage-builder)[https://github.com/AppImageCrafters/appimage-builder] but apparently it's somehow broken, opted to just pull the builder tool straight into the environment instead of using a separate container. I don't think it affects much but the AppImage comes out to be 19.9Mb~ 

@mjr4077au hopefully this is good enough.

**Comment by madame-rachelle** [comment]
Oh, seems sometime back this was completed and I merged it. Well done. 👍

**Comment by madame-rachelle** [comment]
> @madame-rachelle if you want to give this a look to potentially use for building AppImages for Raze, I originally intended to use (AppImageCrafters/appimage-builder)[https://github.com/AppImageCrafters/appimage-builder] but apparently it's somehow broken, opted to just pull the builder tool straight into the environment instead of using a separate container. I don't think it affects much but the AppImage comes out to be 19.9Mb~

I wouldn't worry too much with this. CI builders are just docker images anyway. I have a friend who uses a similar system with Jenkins and she has to use Docker to compile the builds.
