### ISSUE TITLE
[BUG] [Duke Vacation] Voodoo ring (expander) doesn't do damage

### ISSUE THREAD

**Issue by Dremor8484** [ZDoom/Raze#682]
### Raze version

1.4.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[BUG] [duke] vodoo ring (expander) in vacation dlc doesn't do damage

am i the only one with the expander weapon not working in raze using vacation dlc ?

i just put the files in a folder, dlc is recognized by raze, and it loads successfully... still the weapon doesn't work

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
From the looks of it, that mod's CON script does not implement the weapon, none of the enemies handles it. So even if you cheat yourself the ammo, it won't have an effect.

**Comment by Dremor8484** [comment]
> From the looks of it, that mod's CON script does not implement the weapon, none of the enemies handles it. So even if you cheat yourself the ammo, it won't have an effect.

thanks for the answer
