### ISSUE TITLE
[BUG] [SW WD] Geometry lines in sky

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/Raze#686]
Raze 1.4.1. Win10-64. WT.GRP (file only) from Steam Classic Redux. 

Screenshot & save attached, the cross-hair is pointing at the problem.

[Sky.zip](https://github.com/coelckers/Raze/files/8972854/Sky.zip)

**Comment by coelckers** [comment]
There's not much I can do about it. It's just bad level design that doesn't coexist well with SSAO.
