### ISSUE TITLE
Duke Nukem switches sometimes play infinite sound

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/Raze#697]
Win10-64, Raze, 1.5.0, Duke Nukem Megaton from Steam.

Use the switch in front of you. Once the wall finishes rotating, its rotation sound plays forever.

If you use it again, once the wall rotates back to rest position, the sound stops.

[Infinite Sound.zip](https://github.com/ZDoom/Raze/files/9188521/Infinite.Sound.zip)

**Comment by coelckers** [comment]
What switch? Are you sure this is the right savegame?

**Comment by Q3BFG10K** [comment]
It's right under the crosshair. Just press 'Use' to activate it.

I just downloaded the file now to test it.

**Comment by coelckers** [comment]
addressed in 9627f00f32040cfd29a2ca9929e052398b301167

It looks like this special case was rejected in the original sound code due to a bug, not by intent. but the game relied on it. So I had to add a special case for this check.
