### ISSUE TITLE
[BUG] No music in duke3d on linux version

### ISSUE THREAD

**Issue by bullbob1** [ZDoom/Raze#698]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86

### Please describe your specific OS version

Whatever is installed on a steam deck

### Relevant hardware info

Steam Deck

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I run the linux version of Raze on my steam deck, duke 3d does not have any music. Shadow warrior does not have this problem. I'm not sure why, or if I need to point the config to some other data directory. I pointed it where .grp file was 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Point to gameroot folder directory in the ini file after installing duke megaton edition on steam
2. Run duke 3d or any addon

**Comment by coelckers** [comment]
Have you made sure that all dependencies are installed? SW uses CD music, meaning Ogg files.
Duke uses MIDI which has different dependencies. Also, is there an error message in the console?

**Comment by bullbob1** [comment]
On steam deck raze by default knows nothing about where steam installs
games, so I had to manually add the .grp locations to the ini for the main
game and addons. I assume that's the issue with the music too, but I tried
adding the path to the music files to the same 3 path sections. Unless I
need to define that path somewhere else. Or do I need to select midi
instead of fluidsynth? Also, is there a way to specify to the path to
recursively check all subfolders? I just specifically listed each one for
each addon and base game. Thanks

**Comment by bullbob1** [comment]
Also the error in the log Says

Could not load libfluidsynth.so.1 or libfluidsynty.so.2 or
libfluidsynth.so.3

Unable to create FluidSynth MIDI device. Falling back to system default

**Comment by bullbob1** [comment]
Ah, I found something that works. If I enable ignore file type for music
lookup and sound lookup the music plays

**Comment by coelckers** [comment]
The FluidSynth error comes from not having installed all required dependencies.
Without a MIDI synth available it simply cannot play them.

**Comment by tylerfox3894** [comment]
i attempted to ignore file type and it did not work
