### ISSUE TITLE
[BUG] 1.5.0 Duke Nukem Map 03 is broken on that version

### ISSUE THREAD

**Issue by Tasosgemah** [ZDoom/Raze#699]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 pro

### Relevant hardware info

i5 4670, 16 GB RAM, GTX 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In map 03, the last gate before the submarine is broken. 

From one side it's a black void that sends you elsewhere in the map. From the other side there are walls and textures missing

Save file:
[save0002.zip](https://github.com/ZDoom/Raze/files/9208676/save0002.zip)

### Steps to reproduce the behaviour.

Load the save file, get out of the sub, go back to the gate.

**Comment by De-Seppe** [comment]
I was able to reproduce this error with the provided savegame, but not when I warped to the level using map E1L3.
I got following warnings in the console when I loaded the provided savegame.
"Potential problem at sector 378 with 2 loops
Potential problem at sector 440 with 3 loop"

These warnings do not occur when warping to the level.

**Comment by coelckers** [comment]
The savegame is already broken - some doors got moved to bad places far outside,the map. Without any means to reproduce the action that messed up the map I'm afraid I cannot do anything here. Maybe it even got fixed by now - the savegame is from 1.4.0.
