### ISSUE TITLE
[BUG] Sky dome cap loses colour after portal transition

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#700]
FIrst started occurring after e86899ed31c4df5aceed12f159ed8cb0f5604592. Easiest observed in Duke 3D. Start a new game, observe the sky dome cap is grey-ish. Go down the ventilation shaft and then observe the dome has turned completely black.

![image](https://user-images.githubusercontent.com/48643140/182720247-6bdaaa2e-7d36-4d03-9a3d-68aa543288fd.png)

**Comment by coelckers** [comment]
fixed in 4260d334e2dcbda536a19994158e0037570a855e
