### ISSUE TITLE
[BUG] [SW] Assert failure upon opening gold key door on $bullet

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#701]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04

### Relevant hardware info

Intel Core i5-4690K CPU, NVIDIA GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game asserts whenever I try to open this door on $bullet (Seppuku Station):

![ShadowWarrior_0018](https://user-images.githubusercontent.com/6550500/183233308-8e56c86c-8c1f-415e-9bb4-bfadab102e66.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on the Enter The Wang episode
2. Get the gold key and unlock the door shown in the screenshot
3. Try to open the door
4. Assert (see below)

### Provide a Log

```raze: ../source/common/utility/tarray.h:307: T& TArray<T, TT>::operator[](size_t) const [with T = sectortype; TT = sectortype; size_t = long unsigned int]: Assertion `index <= Count' failed.```

**Comment by coelckers** [comment]
fixed in fddb4d23301be2fec2fbdd6a5c4fcaece675cc05
