### ISSUE TITLE
[BUG] Blood elevator bug

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#703]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 20.3

### Relevant hardware info

Intel CPU, AMD GPU

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When going up or down an elevator in Blood, the player's position seems to lag behind that of the elevator. When going down a sufficiently fast elevator, the player bounces; when going up an elevator, the camera is pushed down towards the floor. This does not happen with Raze 1.4.1.

I don't know whether Blood is the only game affected, but the bug does *not* occur in the arcade elevator found in the first map of Duke Nukem 3D.

### Steps to reproduce the behaviour.

1. Start Raze 1.5.0 on Linux and select *BLOOD: One Unit Whole Blood*.
2. Get to an elevator. (I don't remember where all of them are, but there's one reasonably close to the start of *Monster Bait*. Open the console and use `map e3m6`, optionally use `god` to enable immortality unless you want reproducing this bug to be a challenge, and continue just past the part with the bridge next to the waterfall. Behind the next door there's an elevator going down.)
3. Ride the elevator.

### Your configuration

I moved my `raze.ini` and let Raze create a new one with all default values; the bug still occurred.

**Comment by coelckers** [comment]
fixed in 72575d8b0aff5cfafc4437dfbc9230bf239b9e6c
