### ISSUE TITLE
[BUG] Cannot open this door

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#704]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04

### Relevant hardware info

Intel Core i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

A door on Redneck Rampage E2L7 (Beaudry Mansion) cannot be open, despite having the key to open it. The door just plays the opening sound, but does not actually move.

[Here's a saved game](https://github.com/ZDoom/Raze/files/9418549/save0004.zip) (Raze 1.5.0, Redneck.Redneck).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Raze 1.5.0 with Redneck Rampage and the saved game
2. Try to open the door in front of you
3. Door does not open

**Comment by coelckers** [comment]
It is actually a map bug. The door has no size descriptor so the movement distance is left at 0.
added a hack in c4f67aefb263b75021b30803735b10de82cff560
