### ISSUE TITLE
[BUG] Blood rain

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#705]
### Raze version

Git master f58f6119dbae9c4777a221e53b5bf5197673e9c6

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04

### Relevant hardware info

Intel Core i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Blood droplets do not disappear when they hits the floor. Instead, it plays the floor impact animation over and over, making it look like "blood rain"

[Here's a saved game showing the issue](https://github.com/ZDoom/Raze/files/9418575/save0008.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Watch the blood droplets repeatedly hitting the floor

**Comment by Talon1024** [comment]
This seems to be one of the issues caused by the "floatification".

**Comment by coelckers** [comment]
fixed in work branch
