### ISSUE TITLE
[BUG] Cannot leave water

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#706]
### Raze version

Git master f58f6119dbae9c4777a221e53b5bf5197673e9c6

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04

### Relevant hardware info

Intel Core i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The player will be unable to leave the water once they have entered it.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load any map that has water
2. Enter the water
3. Try to leave the water

**Comment by coelckers** [comment]
fixed in work branch.
