### ISSUE TITLE
[BUG] Assert failure on $shrine after finding third secret area

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#709]
### Raze version

Git master fa53fcd08

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04

### Relevant hardware info

Intel i5-4690K CPU, Nvidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to load a saved game which was saved after finding the third secret area and leaving the water in $shrine¹ causes an assertion failure (see log below).

1. It's the underwater area where you can find a button that will open a cavity in which you will find a nuclear warhead

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load this saved game (It's called "please be good") [save0000.zip](https://github.com/ZDoom/Raze/files/9471888/save0000.zip)
2. Go underwater to the area with the bronze key gate
3. Enter the aforementioned underwater secret area
4. Leave the water
5. Save your game
6. Reload that saved game
7. Assert failure

### Provide a Log

    raze: ../source/core/actorlist.cpp:257: void AddSectHead(DCoreActor*, sectortype*): Assertion `head == nullptr || head->prevSect == nullptr' failed.

**Comment by coelckers** [comment]
fixed in d1b4bef98d2a2bc45cc3f8594cd4dace86fb1180

We already had this but it was in the wrong branch
