### ISSUE TITLE
[Shadow Warrrior] 5.1/7.1 surround: Player's weapon fire plays from side/rear channels when walking

### ISSUE THREAD

**Issue by mrmatteastwood** [ZDoom/Raze#710]
### Raze version

1.5.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21

### Relevant hardware info

Full specs of my PC: https://termbin.com/cr0m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When playing the game in 7.1 surround sound, the player's rapid weapon fire (e.g. from an uzi) plays from the side or rear channels, not the fronts while the player is in motion. It seems like the sound is stuck to the point on the map where the player is while the sound is emitted, not attached to the player. Other games than Shadow Warrior might be affected, I haven't yet played them far enough to get rapid-fire guns.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Hook up a Linux Mint PC to a 5.1/7.1 system by plugging an HDMI cable into the graphics card and surround receiver
2. In Mint's sound config, set output profile to "Digital Surround 7.1" or 5.1
3. Start game (the 18-level full episode)
4. Get rapid-fire gun
5. Shoot while walking or being on the boat at the beginning

### Your configuration

https://gist.github.com/mrmatteastwood/1a66d46cfdf7376afcccf995721a8655

**Comment by mrmatteastwood** [comment]
Blood (tried machine gun, slot 4) is not affected.

**Comment by mrmatteastwood** [comment]
For what it's worth, the bug also occurs with the hi-res sound effects pack by @Dzierzan mentioned here: https://github.com/ZDoom/Raze/issues/715#issuecomment-1257232774

**Comment by mrmatteastwood** [comment]
Duke Nukem 3D (tried devastator, pistol and chaingun (slot 4)) not affected.

**Comment by coelckers** [comment]
Which means the problem is on the game side. SW's original sound code was pretty bad with sound positioning. Most importantly, the game plays lots of sounds without any positioning at all. This may have to be changed.

**Comment by mrmatteastwood** [comment]
Doesn't sound like an easy fix then, right? That's too bad. If you find the time to look into it, I think it would bring a marked improvement for those of us who play in surround, but I'd understand if you decided you have bigger fish to fry.

**Comment by coelckers** [comment]
I'll have to check. From the looks of it the flag is used on virtually all sounds in the game, rendering 3D effects nearly ineffective.
From a quick look more than 90% of them are bogus.

**Comment by coelckers** [comment]
Please check out e2a1190e321f4e4f7de89ab607bbbbc245349bed
After looking at how these flags get used I had to come to the conclusion that it is too inconsistent to be useful. So now everything except ambient sound effects are both following their originator and are set to be properly panned.

**Comment by mrmatteastwood** [comment]
Hey @coelckers thanks so much for looking into this so quickly. I looked at the build instructions for Zdoom for Linux here: https://zdoom.org/wiki/Compile_GZDoom_on_Linux and they go way over my head. This looks much too complicated for me, unfortunately.

Are you planning to publish a new release anytime soon? Alternately, would you be willing to provide a dev build for Linux?

**Comment by mrmatteastwood** [comment]
I'm afraid this bug still occurs in version 1.6.0. Steps to Reproduce:

1. Hook up a Linux Mint PC to a 5.1/7.1 system by plugging an HDMI cable into the graphics card and surround receiver
2. In Mint's sound config, set output profile to "Digital Surround 7.1" or 5.1
3. Start episode "Code of Honor"
4. Get rapid-fire gun on the boat
5. Shoot

The gunshots still play from the rear channels.

I see there have been a couple 100 commits since version 1.6.0, is it possible this fix simply isn't in yet? Is 1.7.0 planned soon?

**Comment by mrmatteastwood** [comment]
Works perfectly on new version 1.7! Awesome stuff, thanks :-)
