### ISSUE TITLE
[BUG] Redneck Rampage savegame music bug

### ISSUE THREAD

**Issue by Panzermann11** [ZDoom/Raze#711]
### Raze version

1.5.0

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Windows 7

### Please describe your specific OS version

Windows 7 Ultimate

### Relevant hardware info

Intel Pentium G2130, NVIDIA GeForce GT 630

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed when you launch Raze with Redneck Rampage and load a savegame, the music that played on the game you saved will play. After it's done, instead of advancing to the next song, it goes back to the first track.

For example, when you save a game with Baby's Liquored Up playing in the background in the first game, then quit and load the save, the game will play said song before going back to UFOs, Big Rigs, and BBQ. Or Disgraceland then Redneck Rampage, in Rides Again's case.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game.
2. Wait for the first music track to finish.
3. Save the game.
4. Quit the game.
5. Launch the game again, 
6. Load the game you just saved.
7. Wait for the currently playing music track to finish.

**Comment by coelckers** [comment]
fixed in 64a96e1b946ca4f5d4e93f964bda331782a6ea34

The player track state is now saved so that the game will resume the music loop at the place where it was saved.
