### ISSUE TITLE
[Feature] Redneck Rampage: Disable saving and loading in Psychobilly

### ISSUE THREAD

**Issue by Panzermann11** [ZDoom/Raze#712]
### Raze version

1.5.0

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Windows 7

### Is your feature request related to a problem? Please describe.

In the original Redneck Rampage, the Psychobilly difficulty disables saving and loading. When you try to save or load in the difficulty, a message will come up saying "No savin' or loadin' fer Psyco". Raze lacks this feature for some reason, making the difficulty effectively a pointless duplicate of Killbilly.

**Comment by coelckers** [comment]
Here's the deal:

The main feature of these skills is to disable the cheats. This was accidentally disabled in early engine testing and never reverted.
As it is a user setting you will either have to change it manually or start with a new config.

What I will not do is blocking saving or loading on this skill level as that is just unfair. Forcing the player to go through the entire session uninterrupted is just ludicrous - RR's games take several hours to play and without taking a break that's virtually impossible.
