### ISSUE TITLE
[Feature] Ion Fury compatibility with Raze

### ISSUE THREAD

**Issue by Hydra-Spectre** [ZDoom/Raze#713]
### Raze version

Raze 1.5.0

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Raze is based on, among other source ports, EDuke32, which was the source port Ion Fury was based upon.
Now, EDuke32 can also be used to run Ion Fury with more features than the vanilla engine (which is a locked version of EDuke32), but not Raze.
I really hope Raze can be updated to support Ion Fury, as it is quite a good game, unlike games like TekWar and Extreme Paintbrawl 3D.

**Comment by mjr4077au** [comment]
Our Duke code is not based on EDuke32, rather it's based on JFDuke3D. We initially had EDuke32 as our Duke component but we wished to take Raze in a certain direction and that necessitated going back to something more original.

There's no plans to bring EDuke32 code back in, and attempting to would likely prove unsuccessful given how much of how EDuke32 works depends on its precise setup.

**Comment by sinisterseed** [comment]
Precisely that.

The EDuke32 codebase proved to be far too prone to issues after our goals started shaping up, so the only solution was going back to sources which were closer to what the sources released by 3DR were. As a consequence, this meant the complete loss of the EDuke32-specific extensions along with compatibility with mods incorporating them, as well as all support for Ion Fury, which makes extensive use of them.

Solely for achiving and historical reasons, the old base is still available in the "old_master" branch, but does not compile anymore, certainly not with recent versions of MSVC. For those interested in experiencing Raze running with the old codebase for any given reason, the latest version supporting it is **0.6**. **0.7** marked the first (and major) release with a rebased Duke 3D, paving a new road for us.
