### ISSUE TITLE
[Feature] Blood - Support more audio formats

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#715]
### Raze version

Not relevant 

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Not a long time ago, I released High Quality Sound Packs for Duke Nukem 3D and Shadow Warrior. I'd love to make such pack for Blood as well, but right now Raze Blood doesn't support any other formats than its own (RAW). It would be nice to be able to load external sounds such as ogg, mp3 or wav let's say via DEF script or other one. Working with original format is just a pain in the butt.

As far as I am concerned, Raze Blood can load 44kHz quality sounds using original audio format, but personally, I was never able to load them properly, without hearing ear-rape sounds. I highly suspect it doesn't work properly.

![image](https://user-images.githubusercontent.com/17529329/191502883-80f1e8ae-dba5-4a97-b807-190a14a52669.png)
![image](https://user-images.githubusercontent.com/17529329/191502925-14b5c617-54d9-4330-850b-a59a4d4b8a1c.png)

Link to the conversation (ZDoom Discord Server):
https://discord.com/channels/268086704961748992/674163641934807050/949944480763617341

I managed to find a lot of source sounds used in Blood and I am sure some folks would like to experience this game with high quality sounds.

Of course it's a feature request you can ignore :-).

**Comment by mjr4077au** [comment]
It'd be great to have this, we won't ignore it but it'll probably sit for a few weeks or more while we finish up some major works we're doing in a branch.

Does NBlood support loading of external sounds? I feel we discussed it but I honestly can't remember. I'd hate to do it one way and have NBlood to implement it in another way, just makes it annoying for artists and contributors like yourself. The interpolated QAV stuff for instance was done in very port-friendly way, should NBlood and BloodGDX wish to implement it, it's all DEF-based.

**Comment by mjr4077au** [comment]
This may also not take too much to support, there's already some supporting code to load other formats. Might just need some work: https://github.com/ZDoom/Raze/blob/fdb13ffdfd35a00a4523939cae374ee01aba7887/source/games/blood/src/sound.cpp#L119-L128

**Comment by mrmatteastwood** [comment]
Sorry to hijack this thread, but I searched far and wide and couldn't find an answer... Is it possible to load mods, like hi-res sound packs or texture packs, with Raze? How is this accomplished? Also, @Dzierzan, where would I find your high quality sound packs?

**Comment by Dzierzan** [comment]
Shadow Warrior:

https://www.moddb.com/mods/shadow-warrior-high-quality-sound-effects/addons/high-quality-sound-effects-only-raze

Duke Nukem 3D

https://www.moddb.com/mods/duke-nukem-3d-high-quality-sound-effects

I have got also Powerslave HQ sound pack, but not released yet.

And of course i wanna make Blood one, if Raze supports it nicely.

Just download my packs and see how I did it.

**Comment by mrmatteastwood** [comment]
Thanks! Awesome!

**Comment by coelckers** [comment]
The basic features are in. But due to how Blood initializes its sounds it will be a bit awkward to set up replacements as it is necessary to set all contents of the SFX file manually. The original SFY files cannot be used because they are specific to the actual sound file and won't match any replacement.
