### ISSUE TITLE
[BUG] Blood: In-game music plays on cutscenes

### ISSUE THREAD

**Issue by Panzermann11** [ZDoom/Raze#716]
### Raze version

1.5.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 7

### Please describe your specific OS version

Windows 7 Ultimate

### Relevant hardware info

Intel Pentium G2130, NVIDIA GeForce GT 630

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed the in-game music still plays when playing on a level and then starting on a level with an opening cutscene (e.g. Cradle to Grave [E1M1] and The Hall of Epiphany [E4M8]).

### Steps to reproduce the behaviour.

1. Start any episode.
2. Start the episode "The Way of All Flesh" while in-game.

**Comment by coelckers** [comment]
fixed in f858d77e7c62b626c1126cad25e63c04d4966bcc
