### ISSUE TITLE
[BUG] Duke Nukem 3D hard to toggle menu

### ISSUE THREAD

**Issue by allenz8512** [ZDoom/Raze#717]
### Raze version

1.5.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Professional 21H2

### Relevant hardware info

8700k, 980ti, 32g ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The menu always blink and toggle off and you should try many time to toggle it on

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Press ESC in game

### Your configuration

```ini
nothing special
```

### Provide a Log

nothing special

**Comment by coelckers** [comment]
Works fine for me. How does this handle in the other games or in GZDoom?

**Comment by sinisterseed** [comment]
Same. The blinking part in particular sounds intriguing.

As with all things, make sure your drivers are up to date and see if that changes anything first, the 9xx series is still actively supported. Try switching between Vulkan and OpenGL as well and see if that changes anything as well, your initial report makes no mention as to whether OpenGL, Vulkan, or even GLES is being used.

**Comment by coelckers** [comment]
Since this seems to be a fire-and-forget report I'm closing it now. I'm sorry but without feedback we cannot do much here.
