### ISSUE TITLE
[BUG] Crying girl crying sound doesnt go away when she is destroyed

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#726]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11

### Relevant hardware info

uhhhh idk probably not relevant

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you kill the crying girl in level 3, her sprite disappears but her crying sounds do not. (you can find her grieving over Master Leep's death on the cliffside)

This is likely a bigger problem related to tags not triggering on sprite deletion, etc. If I remember correctly her crying sound is actually an "ambiance sound" sprite tag, and it gets deleted when she dies by another sprite tag that detects when she dies.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Kill the crying girl
2. ???
3. She is still crying somehow despite not existing

### Your configuration

```ini
https://pastebin.com/r2NEu2Yd
```

### Provide a Log

https://pastebin.com/APnibH8x

**Comment by ninjakitty844** [comment]
It might be hardcoded, I'm not sure. But all I know for sure is that in normal SW she stops crying when you kill her. Not just in DOS, but in all the modern Shadow Warrior ports as well.

**Comment by coelckers** [comment]
fixed in 0cef35c34576302000a4278696426b0814e5840e
There was an oversight in the sound code that it did not check the ambients when killing their master sprite.
They just kept playing, referencing undefined memory as their owner.
