### ISSUE TITLE
[BUG] Some CVARs are not default initialising properly on a fresh config.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#731]
When launching the engine on a fresh config, `gl_texture_filter_anisotropic` is using an undefined value. This seems to affect all floating point CVARs.

![image](https://user-images.githubusercontent.com/48643140/197317906-021a8472-dfc9-43fb-920c-2580a161d8dd.png)

![image](https://user-images.githubusercontent.com/48643140/197317934-adf9c6a2-f756-4aa6-972f-cc8e79fdafc0.png)

**Comment by coelckers** [comment]
Should be fixed now with proper type checks in place and everything being adjusted.
