### ISSUE TITLE
[BUG] Loading Duke with ERP, but true colour textures disabled messes up palette of intro

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#732]
https://www.moddb.com/mods/enhanced-resource-pack-for-duke-nukem-3d

![image](https://user-images.githubusercontent.com/48643140/197388059-1b960618-4dd2-4585-82c3-c64f4a957354.png)

**Comment by coelckers** [comment]
Yeah, unfortunately that image with those incorrect colors is what the ERP contains as a placeholder for this tile. 
It needs to be fixed on the mod side because the engine has no way to determine that it got a PNG with incorrect colors.
