### ISSUE TITLE
[BUG] Cannot load penthouse.grp nor load by file path

### ISSUE THREAD

**Issue by StenApp** [ZDoom/Raze#733]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Win 10 Pro

### Relevant hardware info

i7 Gen7, AMD Radeon 560 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If i place penthouse.grp in raze root/data folder, it refuses to list it.
Even if i use a cmd file to load it: raze.exe -file data/penthouse.grp

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Put penthouse.grp into raze root/data folder
2. start raze.exe
3. No Penthouse level shown nor selectebal in menu of duke3d

### Provide a Log

[raze.log](https://github.com/ZDoom/Raze/files/9847079/raze.log)
[raze-Sten.zip](https://github.com/ZDoom/Raze/files/9847084/raze-Sten.zip)

**Comment by StenApp** [comment]
I use the penthouse.grp from the eduke32 addonpack compilation because it has fixes.
I had to create a penthouse.grpinfo file with the following content:

grpinfo
{
    name "Penthouse Paradise"
    scriptname "paradise.con"
    size 3773026
    crc 859417507
    dependency DUKE15_CRC
}

Copied the infos right out of the addons.grpinfo. Now raze sees penthouse paradise addon.

**Comment by StenApp** [comment]
Got lucky too early, now i get Paradise.con errors

**Comment by coelckers** [comment]
The CON from the EDuke32 pack most likely contains additions made specifically for EDuke32 and won't work with other ports.

**Comment by StenApp** [comment]
I heard that there are problems with spawners under water and some level geometry bug, thst‘s why i used the edule32 addon compilation version.
Does the normal, bon edule32 version work?

**Comment by StenApp** [comment]
Is there any documentation which version is supported, or how to load them with raze?

**Comment by StenApp** [comment]
Holy crap!!! Now it works.
This is how i got it to run:

you need these files, size doesn't matter:
```
25.10.2022  09:14           159.868 NEEDLE.WAV
25.10.2022  09:14           157.822 NEEDLE2.WAV
25.12.1996  00:32             5.165 penthous.txt
25.10.2022  09:26         1.960.807 penthouse.grp
25.12.1996  00:32            36.338 ppakdefs.con
25.12.1996  00:32           150.854 ppakgame.con
25.10.2022  09:14           318.662 ppakpent.MAP
25.12.1996  00:32            46.046 ppakuser.con
25.10.2022  09:14            19.251 SBELL1A.VOC
25.10.2022  09:14             8.660 SWEET04A.VOC
25.10.2022  09:14            16.219 SWEET05A.VOC
25.10.2022  09:14            17.557 SWEET16A.VOC
25.10.2022  09:14         2.839.282 TILES014.ART
25.10.2022  09:14            30.572 VACATN01.VOC
25.10.2022  09:14            53.300 WAVE1A.VOC
```
zip them to a file called penthouse.grp

create a text file called penthouse.grpinfo and insert this:

grpinfo
{
name "Penthouse Paradise Level"
scriptname "PPAKGAME.CON"
defname "duke3d.def"
**size** 1960807
dependency DUKE15_CRC
flags GAMEFLAG_ADDON
**CRC** 2528106282
}

drag the penthouse.grp on Eduke32 that it calculates the crc in the log.
eduke32.log is created in the folder where you dragged it to Eduke.
search for the line penthouse.grp and replace crc in the grpinfo.
right click on penthouse.grp file to get its size in bytes in file properties, replace that number within your grpinfo.
