### ISSUE TITLE
[master] RR E1L3 boss pathfinding isn't right

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#735]
This is the behaviour in 1.5.0, which is the same as Rednukem: https://youtu.be/Y-9W8PP3zk0. The boss is supposed to leave the left window, and when he aims at you he makes contact at least.

This is the behaviour in master as of 1cf954920cc5bd9188b4f0e7e564272e8398dd84: https://youtu.be/98-1JworZwE. He has trouble leaving the crane's cabin and even when he does, in the last few seconds of the video you can see he can't aim at you properly. I've also seen him fire in the completely wrong direction.

**Comment by coelckers** [comment]
Can you please try to narrow this down? I have no luck with this one, it seems to work fine for me.
