### ISSUE TITLE
[master] RRRA: Obscure issue possibly to do with a particular angle or something?

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#736]
Probably best to just watch the video: https://youtu.be/yqH5TYwsC34

Semi-reproducable, in RRRA's E1L2 when on the bike you can trigger this bug where the screen goes blank and the console is spammed with endless OpenAL errors.

When this occurs, it appears that the game does not process any mouse input whatsoever, I was unable to turn when I changed the view to the automap, irrespective of whether I forced synchronised input or not.

Legitimately completing the level in the blind caused the next level to load up perfectly fine without any issues.

Video is captured from a RelWithDebInfo build, unsure if its reproducable with a debug build. I haven't provided a save as saving the game in this state and loading it recovers from the issue.

**Comment by coelckers** [comment]
I'm unable to get this. I tried several times to play that level, it went fine every single time.

**Comment by mjr4077au** [comment]
I'll take a look tonight after I get home from my work dinner. I did have a quick look this, its reproducable in debug builds, and seems most consistently reproducable by giving the backwards key the quickest tap while moving the mouse left/right.

**Comment by coelckers** [comment]
Fixed. This was caused by negative speed values being passed to sqrt for backwards movement.
