### ISSUE TITLE
[BUG] Cannot open shrinker secret on E3L1

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#737]
### Raze version

master 77ae3b3b71

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I cannot open the shrinker secret on E3L1 by walking up to the Exotica poster and pressing on it like I normally would.

However, I was able to get it open by walking backwards a few steps while tapping the use key.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on episode 3 "Shrapnel City"
2. Go to the large Exotica poster
3. Press use on it

**Comment by coelckers** [comment]
fixed in 73deae88ce9dd833366cb02a683ed175049c850c
