### ISSUE TITLE
[BUG] Pancake mutant ninja girls

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#738]
### Raze version

master 73deae88ce

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Ninja girls are flat like pancakes.
![ShadowWarrior_0020](https://user-images.githubusercontent.com/6550500/199985461-5f543674-5bc5-43b6-b8e2-adc7307db703.png)
[Here's a saved game.](https://github.com/ZDoom/Raze/files/9938719/save0002.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play any level that has the ninja girl enemy (e.g. $boat)
2. Find one of the ninja girls

**Comment by coelckers** [comment]
fixed in 99753fd03a67f5714415861d5affaf031260153a
