### ISSUE TITLE
[BUG] Duke3D crushers too slow

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#739]
### Raze version

master 99753fd03a

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The crushers in Duke Nukem 3D are too slow.

[Here's a saved game in the area with the crushers from E2L4 "Fusion Station"](https://github.com/ZDoom/Raze/files/9943949/save0001.zip).

And a video from Duke Nukem 3D: Megaton Edition, showing the correct crusher speed:

https://user-images.githubusercontent.com/6550500/199866948-90da09b2-c963-405d-8805-7de31c7f55ef.mp4

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start any Duke Nukem 3D level that has crushers
2. Go to the area where the crushers are
3. They are too slow

**Comment by coelckers** [comment]
fixed in b4a49ea228e0fff196092ccf6e03b8550fa4592c
These  must multiply the specified speed with 16 which got lost recently.
