### ISSUE TITLE
[BUG] raze inconsistent symlink detection

### ISSUE THREAD

**Issue by pas-de-2** [ZDoom/Raze#740]
Just a small thing I noticed today while setting up raze. A symlink to DUKE3D.GRP in the raze_1.5.0 directory is detected fine. The same symlink in the /data subdir is not. Symlinks to Sw.grp or WT.GRP aren't detected no matter where I place them.

raze v1.5.0, Win10

**Comment by mjr4077au** [comment]
Why do you need symlinks anyway? Raze can/does search subdirectories so such a setup shouldn't be necessary.

**Comment by pas-de-2** [comment]
Don't get me wrong this isn't a priority at all, it's just something weird I noticed after I tried to symlink the files from my eduke32 directory and felt like documenting.

**Comment by coelckers** [comment]
This is an unsupported way to set up the game.
