### ISSUE TITLE
[BUG] Conveyor belts do not push luggage

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#741]
### Raze version

master b4a49ea228

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The conveyor belts in Shadow Warrior do not push luggage bags like they should.

[Here's a saved game](https://github.com/ZDoom/Raze/files/9946325/save0003.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a game on $airport.map
2. Play until you get the red key
3. Open the elevator
4. The conveyor belt (leads to a secret area) behind the counter should open up

**Comment by coelckers** [comment]
fixed in fd1864bb4861e2caec7248644abedcba9bd42587
