### ISSUE TITLE
[BUG] Chaingunner's spit too fast

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#742]
### Raze version

master b4a49ea228

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Chaingunner's spit projectiles are too fast. I'm pretty sure they weren't supposed to be that fast in the OG.

[Here's a saved game](https://github.com/ZDoom/Raze/files/9946338/save0002.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Encounter a chaingunner
2. Let him spit at you if he tries
3. The spit projectiles fly too fast

**Comment by coelckers** [comment]
I can't really say. Keep in mind that the Duke monsters are entirely being controlled by CON code, not by the engine itself.

**Comment by Talon1024** [comment]
Here's a video from BuildGDX, showing the correct behaviour:

https://user-images.githubusercontent.com/6550500/200436319-5bf4f0f0-2c70-4304-9bff-cfd751714132.mp4

**Comment by coelckers** [comment]
I cannot see anything in there - you kill him way too fast.

**Comment by Talon1024** [comment]
Here's a (hopefully) better video from E3L11 on DukeGDX:

https://user-images.githubusercontent.com/6550500/201050434-f45b4258-4d7b-46f7-a9d7-6306d843a191.mp4
