### ISSUE TITLE
[BUG] Some lifts stop at the wrong heights

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#743]
### Raze version

master b4a49ea228

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some elevators stop at the wrong heights.

Here's a screenshot showing the lift with the ceiling too low:

![Duke_0028](https://user-images.githubusercontent.com/6550500/200186381-c071e7ca-bf70-435c-91a7-adad09f2a374.png)

[And here's a saved game](https://github.com/ZDoom/Raze/files/9946441/save0003.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Activate one of these lifts (another one is the blue key lift on E3L11)
2. Notice the wrong ceiling height taken from the neighbouring sector

**Comment by coelckers** [comment]
fixed in 5ebf2fef893e42941f1a83e903c7fa08e0e6000b
