### ISSUE TITLE
[BUG] Weird wall on E2L1

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#744]
### Raze version

master b4a49ea228

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The "[weird wall](https://github.com/ZDoom/Raze/issues/539)" issue is happening again.

[save0004.zip](https://github.com/ZDoom/Raze/files/9948187/save0004.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Press the button to open the exit to the tunnel
3. Notice a weird fake wall appears right before you leave

**Comment by coelckers** [comment]
The existing handling did not work when the player crouches. Addressed in 8f5923c324d90bc3b099a31d7e4f297647e03ec8
Doing a proper fix in the clipper will require a lot more work, though.
