### ISSUE TITLE
[BUG] Ladders are too fast

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#745]
### Raze version

master 912b6a47c1

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Lo Wang climbs ladders too quickly.
[save0004.zip](https://github.com/ZDoom/Raze/files/9948373/save0004.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Grab on to a ladder
2. Try to climb
3. It is way too fast

**Comment by mjr4077au** [comment]
@Talon1024 I'm going to have a look at some of these tonight once work has finished, but just wanted to thank you for your continued devbuild reports, they all go far to make Raze stronger and better.
