### ISSUE TITLE
[BUG] Thrown dynamite sticks too slow

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#747]
### Raze version

master 5ebf2fef89

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The dynamite sticks in Redneck Rampage are thrown with too little velocity. They are supposed to be thrown very quickly, like in this video from RedneckGDX:

https://user-images.githubusercontent.com/6550500/200565369-756556ac-49f2-4889-b9d0-234a1fa5b72c.mp4

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Pick up a dynamite stick or dynamite box
2. Select the dynamite stick weapon
3. Throw one

**Comment by coelckers** [comment]
fixed in 32a447ea54af4b01ce16f7479ae15d318f6429b5
