### ISSUE TITLE
[BUG] Cannot pick up yellow keycard on $yamato

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#749]
### Raze version

master 5ebf2fef89

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I cannot pick up the yellow keycard on $yamato.map

[Here's a saved game in the room where the yellow keycard is](https://github.com/ZDoom/Raze/files/9961218/save0006.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Try to pick up the yellow keycard
3. It cannot be picked up

**Comment by coelckers** [comment]
fixed in d2f0981091e8c5fbedbcb2ed553c3d676aab97fd
