### ISSUE TITLE
[BUG] Big ripper acting weirdly

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#750]
### Raze version

master 5ebf2fef89

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The big ripper is acting weirdly. They try to scratch you even though they are out of range, and they try to jump off of non-existent surfaces, or surfaces that are too far away for them to reach.

[Here's a saved game](https://github.com/ZDoom/Raze/files/9961969/save0007.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Open the yellow door
3. Observe as you fight the ripper

**Comment by coelckers** [comment]
fixed in e88b24bce7bd1f385eb98df981eaf9e8ba3984ba
