### ISSUE TITLE
[BUG] Conveyor belts too fast

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#751]
### Raze version

master 5ebf2fef89

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Conveyor belts push the player too fast.

Here's a video from E4L2 in BuildGDX, showing the correct speed:

https://user-images.githubusercontent.com/6550500/200865852-a9421ce5-191e-4feb-be6f-7227b18bcf7a.mp4

[And here's a saved game for Raze from the same spot in E4L2](https://github.com/ZDoom/Raze/files/9972293/save0001.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Walk onto the conveyor belt
3. Too fast

**Comment by coelckers** [comment]
fixed in 53341ee525a9f6a8cfa9c20980d03a08669ac112
