### ISSUE TITLE
[BUG] Cannot roll pipebombs and dynamite sticks

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#752]
### Raze version

master 5ebf2fef89

### Which game are you running with Raze?

Duke Nukem 3D or Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Duke's pipe bombs and Leonard's dynamite sticks are supposed to roll on the floor when they crouch. Instead, the pipe bombs/dynamite sticks are thrown as if Duke/Leonard are standing up, but more slowly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get a pipe bomb or dynamite stick
2. Crouch
3. Fire while crouched

**Comment by coelckers** [comment]
fixed in a8585d72c773e724b7f57869cd4124646be0084c
