### ISSUE TITLE
[BUG] cl_weaponswitch does nothing

### ISSUE THREAD

**Issue by prg318** [ZDoom/Raze#753]
### Raze version

raze 1.5.0 and latest git

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

all GPUs

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In eduke32, the `cl_weaponswitch` option defines when the engine will switch to a new weapon (either on pickup or on using the last unit of ammo for a weapon).  eduke32's `P_AddWeaponMaybeSwitch()` and `P_CheckWeapon()` contain the logic for this.

Raze currently doesnt't seem to handle `cl_weaponswitch` besides the handling of the cvar itself.  It would be awesome if at least `cl_weaponswitch 0` so that automatic weapon switching can be completely disabled

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load "Lunar Apocalypse" episode of DUKE3D
2. Enter `cl_weaponswitch 0` in console
3. Turn around and go through the teleporter to grab the rocket launcher.  Notice that its automatically picked up.
4. Fire all five of the rockets.  Notice how the pistol is automatically switched out.

### Your configuration

```ini
cl_weaponswitch 0
```

### Provide a Log

Let me know if there's log files that would help, but I don't see anything relevant in the logs.

**Comment by coelckers** [comment]
added in ac4be79e9621802be48d0295fb4daa5d237cd900

**Comment by prg318** [comment]
Awesome!  Works great!  Looks it required changes in a lot more places than I anticipated - awesome.  This will probably prevent me blowing myself up with an RPG many times forward.  Thanks for your work on this issue and an awesome source port
