### ISSUE TITLE
[BUG] Jumpy ladders

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#754]
### Raze version

master d2f0981091

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some ladders in Shadow Warrior are "jumpy"; As the player tries to climb one, they seem to detach from it as if they reached the top, even if they haven't. It happens continuously as the player tries to climb any such ladder.

Such ladders can be found on Sumo Sky Palace ($plax1) and Floating Fortress ($yamato).

This bug is also present in BuildGDX, but not in the original DOS version of Shadow Warrior, nor Shadow Warrior Classic Redux.

I think it's because there are portals at the top of those ladders, but I don't know for sure.

[Here's a saved game from Sumo Sky Palace](https://github.com/ZDoom/Raze/files/9974288/save0008.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Try to climb the ladder in front of you
3. Notice how the player "jumps" as they try to climb the ladder

**Comment by coelckers** [comment]
I have no idea how this could work originally, but the setup here is at odds with the ladder code. The ladder code checks if the player has reached the floor of the neighboring sector and if so makes the player jump up.
But this only works if the back sector is actually higher than the front sector.
In this case the back sector has the same floor height - far below where the action takes place. Those platforms are made of sprites.

As this is not a game breaking issue and I cannot check how the original code got around this I'm putting it on hold for now.

**Comment by Talon1024** [comment]
[Here's a saved game](https://github.com/ZDoom/Raze/files/9993785/save0001.zip) from the "jumpy ladder" in Floating Fortress ($yamato). I don't know if this case is any different from the one in Sumo Sky Palace, but I thought it would be worth a look.

**Comment by coelckers** [comment]
It's exactly the same problem. SW's original ladder code does not work (it crashes) when the ladder is on a wall with no back sector. So they added an empty dummy sector behind it and gave it the wrong floor height for the ladder to work correctly.

**Comment by Talon1024** [comment]
If you're interested in the Shadow Warrior Classic Redux sources, a quick GitHub search [found this](https://github.com/TermiT/sw-redux).

**Comment by mjr4077au** [comment]
I've known about the source code there and did in fact check it out when you said SWCR doesn't experience this issue, but I found no discernable difference between what we/other ports do and it. The next thing to do here would be to try and build SWCR ourselves and see what it does.

**Comment by coelckers** [comment]
As I see no way to address this or even confirm that it is an issue to be addressed, I'm closing this report.
