### ISSUE TITLE
[BUG] [MINOR] Running "useitem" in the console with no argument crashes raze

### ISSUE THREAD

**Issue by prg318** [ZDoom/Raze#756]
### Raze version

raze 1.5.0 and latest git

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

AMD 5700 XT (but likely hardware independent)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the `useitem`  or `slot` command is run in the console without any arguments, Raze crashes:

```
E1L1: Hollywood Holocaust
]useitem


*** Fatal Error ***
!!! Failed to exec debug process
zsh: segmentation fault (core dumped)  raze
```

It might be an improvement if running `useitem` or `slot` without any arguments could provide a basic help string.

Thank you for the Raze Team's efforts on Raze - it's really awesome

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start raze with any GRP and load any level
2. Open the console
3. Enter `slot` or `useitem` without anything following it.

Raze will crash

### Provide a Log

Let me know if there is anything else I can provide, but this should be trivial to reproduce.

**Comment by coelckers** [comment]
fixed in 6a6e9299caa74a7eb6a8c0487e59c0cbf3cf2e38
