### ISSUE TITLE
[BUG] Bubbles do not rise

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#757]
### Raze version

master bd5d96df10

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The underwater bubbles in Duke Nukem 3D do not rise like they should.

[Here's a saved game](https://github.com/ZDoom/Raze/files/9994731/save0002.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Fire any weapon that spawns bubbles underwater
3. The bubbles will not rise like they should

**Comment by coelckers** [comment]
fixed in e867c4603f051cd1eb0a16f7f79cf9108c12112a
