### ISSUE TITLE
[BUG] Cannonballs do not explode

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#758]
### Raze version

master bd5d96df10

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The cannonballs in Babe Land (E4L4) do not explode.

A saved game can be found in #757

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game from #757
2. Get out of the water
3. Watch as the cannons fire their cannon balls without exploding

**Comment by coelckers** [comment]
fixed in c94d2fb3d08e7358fed2f7e14b715b6d60bc2ffc
