### ISSUE TITLE
[BUG] Weapons broken in Redneck Rampage

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#759]
### Raze version

master ac4be79e96

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Ever since ac4be79e96, weapons cannot be used in Redneck Rampage. The player should start with a pistol and 48 rounds, but they appear to have only a crowbar. In addition, firing weapons does not work.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game of Redneck Rampage
2. Notice your crowbar is equipped
3. Try to hopelessly open fire

**Comment by coelckers** [comment]
fixed in 36f753df8f90b8d64563b502882ced974ff81881
