### ISSUE TITLE
[BUG] Assertion failures

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#760]
### Raze version

master 6b3e57fd2c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Sometimes, the game randomly has assertion failures. I can't tell what exactly is causing these assertion failures, but I think it's related to the recent scripting changes, since builds from before "walls" were scriptified work fine.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game with a debug build
2. Play for a while
3. Assertion failure (see log below)

### Provide a Log

    
    #2  0x00007ffff7465729 in __assert_fail_base (
        fmt=0x7ffff75fb588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
        assertion=0x55555648a65b "index < Count",
        file=0x55555648a470 "../source/common/utility/tarray.h", line=1887,
        function=<optimized out>) at assert.c:92
    #3  0x00007ffff7476fd6 in __GI___assert_fail (
        assertion=0x55555648a65b "index < Count",
        file=0x55555648a470 "../source/common/utility/tarray.h", line=1887,
        function=0x55555648a600 "T& TArrayView<T>::operator[](size_t) const [with T>
    #4  0x0000555555bbce70 in TArrayView<walltype>::operator[] (
        this=0x55555ecc6090, index=4) at ../source/common/utility/tarray.h:1887
    #5  0x0000555555bba7fa in pushmove (pos=...,
        pSect=0x555556ce13e0 <Duke3d::ps+928>, walldist=10.25, ceildist=4,
        floordist=4, cliptype=65537) at ../source/core/gamefuncs.cpp:1223
    #6  0x0000555555f8372b in Duke3d::processinput_d (snum=0)
        at ../source/games/duke/src/player_d.cpp:3085
    #7  0x0000555555f3458d in Duke3d::GameInterface::Ticker (this=0x55555719ab70)
        at ../source/games/duke/src/gameloop.cpp:84
    #8  0x0000555555ba775c in GameTicker () at ../source/core/mainloop.cpp:357
    #9  0x0000555555ba8177 in TryRunTics () at ../source/core/mainloop.cpp:665
    #10 0x0000555555ba82e4 in MainLoop () at ../source/core/mainloop.cpp:723
    #11 0x0000555555baf7ee in RunGame () at ../source/core/gamecontrol.cpp:1151
    #12 0x0000555555bad723 in GameMain () at ../source/core/gamecontrol.cpp:599
    #13 0x00005555559eca37 in main (argc=1, argv=0x7fffffffde78)
        at ../source/common/platform/posix/sdl/i_main.cpp:197

**Comment by coelckers** [comment]
fixed in 043e0053630144e8a4d02798e4dec5ce27253698

It was actually quite obvious when I had a look at the offending line.
