### ISSUE TITLE
[BUG] Slimer debris is wrong

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#764]
### Raze version

master 1e421af8bc

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When a "Protozoid slimer" dies, it explodes into green glass/plastic shards, rather than filth pieces.
![Duke_0030](https://user-images.githubusercontent.com/6550500/202926764-a488f68b-36bf-4a18-a423-2aa2793a153a.png)
[Here's a saved game](https://github.com/ZDoom/Raze/files/10050715/save0001.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Kill a protozoid slimer
2. Watch as it explodes into green glass/plastic shards

**Comment by coelckers** [comment]
fixed in 6cb3e2f457e3ca291bb2a8319b1a8acf38fa12c3

This fell victim to unexpected operator precedence in C.
