### ISSUE TITLE
[BUG] Horizontal crushers on Critical Mass (E4L8) not working properly

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#765]
### Raze version

master 6cb3e2f457

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The big horizontal crushers on E4L8 "Critical Mass" do not work properly. They are supposed to be sandwiched together, but the door on the left just gets skewed.
![Duke_0031](https://user-images.githubusercontent.com/6550500/203108698-bcec44ed-5980-4b97-b775-6fe4f36c14d6.png)
[Here's a saved game from before it happens](https://github.com/ZDoom/Raze/files/10058340/save0004.zip), [And after it happens](https://github.com/ZDoom/Raze/files/10058344/save0003.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a game on E4L8
2. Get past the exploding room and the protector drone(s)
3. Start the horizontal crusher by pressing the "pressure maintenance" button.

**Comment by coelckers** [comment]
fixed in 0e1121ed51e99e1dc898d0799055c9946a96fd60

That is some truly inept math in there, getting compounded by a poor distance approximation.
