### ISSUE TITLE
[BUG] Cannot climb up to grab the key (Redneck Route 66 Slaughterhouse)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#766]
### Raze version

master 6cb3e2f457

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I cannot climb on top of the machines to grab the key in the Slaughterhouse level from Redneck Rampage: Suckin' Grits on Route 66.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10059111/save0000.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on Route66/Slaughtr
2. Go to where the first key is
3. Try to climb up to reach it
4. It is impossible

**Comment by coelckers** [comment]
fixed in 229ee3dbe45602f46a387720a88772ec9f875d6a

Introduced by a supposed clipping improvement copied from EDuke32.
