### ISSUE TITLE
[BUG] Locked doors do not work

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#768]
### Raze version

master 6cb3e2f457

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Doors that are supposed to be locked can always be opened, regardless of whether the player has unlocked them or not.

[Here's a saved game from the arcade room on E1L1. There's a door which is supposed to require the red keycard, but it can be opened without the player unlocking it beforehand.](https://github.com/ZDoom/Raze/files/10078367/save0005.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on any map with a locked door
2. Go to the locked door
3. Open it
4. The door should not open if it hasn't been unlocked

**Comment by coelckers** [comment]
fixed in aa3df50f9b3118190f956d632eaf77f5044703d9
