### ISSUE TITLE
[BUG] Crash while trying to load RR levels from menu, etc.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#769]
### Raze version

1.6pre

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/48643140/203682705-48c5caae-7823-41af-b5f4-09e2f7eb33b2.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
fixed in 13e19bad36dfd2595f3ff75640126aa8deb7bc8a
