### ISSUE TITLE
[BUG] Duke WT: Issues with teleporter in E5L1

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#772]
### Raze version

1.6pre

### Which game are you running with Raze?

Duke Nukem 3D

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Once you've entered this room, you can't get out because there's a teleporter trip that keeps putting you back in. Works fine in 1.5.0.

https://youtu.be/hKtkoxQ-X0E

Screenshot has coordinates in it for getting to the spot.

![Duke_0042](https://user-images.githubusercontent.com/48643140/203994078-e158c35a-316b-45ac-a86f-5686fc22fb08.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
Seems to work now. I susepect the same activator problem as the locked doors as the cause,.
