### ISSUE TITLE
[BUG] Duke: Enemy actor can't circumnavigate dead player

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#773]
### Raze version

1.6pre

### Which game are you running with Raze?

Duke Nukem 3D

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

1.5.0 behaviour: https://youtu.be/Gki-1_gid_s

1.6pre behaviour: https://youtu.be/FlCP2bW37tI

**Comment by coelckers** [comment]
fixed in c9a94a4899447718c95d95aeaa4cd91396576279
Interestingly, the bug was only in move_d but not in move_r...
