### ISSUE TITLE
[BUG] Crash on Disgraceland

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#774]
### Raze version

master 1d39e1edc1

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04.5 LTS

### Relevant hardware info

Intel i5-4690k CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to hit this switch (opens a secret area IIRC) causes the game to crash
![Redneck_0008](https://user-images.githubusercontent.com/6550500/204984330-2f8db4ea-1989-4756-be49-9da32d30b733.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/10129951/save0002.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on E2L4
2. Try to flip the switch shown in the screenshot
3. Crash

### Provide a Log

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

**Comment by coelckers** [comment]
fixed in f30abffa824fc7a1ed62d336dbfebb53c14745cf
Some leftover debug thing... :(
