### ISSUE TITLE
[BUG] Rats cannot leave the holes

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#775]
### Raze version

master a580e9d884

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The rats shown here cannot leave the holes:

![Blood_0026](https://user-images.githubusercontent.com/6550500/205501108-d7e0f33d-212f-401c-aead-bc4009cada75.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/10148940/save0003.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new one on E1M5 "Hallowed Grounds"
2. Go to the area shown in the screenshot and pick up the key
3. The walls should open up and the rats should be able to get out of the holes and attack the player.

**Comment by mjr4077au** [comment]
I was wondering if by chance you know of the experience via DOSBox? When I was testing a recent version of NBlood, they never left the alcove for me either. https://youtu.be/bINDv-wO-Ms

We occasionally cherry-pick from NBlood, I wonder if it's a regression over there as well?

**Comment by mjr4077au** [comment]
As an addendum, this is a screenshot from an April 2020 version of NBlood with the rats also not leaving the alcove.

![image](https://user-images.githubusercontent.com/48643140/206844269-9a6a2029-334a-419f-b1b3-ab393cc8dbf4.png)

**Comment by mjr4077au** [comment]
As an addendum to my addendum, they don't leave the alcoves in DOS either. This is probably a mapping error and they're too large to make it through the gap.

![image](https://user-images.githubusercontent.com/48643140/206849452-88f0ec7c-d651-45b5-a769-a0c97693fda1.png)
