### ISSUE TITLE
[BUG] Crash when leaving Slaughterhouse and entering Fun Park

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#776]
### Raze version

master ff8863833a

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When leaving Slaughterhouse (Route66/slaughtr) and entering Fun Park (Route66/minigolf), the game either crashes or has an assertion failure.

However, this does not happen when warping to Fun Park using the `map` CCMD.

[Here's a saved game at the end of Slaughterhouse](https://github.com/ZDoom/Raze/files/10171290/save0003.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play through the Slaughterhouse level or load the above saved game
2. Hit Bubba with the crowbar to end the level
3. Wait for Fun Park to load
4. Crash or assertion failure

### Provide a Log

```raze: ../source/core/savegamehelp.h:23: FSerializer& Serialize(FSerializer&, const char*, T*&, T**) [with T = sectortype]: Assertion `arc.isReading() || w == nullptr || (w >= &sector[0] && w <= &sector.Last())' failed.```

**Comment by mjr4077au** [comment]
I wasn't able to get the crash with your save, it proceeded to Fun Park without an issue (Windows, MSVC). What platform, compiler, etc? Would it be possible to please get the stack trace?

**Comment by Talon1024** [comment]
Here's the assertion failure that occurs to me:

    $1 = "If your mouse cursor is stuck, enter this:"
    $2 = "call I_ReleaseMouseCapture()"
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [Detaching after vfork from child process 6106]
    [Detaching after vfork from child process 6107]
    [Detaching after vfork from child process 6109]
    [New Thread 0x7ffff60c9700 (LWP 6116)]
    [Thread 0x7ffff60c9700 (LWP 6116) exited]
    [New Thread 0x7ffff3769700 (LWP 6117)]
    [Thread 0x7ffff3769700 (LWP 6117) exited]
    [New Thread 0x7ffff3769700 (LWP 6118)]
    [New Thread 0x7ffff4269700 (LWP 6119)]
    [New Thread 0x7ffff4068700 (LWP 6120)]
    [New Thread 0x7ffff2741700 (LWP 6121)]
    [Thread 0x7ffff2741700 (LWP 6121) exited]
    [New Thread 0x7ffff2741700 (LWP 6122)]
    [New Thread 0x7fffc4e31700 (LWP 6123)]
    [New Thread 0x7fffc0630700 (LWP 6124)]
    [New Thread 0x7fffc444c700 (LWP 6125)]
    [New Thread 0x7fffa89ff700 (LWP 6126)]
    
    Thread 1 "raze" received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff7466859 in __GI_abort () at abort.c:79
    #2  0x00007ffff7466729 in __assert_fail_base (
        fmt=0x7ffff75fc588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
        assertion=0x5555564acdb8 "arc.isReading() || w == nullptr || (w >= &sector[0] && w <= &sector.Last())", 
        file=0x5555564acd9a "../source/core/savegamehelp.h", line=23, 
        function=<optimized out>) at assert.c:92
    #3  0x00007ffff7477fd6 in __GI___assert_fail (
        assertion=0x5555564acdb8 "arc.isReading() || w == nullptr || (w >= &sector[0] && w <= &sector.Last())", 
        file=0x5555564acd9a "../source/core/savegamehelp.h", line=23, 
        function=0x5555564acd48 "FSerializer& Serialize(FSerializer&, const char*, T*&, T**) [with T = sectortype]") at assert.c:101
    #4  0x0000555555ba6907 in Serialize<sectortype> (arc=..., 
        keyname=0x555556534fb5 "sector", w=@0x555561f787d0: 0x5555648070a8, 
        def=0x555556e0ef40 <Duke3d::Serialize(FSerializer&, char const*, Duke3d::animate&, Duke3d::animate*)::nul>) at ../source/core/savegamehelp.h:23
    #5  0x0000555555bfbc6e in FSerializer::operator()<sectortype*> (
        this=0x7fffffffc970, key=0x555556534fb5 "sector", 
        obj=@0x555561f787d0: 0x5555648070a8, def=@0x555556e0ef40: 0x0)
        at ../source/common/engine/serializer.h:126
    #6  0x0000555555f6a168 in Duke3d::Serialize (arc=..., keyname=0x0, w=..., 
        def=0x555556e0ef40 <Duke3d::Serialize(FSerializer&, char const*, Duke3d::animate&, Duke3d::animate*)::nul>) at ../source/games/duke/src/savegame.cpp:332
    #7  0x0000555555f849c0 in Serialize<Duke3d::animate, Duke3d::animate> (
        arc=..., key=0x5555565350bf "animates", value=..., def=0x0)
        at ../source/common/engine/serializer.h:267
    #8  0x0000555555f828b5 in FSerializer::operator()<TArray<Duke3d::animate, Duke3d::animate> > (this=0x7fffffffc970, key=0x5555565350bf "animates", obj=...)
        at ../source/common/engine/serializer.h:120
    #9  0x0000555555f6a559 in Duke3d::GameInterface::SerializeGameState (
        this=0x5555571c0c60, arc=...) at ../source/games/duke/src/savegame.cpp:385
    #10 0x0000555555bf75b0 in SerializeSession (arc=...)
        at ../source/core/savegamehelp.cpp:115
    #11 0x0000555555bf7c7c in WriteSavegame (
        filename=0x555561ecc3fc "/home/kevinc/.config/raze/Redneck.Route66/auto0000.dsave", name=0x5555647792dc "Autosave 2022-12-08 04:52:30")
        at ../source/core/savegamehelp.cpp:224
    #12 0x0000555555bfa265 in G_DoSaveGame (ok4q=false, forceq=false, 
        fn=0x555561ecc3fc "/home/kevinc/.config/raze/Redneck.Route66/auto0000.dsave", desc=0x5555647792dc "Autosave 2022-12-08 04:52:30")
        at ../source/core/savegamehelp.cpp:798
    #13 0x0000555555bfa505 in M_Autosave () at ../source/core/savegamehelp.cpp:835
    #14 0x0000555555bb9bc9 in GameTicker () at ../source/core/mainloop.cpp:263
    #15 0x0000555555bba861 in TryRunTics () at ../source/core/mainloop.cpp:665
    #16 0x0000555555bba9ce in MainLoop () at ../source/core/mainloop.cpp:723
    #17 0x0000555555bc1ed8 in RunGame () at ../source/core/gamecontrol.cpp:1151
    #18 0x0000555555bbfe0d in GameMain () at ../source/core/gamecontrol.cpp:599
    #19 0x00005555559fea37 in main (argc=1, argv=0x7fffffffde78)
        at ../source/common/platform/posix/sdl/i_main.cpp:197

**Comment by coelckers** [comment]
fixed in 7d82ae28f4c2730c8534e24edd27d320173cede1
