### ISSUE TITLE
[BUG]  -cryptic flag is borked on Linux.

### ISSUE THREAD

**Issue by V0rt3x667** [ZDoom/Raze#777]
### Raze version

Raze 1.5.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running raze -cryptic from a terminal, Blood: Cryptic Passage does not load correctly. The Blood splash screen is displayed instead of the Cryptic Passage splash screen and textures are not rendered correctly in game.

There are two workarounds for the issue:
1: Use the GUI IWAD Dialogue Box and select Blood: Cryptic Passage
2: Run raze -iwad blood.rff -con cryptic.ini -art cpart07.ar_ -art cpart15.ar_ from a terminal. 
If the file names are uppercase then change as appropriate due to Linux being a case sensitive OS.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open a terminal
2. Run the command: raze -cryptic
3.Observe the glitches noted above

**Comment by V0rt3x667** [comment]
Hello, my game files are all lowercase. I can rename them and test again. I will let you know how it goes. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by V0rt3x667** [comment]
Hi, I renamed all of the files to uppercase but the issue still occurs when using the -cryptic flag.

**Comment by mjr4077au** [comment]
Thanks for hanging in there! Fixed as of dc4105798449b5dcbe81c5a9a2e012fcb405f094. It was broken for all platforms and not just POSIX environments.

![image](https://user-images.githubusercontent.com/48643140/206813584-60bf201c-77f5-4bba-bf50-429ea858477d.png)

**Comment by V0rt3x667** [comment]
Thank you.
