### ISSUE TITLE
[BUG] Lighting effects not working properly after re-loading saved game

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#783]
### Raze version

1.6.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some lighting effects are completely broken after re-loading a saved game, such as the one near the start of E2L8 "Dark Side".

After re-loading a saved game from a full Episode 2 playthrough, this is what the area in question looked like:
![Duke_0032](https://user-images.githubusercontent.com/6550500/207237863-9f81034f-59a2-49ed-a853-8adf74b391e5.png)

This is what the area should look like. It was taken from a fresh start on E2L8
![Duke_0033](https://user-images.githubusercontent.com/6550500/207237868-f41f75a5-006b-484e-b12f-e8279e2cf65b.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a map with one of these lighting effects, like E2L8
2. Save your game
3. Re-load the saved game

**Comment by coelckers** [comment]
I cannot reproduce this, neither with 1.6.0 nor with current master.
Reloading a save from that place looks correct.

**Comment by coelckers** [comment]
I still cannot reproduce it on my system but if I am not mistaken this should fix it

efd6d2cf07ecd061a516491c53125028f6d36026
