### ISSUE TITLE
[BUG] Pipebombs riding along ceilings

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#784]
### Raze version

master 9c1fc93e1c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If a pipebomb hits a sector ceiling, it seems to stick to it and ride along it as if it were magnetic.

https://user-images.githubusercontent.com/6550500/207283051-350517a5-69ca-4119-9cb1-b4b2dbc56632.mp4

[Here's a saved game](https://github.com/ZDoom/Raze/files/10216540/dissed.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Throw a pipebomb upwards when standing under a low ceiling
2. Watch as it rolls along the "ceiling" as if it were the floor

**Comment by coelckers** [comment]
fixed in71425a94af33498e27c7cb78bb64d6fbbaf4589e
