### ISSUE TITLE
[BUG] Electric chair is harmless

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#785]
### Raze version

master 9c1fc93e1c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The electric chair at the start of E1L3 is harmless.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10216640/electric.chair.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on Duke Nukem 3D E1L3 or load the saved game
2. The electric chair is supposed to hurt you, but it does not.

**Comment by coelckers** [comment]
fixed in dc55669d8a89e9a21749dcde43c4196daf2d4245
