### ISSUE TITLE
[BUG] E1L5 shrink ray does not work

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#786]
### Raze version

master 9c1fc93e1c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The shrink ray that you're supposed to use in E1L5 does not shrink the player when it hits.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10216912/bad.shrink.ray.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Wait for the shrink ray to hit
3. Nothing happens

**Comment by coelckers** [comment]
fixed incd28c818b0170cefc62d1c9e942cdb66a62e3804
