### ISSUE TITLE
[BUG] E2L2 start is too fast

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#789]
### Raze version

master 9c1fc93e1c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the start of E2L2, you get pushed into space, and through the space station until you reach the second room.

That's not supposed to happen. The player is supposed to be on the shuttle until it docks.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on E2L2

**Comment by coelckers** [comment]
fixed in fba882e368ae0edf70cec2cb787d026cc59dfe6a
