### ISSUE TITLE
[BUG] PowerSlave/Exhumed Anubis enemies stuck walking in place

### ISSUE THREAD

**Issue by ChapyGuy** [ZDoom/Raze#790]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

10.0.19045 Build 19045

### Relevant hardware info

Ryzen 3700X, GTX 1070ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It appears that when an Anubis is put in a pain state before detecting the player they get frozen walking in place and cannot be broken out of this state.

### Steps to reproduce the behaviour.

Hurt any Anubis before it activates and chases the player. It can happen multiple times in the first level. They behave normally if they start moving on their own, even if hurt.

**Comment by coelckers** [comment]
should be fixed with ff09257d4739df54d59465ad2e9f95e872bbfb1e

But due to the difficulty to trigger this thing it's hard to really confirm that it helped.
