### ISSUE TITLE
[BUG] Blood's "fish-man" enemies die instantly

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#791]
### Raze version

master f893f12ed7

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The "fish-man" enemy in Blood dies instantly as soon as he notices you, if you are underwater.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10225381/aqua.enemy.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on E2M1
2. Dive

**Comment by coelckers** [comment]
fixed in 9fc17a4bcf9c5ff0816d0d36d09b90d1bed17649
