### ISSUE TITLE
[BUG] Hovering patrol vehicles not shooting

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#792]
### Raze version

master f893f12ed7

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The recon/patrol hovercars in Duke Nukem 3D are not firing like they should.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10226945/recon.vehicle.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a level with one of those enemies on it (E1L2, E3L11, E4L2)
2. The recon/patrol hovercars should fire at you when moving around

**Comment by coelckers** [comment]
fixed in e9acd74157a326c2f993f48e2752382cd9e1dd4d
