### ISSUE TITLE
[BUG] Cannot destroy mortars

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#793]
### Raze version

master f893f12ed7

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the Battlelord or Battlelord sentry leaves a mortar on the ground, I cannot detonate it myself by shooting at it or detonating my own explosives near it.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10227264/mortar.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or fight a Battlelord sentry
2. Try to shoot at the mortars it leaves behind, if any
3. They cannot be destroyed manually

**Comment by coelckers** [comment]
fixed in 9a1a90a730ae41a5b922e904643db1822abe0115
