### ISSUE TITLE
[BUG] Assertion failure when entering E2M6

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#794]
### Raze version

master 6e4e2b04eb

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

An assertion failure occurs when entering E2M6 "The Cold Rush". See the log below.

[Here's a saved game at the end of E2M5 "The Haunting"](https://github.com/ZDoom/Raze/files/10233325/bloody.hell.zip).

[And a GDB log](https://github.com/ZDoom/Raze/files/10233356/raze-gdb.log)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or enter `map e2m6` into the console
2. If you entered `map e2m6` into the console, close the console
3. Assertion failure

### Provide a Log

```raze: ../source/common/utility/tarray.h:1897: T& TArrayView<T>::operator[](size_t) const [with T = walltype; size_t = long unsigned int]: Assertion `index < Count' failed.```

**Comment by coelckers** [comment]
fixed in 82c30f551f95a31c02368d53519eda7e229e8a71

Actually a map bug but it got caught in stricter range checks.
