### ISSUE TITLE
[BUG] Forced "sword start" on every level

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#796]
### Raze version

master 8bbf7f4e00

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Shadow Warrior, a "sword start" is forced on every level. Weapons, health, items, armor, etc. are all reset upon entering another level, even if coming from a previous level.

[Here's a saved game at the end of level 1](https://github.com/ZDoom/Raze/files/10246283/end.of.level.1.zip).
[And another saved game, at the end of level 2](https://github.com/ZDoom/Raze/files/10246284/end.of.level.2.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play through a level in Shadow Warrior
2. Exit the level
3. Notice all your stuff is missing

**Comment by mjr4077au** [comment]
Thanks mate, an oversight on my end when I was fixing up how the game recovers from a death state.
