### ISSUE TITLE
[BUG] Barrels that should be destructable

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#797]
### Raze version

master cf5ba0886a

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

These barrels cannot be broken, but players and enemies should be able to break them:

![Duke_0035](https://user-images.githubusercontent.com/6550500/208217027-40f863c8-6123-4739-bed1-1b9374185ca5.png)
![Duke_0036](https://user-images.githubusercontent.com/6550500/208217031-0719b77f-5d1b-49ac-be82-05c1046d3afa.png)
![Duke_0037](https://user-images.githubusercontent.com/6550500/208217033-07887aee-bf38-4b41-b72c-1bfb1db77048.png)

And the first barrel shown in this series of screenshots should contain a box of shotgun shells.

[Here's a saved game at the end of E4L2](https://github.com/ZDoom/Raze/files/10250464/barrel.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a level which has these barrels, like E4L2 or E4L9.
2. Try to destroy the aforementioned barrels
3. They cannot be destroyed

**Comment by coelckers** [comment]
fixed in 46660ab889ab4ee47ea27af6e1dc8feb26771306

Some IDs got mixed up between Duke and RR.
