### ISSUE TITLE
Music config?

### ISSUE THREAD

**Issue by stevenvachon** [ZDoom/Raze#798]
I've been unable to find documentation on this and forums are little help as well.

How does one configure custom music mapping to files for Blood, Duke Nukem 3D and Shadow Warrior?

* I have *.flac and *.ogg files for each.
* Blood is unique in that it has _differing_ CD audio and MIDI, so I'd like to provide both.

**Comment by coelckers** [comment]
Generally, it is sufficient to just replace the existing sound files with same-named alternatives.
The CD tracks for Blood are named "blood01.ogg" - "blood09.ogg". You can replace these only with other .ogg files
To replace the MIDIs you have to manually enable the "extended lookup" feature in the advanced sound options menu. By default it only looks for files with both the same name and the same extension.
Other setup is not needed.

**Comment by stevenvachon** [comment]
For the record, it now works and without the need of a zip file. These are the file names for both CD audio and MIDIs:

* music\blood02.flac
* music\blood03.flac
* music\blood04.flac
* music\blood05.flac
* music\blood06.flac
* music\blood07.flac
* music\blood08.flac
* music\blood09.flac
* music\cblood1.flac
* music\cblood2.flac
* music\cblood3.flac
* music\cblood4.flac
* music\cblood5.flac
* music\cblood6.flac
* music\cblood7.flac
* music\cblood8.flac
* music\cblood9.flac
* music\cblood10.flac
* music\pestis.flac
* music\unholy.flac
