### ISSUE TITLE
[BUG] Player rotates faster than rotating sectors

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#799]
### Raze version

master cf5ba0886a

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the player is standing on a rotating sector, like the spinner in E3M5, the player rotates faster than the sector rotates.

[Here's a saved game from within the spinner on E3M5](https://github.com/ZDoom/Raze/files/10252169/spinner.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Stand on a rotating sector
2. Activate the rotation
3. Notice you are turning faster than the sector

**Comment by coelckers** [comment]
fixed in bfe958abd65e75bea7a47866cc5c0ebabb6a641f
