### ISSUE TITLE
[BUG] two conflicting Blood mods results in one not loading

### ISSUE THREAD

**Issue by stevenvachon** [ZDoom/Raze#800]
### Raze version

1.6.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Home

### Relevant hardware info

Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz   2.81 GHz; Asus ROG Strix GeForce RTX 3080 OC

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I run with:
```shell
raze -iwad blood/blood.rff -file blood/voxels_blood_v095.zip -file blood/Blood_-_Coagulated.zip
```

_voxels\_blood\_v095.zip_ and _Blood\_-\_Coagulated.zip_ share a few voxel model file names, which causes one of the mods to be completely excluded from loading. I would think that the best solution would be to load in succession, replacing any previous in memory.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Blood with more than one mod containing the same named files
2. 
3.

### Your configuration

```ini
I don't have a _raze.ini_ file 🤷‍♂️
```

**Comment by mjr4077au** [comment]
The mods will only load consecutively if the DEF files within them have `-raze` as a suffix (`blood-raze.def`). Because this is a change in established behaviour, it has to be opt-in from the mod. You can rename the DEF files yourself though as I'm sure these will work fine together.

**Comment by stevenvachon** [comment]
So, the only available solution to me is to manually modify the mod contents? That is something that I was avoiding because I'll have to redo it when upstream changes are released. If I were to do this, I would get selective as to which models I preferred instead of the suffix change.

**Comment by mjr4077au** [comment]
Changing the default behaviour to allow this without the suffix breaks defined/expected behaviour. Even if the original experience is crap, it's not something we can risk. Most mods that are developed have included a -raze.def file and the ones that haven't probably don't get updated anymore anyway so manually making a change that you know will work isn't that big of a deal.

**Comment by coelckers** [comment]
If the mods were not made for Raze, renaming may be the only way to get them working as intended,. The current behavior is fully intentional because it mimics NBlood.
