### ISSUE TITLE
[Blood] Version number in the full HUD

### ISSUE THREAD

**Issue by lgallen95** [ZDoom/Raze#801]
### Raze version

Raze v1.6.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

In Blood's "full" HUD, there is a space reserved for the version of Blood you are running. In Raze, this space is empty.

### Describe the solution you'd like

I'm thinking this space could be filled with either Blood's version or Raze's version.

**Comment by mjr4077au** [comment]
@coelckers with this one, is the engine's version number exposed to ZScript in any way?

**Comment by coelckers** [comment]
TBH I don't see much of a point adding this.
