### ISSUE TITLE
[BUG] Scanning too many Directories on Startup

### ISSUE THREAD

**Issue by CandiceJoy** [ZDoom/Raze#802]
### Raze version

1.6.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

Ventura 13.1

### Relevant hardware info

2021 M1 Pro 13" Macbook Pro with 1tbh HDD

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/8854890/208287858-ca12f80b-a08a-4f8f-82fb-d33dffdc4cee.png">

Upon running raze as shown in the screenshot, it attempts to scan many irrelevant directories and subsequently hangs, purportedly until force closed.  This happens with HEAD as well.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download Raze 1.6.0 or clone HEAD and build
2. Run Raze using a similar command to the screenshot

### Your configuration

```ini
(This isn't a rich text field to be able to use attachments or links)
```

### Provide a Log

[raze.log](https://github.com/ZDoom/Raze/files/10253395/raze.log)

**Comment by coelckers** [comment]
What I need is your autoload section.  Did you really put your home folder in there with '/*'? 
Yes, if you do that it will scan all kinds of shit it's not supposed to as it recursively traverses the entire directory tree under the given path.

Short answer: Don't do that!

**Comment by CandiceJoy** [comment]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/8854890/208288675-4a05ee1c-aa7d-4288-8eaa-0cb52f5f3690.png">
This file was deleted before I ran the build process.  Raze generated it in this state.

**Comment by CandiceJoy** [comment]
The function InitFileSystem() in source/core/initfs.cpp is scanning the entire subtree of whatever GRP you give it.  Meaning if my GRP is /duke3d.grp, it will scan my entire directory structure.  Since I'm putting mine in /Users/candice, it's scanning my entire home directory.  I believe I might be able to fix this, but I don't know the best way to go about it in all honesty.  

Line 338 is the "offending" line.  "D_AddFile(Files, fn, true, -1, GameConfig);" fn is the directory containing the GRP, as per line 317 "fn = ExtractFilePath(grp.FileName);", and D_AddFile scans the entire directory tree its given.  Unfortunately, I don't think there's a "don't scan this tree if it's too large" function :P  My two initial thoughts are to have D_AddFile take an extra bool to determine whether to scan subtrees or not, or to have a second AddFile function that only adds the file its given and no more.  Honestly, I don't think either approach is great, and it might even be a case of there simply not being any good fix.

That all being said, I'm willing to try if you can tell me what you'd like done......or, if nothing, then congrats!  I did it!  We can close the issue :P

**Comment by coelckers** [comment]
I think it's "./*" causing the problem. What this is really supposed to do is scan one level, not all levels.
Regardless, you shouldn't put your game data into the user's root folder - even in the best of cases this will scan a lot of garbage, because it's the place where everything you do lives in.

**Comment by CandiceJoy** [comment]
I've commented out my entire autoload section and it still scans my entire user directory, including all depths of all subtrees.  AddDirectory is recursive, which is why it scans the entire subtree.  Here's a quick stacktrace (keep in mind the line numbers may be SLIGHTLY off because I've put a Printf here and there for debugging this).

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8854890/208294648-b8f5e417-79a6-42c2-bd8b-b4555d31c3a2.png">

**Comment by coelckers** [comment]
Ok, here's what happens:

Build requires that the folder the main GPP is in is added to the file system. Further additions by previous source ports also require that all subdirectories be added to the file system as well.
So Raze will see your entire user folder as the game's directory and try to read it all.
That not only ends up in excessively long paths but ultimately eat all your RAM to create file system entries for tends or hundreds of thousands of files, and ultimately fail.

What you did here is a classic case of "Don't do that!" and not really fixable.
