### ISSUE TITLE
[BUG] Incorrect falling damage when jumping into certain sectors

### ISSUE THREAD

**Issue by EdHerdman** [ZDoom/Raze#805]
### Raze version

raze-x64-1.7pre-360-g9a1a90a73

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro Version 10.0.22621 Build 22621

### Relevant hardware info

AMD Ryzen 7 3700X, NVIDIA RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When jumping into certain sectors, the player character hovers above the ground for a few moments, lets out the 'falling' scream, and then impacts, losing health.

Examples include jumping into an item niche behind a red sign, in the platform area at the end of Seppuku Station. Another is the sector holding the crusher trap in Master Leep's temple. In both cases I measured 13 health points and 20 armor points lost.

Just for fun, there are a couple ways to avoid this falling damage in Master Leep's Temple. One is to walk up against the raised platform of the crusher trap and then just tap jump - sometimes Lo Wang will mantle up on the new sector instead of jumping. After you've disabled the crusher trap, you can also jump into the opening of the revealed secret and then walk freely onto the crusher trap's platform sector.

### Provide a Log

![ShadowWarrior_0006](https://user-images.githubusercontent.com/96923667/208343322-ea9efe9c-f809-4ebc-9d9e-d0d6cafe67fd.png)
![ShadowWarrior_0007](https://user-images.githubusercontent.com/96923667/208343325-cc1e6bfb-5999-4ffd-b440-7f6d4ab612db.png)
![ShadowWarrior_0001](https://user-images.githubusercontent.com/96923667/208343502-5f855c31-f9dd-4979-b72e-b99fdd2da7f7.png)
![ShadowWarrior_0002](https://user-images.githubusercontent.com/96923667/208343503-67cd13f1-5990-44c7-b0d7-1efdee8d2205.png)

**Comment by mjr4077au** [comment]
Could you please give provide some saves at each of these spots so I can test and review? Alternatively, the output displayed on your screen from `stat coord` in the console would do file also.

**Comment by EdHerdman** [comment]
Sorry for the late response. Here are saves for both locations.
[ShadowWarrior.ShadowWarrior.zip](https://github.com/ZDoom/Raze/files/10256079/ShadowWarrior.ShadowWarrior.zip)

**Comment by EdHerdman** [comment]
I forgot to pick up armor, which may be helpful for calculating the fall damage. So here's an alternate save for Seppuku Station.
[ShadowWarrior.ShadowWarrior.zip](https://github.com/ZDoom/Raze/files/10256093/ShadowWarrior.ShadowWarrior.zip)

**Comment by mjr4077au** [comment]
I'm sorry man but these saves are toast now with the recent pushes to master 😢. Can you see/confirm whether these spots are right now that 5f1581be9dee332a63c6f2b87a15b67fad21d01b is in?

**Comment by EdHerdman** [comment]
I'll need to build from source, yeah? I don't see a new auto build to play with yet. I did choose these spots to be easy to get to - for $whirl you just load the map, wait until the end of the boat ride, and then swim back to the start point and dive down looking for that underwater opening.

**Comment by EdHerdman** [comment]
OK, testing done: $bullet is fine, $whirl is good, $garden's moving platforms (with the golden dragons on top) test well.

$boat is almost perfect, although I notice that the player character cannot pick up the underwater gold key if you are hugging the floor of the underwater area. Should I file a new issue for that one? Here is a save showing this - try moving forward to pick up the key and then moving up and down:
[ShadowWarrior.ShadowWarrior.zip](https://github.com/ZDoom/Raze/files/10294246/ShadowWarrior.ShadowWarrior.zip)

**Comment by mjr4077au** [comment]
I'd appreciate a new issue if that's alright with you? This issue is different from the others. I know where it is but I need to run some numbers and can't just at the moment with Christmas and whatnot.
