### ISSUE TITLE
[BUG] Some sectors hurt to stand in, even if they should not hurt you

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#807]
### Raze version

master c7e25726c1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There are some sectors that hurt you as you stand in them, even if they should not. For example, the sky sectors on the second floor of the space station in E2L1, or any lava floor in Redneck Rampage: Rides Again.

[Here's a saved game from Duke Nukem 3D E2L1](https://github.com/ZDoom/Raze/files/10273580/floor.of.hurt.zip)
[And from the second level of Redneck Rampage: Rides Again](https://github.com/ZDoom/Raze/files/10273584/canyon.of.hurt.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load one of the saved games.
2. If RRRA, jump over the canyon to the secret area.
3. If Duke, walk out into the main area where the ceiling above is "glass".

**Comment by Talon1024** [comment]
Found two more in RRRA:
- The mud/feces ground, which now slows you down AND hurts you every tic
- The night sky at the start of "El Peso, Again" (E1L6)

**Comment by mjr4077au** [comment]
Bisected back to 4a306a21dcdd231c564e8f694be5a27b58c4b37f. We'll get it fixed soon.

**Comment by coelckers** [comment]
fixed in ff33dd7188e2766196b4e0209dc1641425cd39e8
