### ISSUE TITLE
[BUG] SW: swtrix

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#810]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11

### Relevant hardware info

11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz with RTX 3080

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

it doesnt work
the command swtrix doesnt work
you cannot shoot bunnies out of your rocket launcher

### Steps to reproduce the behaviour.

Explain how to reproduce
1. type swtrix
2. cry
3. cry some more

### Your configuration

```ini
happens even with default config :[
```

### Provide a Log

nothing unusual in log

**Comment by mjr4077au** [comment]
For now, please use `sw_bunnyrockets` via the console to enable bunny mode. Not sure why or how the original command got lost but we'll look at adding it back in.

The cheat `winpachinko` is also missing, but it's available as a CVAR as well (`Pachinko_Win_Cheat`).
