### ISSUE TITLE
[BUG] Some particles/projectiles will get stuck on level geometry (especially slopes)

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#811]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

None

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

yeah

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some particles/projectiles will get stuck on level geometry (especially slopes) and will therefore never disappear. I have seen this happen in DOS SW as well, but only with explosion fireballs and it happens nowhere near as often as it happens in Raze. Attached is a screenshot of it happening with the van crash in first level. It happens very often there and you should be able to reproduce.

![ShadowWarrior_0060](https://user-images.githubusercontent.com/89247988/208976987-f848cf0b-7c73-4fcc-8be2-5f926aa69f5c.png)

I am making the assumption that this is not a SW-specific bug.

I am unsure whether or not the fire whooshing sounds getting stuck and not disappearing after shadow ninja attacks is related to this.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. go to level 1
2. wait for van to crash
3. examine the slope on the back of the blue car

### Your configuration

```ini
happens even with default config
```

### Provide a Log

nothing unusual in log

**Comment by mjr4077au** [comment]
Bisected back to 4b25400e40c169e8b2235d59366bbf3b745b5762. Save from this commit attached. [save0009.dsave.remove.zip](https://github.com/ZDoom/Raze/files/10358853/save0009.dsave.remove.zip)

**Comment by coelckers** [comment]
fixed in ae6af08cf16004778b6eb391853be7b0e1e17312
