### ISSUE TITLE
Shadow Warrior, opening certain doors instakills you

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/Raze#816]
Win10-64, Raze 1.6.1, save file attached from Twin Dragon.

Load the save and press action to open the door, it'll instakill you.  

Also if you keep pressing action when prompted, the game falls into an infinite loop, trapped between respawn and instakill by the same door.

[Door Instakill.zip](https://github.com/ZDoom/Raze/files/10292646/Door.Instakill.zip)

**Comment by EdHerdman** [comment]
If you run into the death loop, try pressing "back" to backpedal out of the way. Tap immediately on loading the game. It's tricky.

I confirmed the instant kill door behavior doesn't happen in Shadow Warrior Classic Redux or Shadow Warrior 1.2 via DOSbox (part of the same release).

Many SW doors are deadly in Raze if you stand up against them. Lockers in the foreman's office in Zilla Construction, doors in $boat, the door to the Koi pool in $bullet when opened from the inside - there's many other places where you can do this.

**Comment by mjr4077au** [comment]
> the door to the Koi pool in $bullet when opened from the inside

I just tried this one as a quick test, I could get the left door to injure me but neither door flat-out killed me. What's the most sure-fire door to instakill me? It's likely the one cause for them all but will require a consistent test point.

**Comment by EdHerdman** [comment]
Yeah, the koi pond one is a bit random. Home Sweet Home, the first map of Twin Dragons, has a door off to the right once you enter the house proper. I'll try to make an up-to-date save for it, or another door I find.

**Comment by mjr4077au** [comment]
Coordinates on the map will also work, since saves can become useless when I'm going back through the changes. You can get coordinates by enabling `stat coord` in the console, will show like this:

![image](https://user-images.githubusercontent.com/48643140/209901801-38dbf017-a7d0-49bc-83fd-0f3506634042.png)

**Comment by EdHerdman** [comment]
Here's a save for Raze #3850 dcd0e62, plus screenshot with coordinates.
[ShadowWarrior.TwinDragon.zip](https://github.com/ZDoom/Raze/files/10317507/ShadowWarrior.TwinDragon.zip)
![ShadowWarrior_0010](https://user-images.githubusercontent.com/96923667/209901956-b3c339cb-edda-42ed-8bc9-cb8e9ad7bc18.png)

**Comment by mjr4077au** [comment]
Thanks mate, I see the issue now. It's not so much that the doors are sure-fire insta-killing you, its that they're dealing damage when they shouldn't be and if your health is low enough, it'll kill you.

By the way, I should have mentioned but anytime you're wanting to warp to those coordinates in a map, the syntax at the console is `warptocoords X Y Z` (`warptocoords -451.9375 -223.75 32`).

**Comment by mjr4077au** [comment]
@EdHerdman do you mind testing the 1.6.1 released build (https://github.com/ZDoom/Raze/releases). The issues seem very recent, just wanted to confirm whether the release is operating to your expectations?

**Comment by mjr4077au** [comment]
Phew, what a nightmare! Some ~2000 commits ago this oversight occurred. Please let us know if there's any further issues.
