### ISSUE TITLE
[BUG]: SW: Texture issues on sector objects.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#818]
Easiest observed in Seppuku Station (first level) after the bus crashes into the car:

![image](https://user-images.githubusercontent.com/48643140/209300658-c49a3c78-f7fa-4437-9535-910b769487cc.png)

**Comment by mjr4077au** [comment]
This one originates back to 837e4d1438dde19366d7ece8eb4bbd9c79ac0f92. Reverting the changes in `wallmove.cpp` removes the issue. I'm wondering whether `DSWActor::texparam` was already used elsewhere before it became the holder for `SP_TAG5()`?

**Comment by coelckers** [comment]
This one was rather simple: that rock texture is tilenum 0, but this particular controller type considers that as a 'no change' indicator.
