### ISSUE TITLE
[BUG] Underwater pickups trigger at wrong height

### ISSUE THREAD

**Issue by EdHerdman** [ZDoom/Raze#822]
### Raze version

raze-x64-1.7pre-401-gadc2396f3

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro Version 10.0.22621 Build 22621

### Relevant hardware info

AMD Ryzen 7 3700X, NVIDIA RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Shadow Warrior's map $boat, part of the mandatory level progression includes entering a fish market and triggering a switch to raise an underwater gate. Once in the water, you have a short period of time to grab the Gold Key and an optional Railgun weapon pickup.

Currently, the player character can't pick up these weapons while at the bottom of this underwater area. To successfully pick them up you must swim upwards slightly. Here is a savestate set up looking directly at both items for testing.

[ShadowWarrior.ShadowWarrior.zip](https://github.com/ZDoom/Raze/files/10299514/ShadowWarrior.ShadowWarrior.zip)

Other thoughts: In some recent-ish build (I haven't found which it was) it was possible to get stuck on at least the bottom of the Koi Pond in $bullet, accessible after the first key door in the game. This is not a problem in current versions. There also may be some weirdness with underwater enemy hit boxes going on; I'm not sure of it yet.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. enter map $boat, go through level or use "all items" console cheat
2. enter locked fish market door, trigger switch, dive underwater (optional: use god cheat and kill enemies for convenience)
3. key cannot be picked up when you are swimming on the bottom, only when you swim higher

**Comment by mjr4077au** [comment]
Thank you, sir. I've identified the issue and working on a fix. A bit held up with Christmas as you can understand but appreciate you opening the new issue.

**Comment by mjr4077au** [comment]
Shoud be fixed here if you wish to test a CI build: https://github.com/ZDoom/Raze/actions/runs/3775891302. Only very limited testing from my work laptop in bed.

**Comment by EdHerdman** [comment]
It works, including for the existing saves. Thanks!

**Comment by mjr4077au** [comment]
You're most welcome, thanks for testing 🤘
