### ISSUE TITLE
[BUG] 1.6.1 Severe graphic issues on Mac apple silicon

### ISSUE THREAD

**Issue by lostless** [ZDoom/Raze#825]
### Raze version

1.6.1 mac

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

13.1

### Have you checked that no other similar issue already exists?

- [ ] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Raze version 1.6.1. All games and all renderers (vulcan/open GL) have severe graphic issues on Mac OS on apple silicon M1Pro.  Did not check intel.  but Walls and sectors just disappear.  Games are unplayable.  Had to revert back to 1.5
<img width="1728" alt="Screenshot 2022-12-27 at 8 20 54 PM" src="https://user-images.githubusercontent.com/4473565/209757454-89681bae-5509-42f8-a3f8-778f79980f89.png">

### Steps to reproduce the behaviour.

Just start any games

### Your configuration

```ini
Default.  Ive erased all custom ini files.
```

**Comment by madame-rachelle** [comment]
This issue is the same as this issue: https://github.com/ZDoom/zdoom-macos-deps/issues/54

Please try the linked build and let us know if you have better luck with it. (Was compiled with an older version of MoltenVK - 1.1.x) - Sorry about it being a Discord link - not able to attach it directly to this message via Github.

https://cdn.discordapp.com/attachments/384932761984696321/1057527616845926520/Raze_v1.6.1.dmg

**Comment by lostless** [comment]
that build does not fix the issue.  I don't think it's a MoltenVK issue, because it's also happening when using Open GL.

**Comment by lostless** [comment]
Update.  Running through rosetta, the issue goes away.

**Comment by CandiceJoy** [comment]
I wonder if arm windows has the same issue...

**Comment by madame-rachelle** [comment]
Likely does, the problem exists on Linux ARM too from what I understand. Me and mjr are looking into this presently.

**Comment by madame-rachelle** [comment]
@lostless Try this build: https://cdn.discordapp.com/attachments/384932761984696321/1057558072517738568/Raze_1.7pre-402-g6b8bdcc44.dmg

The problem should be fixed in this one.

**Comment by CandiceJoy** [comment]
> @lostless Try this build: https://cdn.discordapp.com/attachments/384932761984696321/1057558072517738568/Raze_1.7pre-402-g6b8bdcc44.dmg
> 
> The problem should be fixed in this one.

Amazing cutie!  <333

**Comment by lostless** [comment]
Testes, problem is fixed
