### ISSUE TITLE
[BUG]: Duke (WT): Commentary sprites won't activate with use key.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#828]
This seems to have been an issue for some time. The current situation is that players cannot listen to the commentary at all.

**Comment by mjr4077au** [comment]
This is still broken in the current state of master, but not in the released build.

Menu option to enable/disable commentary appears ineffective, the commentary sprites are always present no matter what the CVAR is set to. When enabled, the user still cannot hit "use" on it to listen to the commentary.

**Comment by coelckers** [comment]
fixed in d5859db4f15aa1f692a339bfced9da11d41663ba
