### ISSUE TITLE
[BUG] Cannot break through clouds on $volcano (Stone Rain)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#832]
### Raze version

master ad0860f4bf

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I cannot go to the upper half of the level through the layer of clouds in $volcano (Stone Rain).

[Here's a saved game](https://github.com/ZDoom/Raze/files/10322853/solid.clouds.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or start a new game on $volcano
2. Try to go through the layer of clouds
3. It is not possible

**Comment by EdHerdman** [comment]
Reproduced on Windows 11 with [raze-x64-1.7pre-439-gad0860f4b.7z](https://devbuilds.drdteam.org/raze/raze-x64-1.7pre-439-gad0860f4b.7z). Can't get through those clouds here either. IIRC I have run into this bug in another release before - maybe an old version of SW Classic Redux or VoidSW.

**Comment by mjr4077au** [comment]
Fixed now, and a little bonus in f431d51c2f74b22aa9e714e90a620ccfc8a3d9da. I didn't realise how rough warping was, found there was no proper correction to the player's interpolated backup. Warping between sectors is now properly smooth 🙂
