### ISSUE TITLE
[BUG] [Blood+Bloodlines] this sector-over-sector portal is glitched

### ISSUE THREAD

**Issue by axredneck** [ZDoom/Raze#833]
### Raze version

Commit ad0860f4bf57f5ee4ed81e38c20e79c0fa3041b3

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Player gets stuck inside Build Engine Backstage™ when i try to enter the ship (see attached save).
Though i'm unsure whether it's a bug of Raze or the map itself, i didn't try it on other ports.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Blood with [this mod](https://www.moddb.com/mods/bloodlines-out-of-the-grave-edition/downloads/bloodlines-out-of-the-grave-edition-version-15)
2. Load this save: [save0002.dsave.zip](https://github.com/ZDoom/Raze/files/10326499/save0002.dsave.zip) (remove .zip from file name)
3. Jump into this doorway in front of you

### Your configuration

```ini
https://gist.github.com/axredneck/4c50ef66e3e111d7a03bccae0edbaebd
(Attachments don't work for this field, please fix!)
```

### Provide a Log

Nothing interesting here:
[raze.log](https://github.com/ZDoom/Raze/files/10326505/raze.log)

**Comment by axredneck** [comment]
The same issue with this portal (in the same mod):
[save0000.dsave.zip](https://github.com/ZDoom/Raze/files/10333769/save0000.dsave.zip)

**Comment by axredneck** [comment]
About other ports: BloodGDX doesn't seem to have this bug.

**Comment by mjr4077au** [comment]
Thanks mate, I'll be getting onto it and as many other bugs this week.
