### ISSUE TITLE
[BUG] Sky at end of $dozer not rendering properly

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#835]
### Raze version

master ad0860f4bf

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The skybox at the end of $dozer, where you see a preview of the next level through a portal, is not rendering properly.
![ShadowWarrior_0024](https://user-images.githubusercontent.com/6550500/210190218-adf2680e-5320-4b2e-bf43-24e83c0d56c7.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/10329821/screwy.sky.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play through $dozer (Zilla Construction) or load the saved game

**Comment by mjr4077au** [comment]
Do you know if it's right in GDX or VoidSW? As best as I can tell, the mapper never put a skytile in here. When you actually go to the area shown through the portal, there's nothing:

![image](https://user-images.githubusercontent.com/48643140/210194867-4b1c3c0d-08e1-4da3-9f91-3341f6b2ecb8.png)

Polymost is even worse (from 1.1.1).

![image](https://user-images.githubusercontent.com/48643140/210194877-ea0051ff-5049-4589-b437-1e447bb9e9a0.png)

**Comment by Talon1024** [comment]
I thought it was the same sky as the beginning of $shrine (Master Leep's Temple), but it looks like you're right.

I just took these screenshots in DOSBox to confirm:
![setup_000](https://user-images.githubusercontent.com/6550500/210196220-216b6ce8-25cb-416f-90ed-90da25a87885.png)
![sw_000](https://user-images.githubusercontent.com/6550500/210196245-3c7ff4e6-a5c7-47b6-9bc5-6d6773f294cf.png)

**Comment by mjr4077au** [comment]
Thanks for checking that out! I might close this one off in that case, we do have some map fixes in the pk3 file but they're typically reserved for issues that affect gameplay.
