### ISSUE TITLE
Does Blood Fresh Supply or Power Slave Exhumed work with Raze?

### ISSUE THREAD

**Issue by sofakng** [ZDoom/Raze#836]
Does the Blood Fresh Supply and/or Power Slave Exhumed remakes from Nightdive Studios (KEX engine) work with Raze?

**Comment by mjr4077au** [comment]
Fresh Supply uses original DOS assets and therefore works fine. PowerSlave Exhumed is a port of the Saturn version of the game and is a completely different engine. This is the Build version of the game and is fully supported: https://www.gog.com/en/game/powerslave

If there's any other general questions such as this, they're best asked on our forum: https://forum.zdoom.org/viewforum.php?f=347
