### ISSUE TITLE
[BUG] [Exhumed] Movable platform slides under the character.

### ISSUE THREAD

**Issue by eclenaeu** [ZDoom/Raze#838]
### Raze version

Raze 1.6.1

### Which game are you running with Raze?

Exhumed/Powerslave

### A clear and concise description of what the bug is.

The character cannot stand on top of any moving platform without the platform "sliding" underneath him; If he stands still on the platform, without moving in the direction it is going, the platform moves forward and he falls.

**Comment by mjr4077au** [comment]
Are you able to please provide a save at the particular spot so there's no confusion?

**Comment by eclenaeu** [comment]
> Are you able to please provide a save at the particular spot so there's no confusion?

I can, but I warn you, this happens on any mobile platform, even on the training map.

[save0001.zip](https://github.com/ZDoom/Raze/files/10355662/save0001.zip)

**Comment by mjr4077au** [comment]
Thanks mate, the training map is a good, reliable spot to get to.

Originates from 54a55b3d0966405533eb8aca5bd7bbd68e33af6d but I cannot see any obvious reason as to why. Might get a 2nd pair of eyes on it later on.

Coordinates: 1661 256 450. Best to toggle noclip on/off to update the sector properly after warping.

**Comment by eclenaeu** [comment]
> Coordinates: 1661 256 450. Best to toggle noclip on/off to update the sector properly after warping.

excuse my lack of knowledge, how should i use these coordinates?, is this really a bug?

**Comment by mjr4077au** [comment]
Sorry mate I should have clarified, its information for Graf to take a quick look when he has the time.

**Comment by coelckers** [comment]
fixed in 2e35d6a6a8bea65c6f98a59f7a476966eba35380
