### ISSUE TITLE
[BUG] SW: Boat issues in $boat since lerping floors in 22d6e3f2f6b7370296bd7a1cf653118001bd24dd

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#839]
Reverting the above commit fixes the boats, but I'm not sure what lerping the floor/ceiling here was to achieve so didn't want to commit it.

https://user-images.githubusercontent.com/48643140/210761902-dd7df41b-477e-44a3-bb86-109bbea24965.mp4

**Comment by coelckers** [comment]
fixed in 32ce8a97bf3892729d6b4c5af929c8b5255c0d3e

Not surpringly it fell victim to the poor interpolation handling in Build in general and for the SOs in particular.
