### ISSUE TITLE
[Feature] Blood: Make dragging and dropping of mods with a batch file in the root work

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#840]
Using [this mod](https://www.moddb.com/mods/bloodlines-out-of-the-grave-edition/downloads/bloodlines-out-of-the-grave-edition-version-15) as an example, the only way for it to work via drag and drop is to remove the batch file from the root of the zip.

This isn't intuitive for end users, it should just work.

**Comment by coelckers** [comment]
added in cfef8c8a711a810606b4948edb97e74905f70cba
