### ISSUE TITLE
[BUG] Duke: Access key sound plays immediately, before access card is swiped.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#841]
This issue is in master but _not_ the 1.6 branch.

https://user-images.githubusercontent.com/48643140/211143821-d6270d78-a54d-4a42-98ef-c03a6f8f1084.mp4

**Comment by coelckers** [comment]
fixed in 1e3a2855348f2118a37478a0f4f8eeda908d24b6
