### ISSUE TITLE
[Feature] Last used weapon command

### ISSUE THREAD

**Issue by eclenaeu** [ZDoom/Raze#848]
### Raze version

Raze 1.6.2

### Which game are you running with Raze?

All

### Is your feature request related to a problem? Please describe.

I don't know how other people play, but whenever I start an FPS style game, I use a light weapon and change settings to leave a hotkey for a heavy or explosive weapon (a grenade or similar), to disperse groups of enemies or a stronger enemy, switching to the light weapon when possible to save ammo, using a command that quickly returns to the light weapon, this hotkey is Last used weapon, however, Raze does not have such a command, which bothers me makes having to use the previous weapon command, which is not so fast, or looking at the keyboard to locate the weapon key I want, but for those who play FPS games, taking their eyes off the screen or taking time to return shots, it can be the difference between winning or losing the fight.

### Describe the solution you'd like

the Last used weapon command would memorize the weapon used (remembering that, despite the term "light weapon", I could be talking about any gun you still have), allowing quick switching in combat, without taking your eyes off the screen, the command, despite not being original to the games supported by Raze, but it is present in other source ports such as eduke32, TFE and BuildGDX, however, I consider that Raze has superior performance and I believe that it would make the source port more complete.

**Comment by coelckers** [comment]
This is something none of the games properly tracks, it's also a really exotic edge case for which I don't see much to be gained from investing the needed work.
