### ISSUE TITLE
[BUG] Duke always auto-aims at women, regardless of autoaim setting

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#849]
### Raze version

master b7799a5a3c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Duke Nukem will always auto-aim at certain things, like the women held in pods, regardless of the autoaim setting. So even if you're looking at the floor, the auto-aim will make Duke aim at the woman.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10375649/woman.autoaim.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Look at the floor if you're not doing so already
3. Open fire
4. The shot should not hit the woman

### Your configuration

```ini
cl_autoaim=0
```

**Comment by Talon1024** [comment]
This bug only seems to affect the pistol.

**Comment by coelckers** [comment]
fixed in 8001c4041fa9d7a0275b26e5027fbc9cac9558e7
