### ISSUE TITLE
[BUG] Some locks do not show the "access" frame

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#850]
### Raze version

master b7799a5a3c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some of the access card locks do not show the "access" frame when you unlock them.

[Here's a saved game in front of a lock that doesn't work properly on E2L3 "Warp Factor"](https://github.com/ZDoom/Raze/files/10375711/door.lock.zip).
[And another saved game in front of a lock that DOES work properly on E1L2 "Red Light District"](https://github.com/ZDoom/Raze/files/10375716/good.lock.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load either of the saved games
2. Unlock the doors

**Comment by Talon1024** [comment]
I think it's only tile 170 and 171 which are broken.

**Comment by coelckers** [comment]
fixed in 59820f9fed42e8f2d580cb0df1a07c5b9e337afe
