### ISSUE TITLE
[BUG] Destroying a fire extinguisher causes an assertion failure

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#851]
### Raze version

master b7799a5a3c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you destroy a fire extinguisher, it causes an assertion failure (See log below).

[Here's a saved game in front of a fire extinguisher on E1L1](https://github.com/ZDoom/Raze/files/10375890/fire.extinguisher.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a map with fire extinguishers, or load the saved game
2. Destroy the fire extinguisher
3. Assertion failure

### Provide a Log

```raze: ../source/core/actorlist.cpp:175: void InsertActorStat(DCoreActor*, int, bool): Assertion `stat >= 0 && stat <= MAXSTATUS' failed.```

**Comment by coelckers** [comment]
fixed in b991af2dbcc7cb7a4d9200e3fc1aeabb81541f1d
