### ISSUE TITLE
[BUG] Boss rockets' firing position is too low

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#852]
### Raze version

master b991af2dbc

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The bosses' rockets are fired too low. IIRC the rocket firing position was higher in the original game.

![Duke_0038](https://user-images.githubusercontent.com/6550500/211633301-4033a480-94cd-4793-85a9-67b9a9f7f7dd.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/10385756/e2.boss.zip)

This is also a problem with the E3 boss (Cycloid Emperor), except the E3 boss rocket firing position is too high.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E2L9 or load the saved game
2. Start fighting the boss
3. Notice his rocket firing position is too low

**Comment by coelckers** [comment]
fixed in 97f14c0e0ef6d6e67a969fb7a958c7b71d799ef7
