### ISSUE TITLE
[Feature] Duke: Make recentering pitch on hard landing optional

### ISSUE THREAD

**Issue by tmyqlfpir** [ZDoom/Raze#853]
### Raze version

Raze 1.6.2

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 7

### Is your feature request related to a problem? Please describe.

For Duke 3D, when you drop from a height taller than your jump the view will recenter the pitch, and forcefully halt your input until it is completed. This feels like a hold over for when players predominately using keyboard only.

### Describe the solution you'd like

Please add a recenter view on drop CVAR to this `if` statement here https://github.com/ZDoom/Raze/blob/9a27cf025f3676ed815dbf944a561ee36a0b8d4e/source/games/duke/src/player_d.cpp#L3054

**Comment by mjr4077au** [comment]
We can do something for that, it's been asked once or twice in the past. A change needs to be made there to accommodate it but it's not the place for the CVAR itself as it needs to come through the network layer so it's safe if we get MP going.

**Comment by mjr4077au** [comment]
@tmyqlfpir just wanted to clarify what you wanted to see happen here? Options are:

1. No returning to center upon hard landing:

https://user-images.githubusercontent.com/48643140/226142995-5b98b4b5-3551-4e4f-b0b9-82511ee73919.mp4

2. No hard landing at all:

https://user-images.githubusercontent.com/48643140/226143061-fdfe41ca-87e8-41ee-b2b5-7831fb0c4a15.mp4

3. Hard landing doesn't lock the input, therefore moving the mouse cancels the return to center action.

https://user-images.githubusercontent.com/48643140/226143224-510a133f-54ae-43af-8e45-5b6a478a8527.mp4

Whatever's chosen, it'll be behind a CVAR for a user to pick. I'd suggest the last option, everything else doesn't feel right.

**Comment by mjr4077au** [comment]
@tmyqlfpir do you mind testing with `cl_dukelockpitchreturn` set to false and letting me know if its satisfactory? If so, I'll add it to the menu and close off the issue.

**Comment by mjr4077au** [comment]
All three controls have been added. They will need to be reworked when it comes time for demos/MP but today is not that day.

`cl_dukepitchmode` is a CVAR bitfield with the following bits:
```
enum
{
	kDukePitchLockReturn = 1,
	kDukePitchHardLanding = 2,
	kDukePitchLandingRecenter = 4,
};
```

When it's masked as 7, all default options are enabled.

You can directly control the CVAR bitmask, or you can use these individual CVAR bools to control each option:

- `cl_dukepitchlockreturn`
- `cl_dukepitchhardlanding`
- `cl_dukepitchlandingrecenter`

These have also been updated to the menu but have no language strings defined yet, they'll come in a language update prior to the next release.
