### ISSUE TITLE
Review level intermission cutscene text length for translations

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#856]
Portugese and Spanish translations overlap the time. It'd be worth checking each game out.

My suggestion is to go left as much as possible, within 10% of the left screen boundary, then go further right when if it's over the top of Duke. 

![image-1](https://user-images.githubusercontent.com/48643140/212461363-91c688de-e956-4543-8bed-7d47fb22803b.png)

**Comment by CandiceJoy** [comment]
Prior discussion was here: https://discord.com/channels/268086704961748992/1063640756692205609

**Comment by coelckers** [comment]
fixed in d067b23917cf81ddc6ff5508276d256a6d57f520 and for RR in 5e7f90562c9f6ad7b5a4f5af12582e7b8e1db677
