### ISSUE TITLE
[BUG] SW: Certain action sounds do not follow the player character

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#857]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The easiest example of this is just swinging your sword while strafing, its very noticeable when strafing left and right because it will be very loud in one direction and not the other. Player voices seem normal though. I cannot get the same to happen in DOS, as the sounds seem to stay with the player position in vanilla. It may also be possible that DOS just plays certain sounds in mono, it is hard to tell. But even if that is what happens in DOS, I think it would make more sense for punching/throwing/swinging/movement sounds to track the player.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. strafe left and right
2. swing sword or fists
3. listen

**Comment by coelckers** [comment]
Damn, I thought I got them all. The logic here is truly screwed - far too many sound are explicitly started not to follow their owner.

**Comment by coelckers** [comment]
I hope it is fixed now. To fix another problem I unlinked non-following sounds from their source actor - for the player this must not happen, of course as it also serves as the listener.
