### ISSUE TITLE
[BUG] Cacti do not explode properly

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#858]
### Raze version

master 8001c4041f

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The cacti do not explode properly. IIRC it should be possible to destroy them by tossing a pipebomb at them and detonating that pipebomb. However, I had to use the rocket launcher to destroy the cacti, and even then, I could only destroy one of them at a time.

Also, the cactus debris does not move. It should be thrown out in random directions.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10418554/cacti.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Throw a pipebomb at the cacti and detonate it
2. The cacti should explode, and the debris should fly out in all directions

**Comment by coelckers** [comment]
fixed in 13c9e9916b6889cf7b467036c010d0d560bca15e
