### ISSUE TITLE
[BUG] Trying to display clip amounts causes assertion failure

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#861]
### Raze version

Raze 1.7pre-519-g 3ab1ae5f7a

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Exhumed, if you try to show the number of remaining bullets in the clip on the fullscreen HUD, the game exits with an assertion failure (see log below)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Turn on "Show clip amount in fullscreen HUD"
2. Start a new game
3. Open up the fullscreen HUD
4. Assertion failure

### Your configuration

```ini
cl_showmagamt=true
```

### Provide a Log

```raze: ../source/common/scripting/vm/vm.h:193: void VMReturn::SetPointer(void*): Assertion `RegType == REGT_POINTER' failed.```

[And a GDB log with a backtrace](https://github.com/ZDoom/Raze/files/10439013/raze-gdb.log)

**Comment by coelckers** [comment]
fixed in 33f0d229fa7f93b1cff1338b5a260e7fb03c7e9a
