### ISSUE TITLE
[BUG] Life seed secret on E3M6 not appearing

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#862]
### Raze version

1.7pre-519-g 3ab1ae5f7a

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There should be a life seed secret on E3M6. However, it doesn't seem to spawn in Raze.
![Blood_0027](https://user-images.githubusercontent.com/6550500/213061787-f810620c-84d0-4aab-88e3-774eec37a807.png)
[Here's a saved game](https://github.com/ZDoom/Raze/files/10441135/there.should.be.a.life.seed.here.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start playing E3M6, either on a continuous playthrough or using the `map` CCMD
2. Go to the area shown in the screenshot and open the pillars
3. There should be a secret life seed on (I think) the pillar shown in the screenshot

**Comment by coelckers** [comment]
fixed in 9cc7f90410c773049d61406482903237dbbe4695
