### ISSUE TITLE
[BUG] Blood - Shotgun / Tommy gun shells disappear 

### ISSUE THREAD

**Issue by Dzierzan** [ZDoom/Raze#863]
### Raze version

1.7pre-522-gacfca3fbd

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Just shoot with Tommy Gun or Sawed-Off. You'll notice that shells are spawned, but they also despawn in the very same moment. I was testing that with pre 1.7 build, however it also happened with build 1.6.2.

**Comment by coelckers** [comment]
fixed in 19a58ddeb0e3277c8bf58478247b78e9b76af4bd
