### ISSUE TITLE
[BUG] Shadow Warrior - Extra sound during Katana swing

### ISSUE THREAD

**Issue by Skumball** [ZDoom/Raze#866]
### Raze version

1.6.2

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Build 19044

### Relevant hardware info

AMD 3970x CPU, AMD RX 5700 GPU, Asus Essence STX II Sound Card

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There is a faint additional background noise during a swing of the Katana. It sounds like GPU coil whine but it's coming from the speakers. It seems to play at various random pitches on each swing. No other weapon exhibits this and the Katana swipe noise in the menu does the same thing.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Attack using the Katana (starting) weapon.

### Your configuration

```ini
All sound (snd) -related lines:

Line  193: snd_aldevice=Default
Line  194: snd_alresampler=Default
Line  195: snd_ambience=true
Line  196: snd_backend=openal
Line  197: snd_buffersize=0
Line  198: snd_channels=128
Line  199: snd_efx=true
Line  200: snd_enabled=true
Line  201: snd_extendedlookup=false
Line  202: snd_hrtf=-1
Line  203: snd_mastervolume=0.19687500596046448
Line  204: snd_mididevice=-5
Line  205: snd_midiprecache=false
Line  206: snd_musicvolume=0.5
Line  207: snd_reverb=true
Line  208: snd_samplerate=0
Line  209: snd_sfxvolume=1
Line  210: snd_streambuffersize=64
Line  211: snd_tryformats=true
Line  212: snd_waterreverb=true
Line  441: snd_menuvolume=0.6000000238418579
Line  442: snd_pitched=false
Line  443: snd_speech=1
Line  621: snd_menuvolume=0.6000000238418579
Line  622: snd_pitched=false
Line  623: snd_speech=1
Line  884: snd_menuvolume=0.6000000238418579
Line  885: snd_pitched=false
Line  886: snd_speech=1
Line 1123: snd_menuvolume=0.6000000238418579
Line 1124: snd_pitched=false
Line 1125: snd_speech=1
Line 1350: snd_menuvolume=0.6000000238418579
Line 1351: snd_pitched=false
Line 1352: snd_speech=1
Line 1588: snd_menuvolume=0.6000000238418579
Line 1589: snd_pitched=false
Line 1590: snd_speech=1
```

### Provide a Log

Log started: 2023-01-21 08:36:50
OS: Windows 10 (NT 10.0) Build 19044

**Comment by coelckers** [comment]
It is part of the sound that is being played.
Whether it is intentional or just a poor recording I cannot say.

**Comment by Skumball** [comment]
Sorry about that, first time noticing it with Raze coincidentally :) Also managed to hear it in WangGDX so I agree it can be closed. Thanks.
