### ISSUE TITLE
[BUG] Unbreakable barrells

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#867]
### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

in E4M2 (Duke Burger) there are some barrells that you can't break anymore. See screenshots below:

![Duke_0012](https://user-images.githubusercontent.com/71838912/214948474-f6fd288e-c7d1-4202-9d27-2d0dd655a48e.png)

![Duke_0015](https://user-images.githubusercontent.com/71838912/214948496-66e5c1e5-a6eb-42fe-9a94-95ac3581c0bc.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E4M2
2. Try to shoot the first barrell to the right

**Comment by coelckers** [comment]
You forgot to add a version. This should already be fixed, it came up a few weeks ago.

**Comment by Axldomi** [comment]
Sorry, my mistake, i was just using version 1.6.2. I shall use the latest devbuild in the meanwhile. 

Thx!
