### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheDwellerInDarkness** [ZDoom/Raze#868]
### Raze version

1.6.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G   2.70 GHz,  8.00 GB (7.39 GB usable), 64-bit operating system, x64-based processor

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While starting up Duke Nukem 3D: Atomic Edition (WT), I get the following warning in the startup box thing: "WARNING (game.con, line 3413) Expected an identifier, got a numeric literal 1". I'm uncertain why it occurs, but it only happens when running Duke 3D. 

A minor secondary issue is that the box where this warning shows up tends to freeze up temporarily when starting Duke 3D specifically, though only the first time after turning on or restarting my laptop. This also only happens with Duke 3D. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
https://file.io/ezLniHkHEwI0
```

### Provide a Log

https://file.io/pEL2yA2T6sAs

**Comment by coelckers** [comment]
This is absolutely normal behavior. The script contains a small but benign error which the original CON parser did not detect.
