### ISSUE TITLE
[BUG] Misplaced railing on E2M5

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#869]
### Raze version

Raze 1.7pre-542-gdce0afe499

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The railing on E2M5 (The Haunting) on the balcony beside the room where the eye key is is misplaced.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10533144/misplaced.railing.2.zip)

And a screenshot from DOSBox, showing the correct position of the railings:
![blood_001](https://user-images.githubusercontent.com/6550500/215405639-d86f0b0d-a622-4c50-84b9-96ecadc70435.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a game on E2M5
2. Go to the place shown in the screenshot

**Comment by Talon1024** [comment]
I think it may have something to do with the [Blood Voxel pack](https://www.moddb.com/mods/blood-voxel-pack), since I don't seem to get this issue if I'm not using it.

**Comment by Talon1024** [comment]
Well, this is interesting...

https://user-images.githubusercontent.com/6550500/217364269-f0f57284-b1e3-494c-b8cd-b00be91cd754.mp4

**Comment by mjr4077au** [comment]
I think there's something with the maphacks parser that's not working. I think the angle of the voxel bins in Duke's E1L1 with the ERP isn't right either, but I haven't checked with another port for validation.
