### ISSUE TITLE
[BUG] E2L3 "Warp Factor" lift at start does not start automatically

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#870]
### Raze version

1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The lift at the start of E2L3 "Warp Factor" does not start automatically like it should.

This isn't game-breaking, thankfully, since the lift can still be activated manually.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E2L3, either on a continuous playthrough, or by entering `map e2l3` into the console.
2. Notice the lift does not start automatically.

**Comment by mjr4077au** [comment]
I've bisected this back to dd5834444e456680f420a4291b6b7a584cdbbb94 but there's no rhyme or reason as to why the change here has broken things. I'll keep looking.

**Comment by mjr4077au** [comment]
Solid report as always. This one was pretty damn nasty on account of sloppy original Duke code that did the wrong thing and built up everything else around that. I annotated the commit heavily with what was up here.
