### ISSUE TITLE
[BUG] Protozoid slimers won't stop eating

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#871]
### Raze version

1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It looks like protozoid slimers won't stop "eating" something once they have devoured it. Once something has been devoured, they try to devour said thing again.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10566336/slimer.eating.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Open the door in front of you
3. Observe the slimer "eating" again and again

**Comment by coelckers** [comment]
hopefully fixed in 77bcea409bad0b9f6a3d3d86d1cc09aca1aa34ef

It was a classic case of incomplete state checks that could leave the slimer in an undefined state, but the bug looks old, it wasn't something that got recently introduced.
