### ISSUE TITLE
[BUG] Enemies devoured by slimers become ghosts

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#872]
### Raze version

Raze 1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When an enemy is eaten by a slimer, they become a "ghost". They turn invisible, but then they can still attack you. The only way to get rid of them is to use explosives.

[Here's a saved game from before an enemy is eaten by a slimer](https://github.com/ZDoom/Raze/files/10576352/let.the.slimers.eat.the.pig.zip)

[And a saved game from an enemy being eaten by a slimer](https://github.com/ZDoom/Raze/files/10576355/imma.eat.you.up.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Let a slimer eat an enemy (tricky!)
2. Notice the enemy disappears, but they can still fire at you as if they are still alive
3. Use explosives to get rid of said enemy

**Comment by mjr4077au** [comment]
@Talon1024 I hope you've been well mate. Just to avoid a wild goose chase, is this something in 1.6 and newer, or do you know if its observable in 1.5 and older as well?

**Comment by Talon1024** [comment]
I'm perfectly fine.

I just did a quick test on E4L2, and this issue does not happen in 1.6.2.

**Comment by coelckers** [comment]
fixed in 792f977d46aa191a2a3359a9d235d96de7b0fa09

Duke should delete anything in  STAT_ACTOR with an x scale of 0 but it did not.
