### ISSUE TITLE
[BUG] Protector drone enemies do not work

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#875]
### Raze version

Raze 1.7pre-548-g 8052bc7e46

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The protector drone enemies do not work at all. Now, they are just static sprites.

[Here's a saved game on E4L1](https://github.com/ZDoom/Raze/files/10577574/protector.drone.zip)

[And another saved game on E4L2](https://github.com/ZDoom/Raze/files/10577573/protector.drone.2.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to any level that has the protector drone enemy on it
2. Encounter a protector drone
3. The enemy does not move around or attack you

**Comment by Talon1024** [comment]
The pig cop tanks don't seem to work either...

**Comment by mjr4077au** [comment]
Bisected back to 4328016963ff12157e169b867d75721fcdf5deb0. I believe the actor's `timetosleep` value may no longer be getting set properly.

**Comment by EdHerdman** [comment]
Since raze-x64-1.7pre-548-g8052bc7e4, I get the same behavior affecting most of the cast of Nuclear Winter. Most characters will fail to wake, including pig cops, all snowmen variants except the Assault Commander reskin, the elves. I tried the latest CI build ede52f2, doesn't help this yet.

**Comment by coelckers** [comment]
fixed in 6c77d1c39edf1495642ce7ae65b5f1343ce2ffdd
