### ISSUE TITLE
Blood - guns akimbo with shotgun carries to next level [BUGS] 

### ISSUE THREAD

**Issue by murderousmashedpotatos** [ZDoom/Raze#876]
### Raze version

Have tested bug on 1.7pre-542 and 1.6.2

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

10.0.19045 build 19045

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Everytime I complete a level with guns akimbo, the timer doesn't carry over, which isn't a big deal. The problem, is that when I use the shotguns, it carries over the fact that I have two guns. This causes an issue where I get one guns akimbo shot with the shotguns.

### Steps to reproduce the behaviour.

Either use cheats or play levels like thin ice where it is easy to carry the akimbo, end the level with dual shotguns, and voila.

**Comment by mjr4077au** [comment]
This one is also original behaviour. I can change it so akimbo doesn't carry over at all between levels but there's so many fanatics in the community who'd baulk at such a fix... Probably best to leave it.
