### ISSUE TITLE
Blood - Dynamite Underwater [BUG] 

### ISSUE THREAD

**Issue by murderousmashedpotatos** [ZDoom/Raze#878]
### Raze version

1.6.2 and pre1.7-542

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 home

### Relevant hardware info

Amd raedon integrated graphic

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Lighting a dynamite then going underwater before throwing it causes a lot of wack stuff, like dropping a second dynamite and then I can't throw the one still in my hand so it just explodes, and some random times it does no damage.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Light or get ready to throw tnt
2. Jump in water

**Comment by mjr4077au** [comment]
This appears to be original behaviour. We'll look at it in due course but its not high priority at the moment.

**Comment by mjr4077au** [comment]
Sorry, I tested this improperly. I'll look at it this week and see what's wrong.
