### ISSUE TITLE
Blood::HackseqCallback: Invalid target in calling actor in crystal lake[BUG] 

### ISSUE THREAD

**Issue by murderousmashedpotatos** [ZDoom/Raze#880]
### Raze version

1.6.2 and pre1.7-561

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 home

### Relevant hardware info

AMD Raedon

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the start of crystal lake, sometime within like a minute of normal play, I sometimes (inconsistent but it happens only on this level like every 5 or so plays), I get the error message mentioned in the title of this issue in the top left, no idea what it means was done.

### Steps to reproduce the behaviour.

I play crystal lake on well done?

**Comment by mjr4077au** [comment]
I don't believe there's anything to fix here. In the original game, this would have been an assertion (a stop error that only occurs in a debug build). We've changed it to print instead across all builds, but there's possible situations where this may be possible.

Assigning to Graf to see whether he thinks it requires investigation or not.

**Comment by coelckers** [comment]
This function never validated its target. In this case it would just have either accessed stale or invalid memory but wouldn't complain.
So the best option is to do a silent target validation instead of the noisy one.
