### ISSUE TITLE
[BUG] No games load, launcher fails with script error in log

### ISSUE THREAD

**Issue by EdHerdman** [ZDoom/Raze#885]
### Raze version

CI 09c8430 Visual Studio 2022 Release, and raze-x64-1.7pre-577-g09c8430e4

### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro 22H2 OS Build 22621.1194

### Relevant hardware info

AMD Ryzen 7 3700X, NVIDIA RTX 4080

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Both CI and DRD Team page builds of Raze fail to launch Duke Nukem 3D Atomic Edition or Shadow Warrior (and related games, such as Nuclear Winter), with the following message:

Script error, "raze.pk3:zscript/games/blood/bloodgame.zs" line 58:
Cannot convert Pointer<NativeStruct<BloodPlayer>> to Pointer<Type>
Script warning, "raze.pk3:zscript/games/duke/actors/flamethrowerflame.zs" line 129:
Accessing deprecated function checktype - deprecated since 4.9.0
Script warning, "raze.pk3:zscript/games/duke/actors/flamethrowerflame.zs" line 134:
Accessing deprecated function checktype - deprecated since 4.9.0
Script warning, "raze.pk3:zscript/games/duke/actors/flamethrowerflame.zs" line 184:
Accessing deprecated function checktype - deprecated since 4.9.0
Script warning, "raze.pk3:zscript/games/duke/actors/firefly.zs" line 24:
Accessing deprecated function checktype - deprecated since 4.9.0
Script warning, "raze.pk3:zscript/games/duke/actors/bowling.zs" line 43:
Accessing deprecated function checktype - deprecated since 4.9.0

Execution could not continue.

1 errors during script processing

**Comment by coelckers** [comment]
fixed in 6729c342af35482306a67a135e72fd8b0024af6e

Ignore the warnings for now, they are there as notification for incomplete code and will either be dealt with before a release or silenced.
