### ISSUE TITLE
[BUG] Incorrect item expiration alerts in Exhumed

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#886]
### Raze version

Raze 1.6.2

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 20.3

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the Scarab Amulet (invincibility) item is about to expire in *Exhumed*, the following message appears:

>TXT_EX_INVINCEX

Similarly, when the Unseen Eye (invisibility) item is about to expire, the following message appears:

>TXT_EX_INVISEX

For comparison, the expiration messages for Sobek Mask and Severed Slave Hand, respectively, appear as follows:

>Mask is about to expire

>Weapon power is about to expire

I assume that these messages are correct and that the ones for invincibility and invisibility are a mistake.

For your convenience, the attached save file (renamed from `save0000.dsave` to `save0000.zip` so that GitHub actually lets me attach it) is one in which I have the relevant items and enough magic to use either of them: [save0000.zip](https://github.com/ZDoom/Raze/files/10714818/save0000.zip)

Based on a `grep -rE "TXT_EX_.+EX"` of the repository, it looks like the problem with the invisibility and invincibility expiration messages is that strings used in `source/games/exhumed/src/player.cpp` do not match those found in `wadsrc/static/language.csv`:
* `player.cpp` uses `TXT_EX_INVISEX` but `language.csv` has `TXT_EX_INVISEXP`.
* `player.cpp` uses `TXT_EX_INVINCEX` but `language.csv` has `TXT_EX_INVINVCEX`.

Based on the spelling conventions for the item expiration alerts that are working correctly, I assume the `TXT_EX_INVISEXP` in `language.csv` is a mistake, and likewise `TXT_EX_INVINVCEX` just looks like a typo. So I would recommend the following change:
```diff
diff --git a/wadsrc/static/language.csv b/wadsrc/static/language.csv
index 76e6a1161..6eeb67ef4 100644
--- a/wadsrc/static/language.csv
+++ b/wadsrc/static/language.csv
@@ -2357,8 +2357,8 @@ Original,GLPREFMNU_ORIGINAL,,,,Původní,,,,,,,Original,Eredeti,,,,,Oryginalne,O
 You need the key for this door,TXT_EX_NEEDKEY,,,,K těmto dveřím potřebuješ klíč,Du brauchst einen Schlüssel für diese Tür,,,,,,Vous avez besoin de la clé pour cette porte,Kell egy kulcs az ajtóhoz,,,,,Potrzebujesz klucza do tych drzwi,Você precisa da chave para esta porta,,Ai nevoie de cheie pentru ușa asta,,
 Take out the control center!,TXT_EX_TAKEOUT,,,,Znič řídící středisko!,Schalte das Kontrollzentrum aus!,,,,,,Détruisez le centre de contrôle !,Iktasd ki a irányító központot!,,,,,Zniszcz centrum kontrolne!,Destrua o centro de controle!,,Distruge centrul de control!,,
 %d towers remaining,TXT_EX_TOWERSREMAIN,,,,Zbývají %d věže,%d Türme noch übrig,,,,,,%d tours restantes,%d torony van hátra,,,,,Pozostało wież: %d,Ainda restam %d torres,,%d turnuri rămase,,
-Invisibility is about to expire,TXT_EX_INVISEXP,,,,Neviditelnost brzy vyprchá,Unsichtbarkeit läuft bald ab,,,,,,L'invisibilité est sur le point d'expirer,Láthatatlanság hamarosan lejár,,,,,Niewidzialność kończy się,Invisibilidade está prestes a expirar,,Invizibilitatea expiră curând,,
-Invincibility is about to expire,TXT_EX_INVINVCEX,,,,Nesmrtelnost brzy vyprchá,Unverwundbarkeit läuft bald ab,,,,,,L'invincibilité est sur le point d'expirer,Sérthetetlenség hamarosan lejár,,,,,Nietykalność kończy się,Invencibilidade está prestes a expirar,,Invincibilitatea expiră curând,,
+Invisibility is about to expire,TXT_EX_INVISEX,,,,Neviditelnost brzy vyprchá,Unsichtbarkeit läuft bald ab,,,,,,L'invisibilité est sur le point d'expirer,Láthatatlanság hamarosan lejár,,,,,Niewidzialność kończy się,Invisibilidade está prestes a expirar,,Invizibilitatea expiră curând,,
+Invincibility is about to expire,TXT_EX_INVINCEX,,,,Nesmrtelnost brzy vyprchá,Unverwundbarkeit läuft bald ab,,,,,,L'invincibilité est sur le point d'expirer,Sérthetetlenség hamarosan lejár,,,,,Nietykalność kończy się,Invencibilidade está prestes a expirar,,Invincibilitatea expiră curând,,
 Weapon power is about to expire,TXT_EX_WEAPONEX,,,,Síla zbraně brzy vyprchá,Waffenenergie läuft bald ab,,,,,,La puissance de l'arme est sur le point d'expirer,Fegyver túlerő hamarosan lejár,,,,,Wzmocnienie broni kończy się,Poder da arma está prestes a expirar,,Puterea armei expiră curând,,
 Mask is about to expire,TXT_EX_MASKEX,,,,Maska brzy vyprchá,Maske läuft bald ab,,,,,,Le masque est sur le point d'expirer,Maszk hamarosan lejár,,,,,Maska traci swą moc,Máscara está prestes a expirar,,Masca expiră curând,,
 Full Viewing Pitch (Experimental),PLRMNU_FULLVIEWPITCH,,,,Plný pohled nahoru/dolů (experimentální),,,,,,,Angle de vue complet (expérimental),Teljes szabad egér nézet (Kísérleti),,,,,Maksymalny Kąt Widoku (Eksperymentalne),Inclinação total de visão (experimental),,Privire Sus-Jos la 90° (Prototip),,
```
However, at the moment, I don't have time to learn how to compile Raze with this modification myself, so technically I haven't actually confirmed that this works.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play *Exhumed* with messages turned on.
2. Acquire the Scarab Amulet and Unseen Eye items (or load the attached save file).
3. Use the items and wait for their effects to expire.
4. Observe the messages.

### Your configuration

By temporarily renaming my `raze.ini` and allowing Raze to create a new file, I have confirmed that this happens with the default configuration.

**Comment by coelckers** [comment]
I fixed both in the master data on Google Sheets, they will be activated with the next text update.
