### ISSUE TITLE
Blood Post Mortem - Disappearing secret exit switch[BUG] 

### ISSUE THREAD

**Issue by murderousmashedpotatos** [ZDoom/Raze#887]
### Raze version

1.6.2 and pre1.7 561

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Home

### Relevant hardware info

AMD

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Probably an issue only on my end, but shooting the red circle that leads to the secret level of Blood Post Mortem makes it disappear until I shoot it again, it disappears on and off each time I shoot for some reason. 

### Steps to reproduce the behaviour.

1. Go to forbidden rituals and try to activate the secret exit, if the thing disappears, then it isn't just a glitch for me. You can delete this or smth if its just me.

**Comment by mjr4077au** [comment]
Its not so much that its disappearing, it changes when shot. The behaviour here matches NBlood so I believe everything is correct. If I'm missing something, please let us know.

**Comment by murderousmashedpotatos** [comment]
Oh, weird, it's just that in dos it doesn't disappear, it changes when shot. Its probably an issue on my end, because it is literally disappearing, not just changing. Occasionally it becomes a red square though, which also doesn't happen in DOS. It isn't a big deal anyway.

**Comment by mjr4077au** [comment]
This is what I see in Raze and NBlood.

https://user-images.githubusercontent.com/48643140/225501097-9ab43f2b-039f-481e-87a9-7e6f326df59d.mp4

![Blood_0010](https://user-images.githubusercontent.com/48643140/225500339-6ee41b5a-c5bc-4523-81e0-3a8e903339ac.png)
![Blood_0009](https://user-images.githubusercontent.com/48643140/225500366-be4b5065-1236-4bb3-b5f9-6845629fb234.png)

Does this not happen in DOS? I must admit I didn't fire up DOSBox.

**Comment by mjr4077au** [comment]
I checked DOSBox and it seems identical. Can you please get a video of what you think is wrong so there's no confusion?

**Comment by murderousmashedpotatos** [comment]
Ah, that is supposed to happen then. I could have sworn it wasn't supposed to do anything visually, my bad. Thank you!

**Comment by murderousmashedpotatos** [comment]
No need to reopen, it isn't a bug it seems.

**Comment by mjr4077au** [comment]
All good, champion. I'd rather get a bug report that turns out to be nothing than for something legitimate not to be.
