### ISSUE TITLE
[BUG] Exhumed: Loading save uses heart item

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#888]
### Raze version

Raze 1.6.2

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 20.3

### Relevant hardware info

Intel CPU, AMD GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If I open *Exhumed* in Raze and immediately load a save in which I have less than full health, the game will use the Still Beating Heart item automatically.

This even happens if I *don't have* the heart item, in which case it *appears* in my inventory. After saving again when this happens, inspection of the unzipped save file appears to show that the number of hearts has gone from 0 to 255, and I believe this wraparound is the eventual root cause (or at least one possible cause) of #415, as explained in my comments there.

As far as I can tell, this erroneous use of the heart item occurs only when loading a less-than-full-health save from the main menu immediately after starting Raze. If I then load the same save again without closing Raze, or if I load the save after starting any other session (e.g. a new game), the bug does not occur.

### Steps to reproduce the behaviour.

Used heart:
1. Open *Exhumed* in Raze.
2. Open the console and enter `map lev5`. (There's a heart on the left across some water.)
3. Get the heart and take damage from the fish.
4. Save the game.
5. Exit Raze.
6. Open *Exhumed* in Raze again.
7. Load the save created in step 4.

Glitched heart:
1. Open *Exhumed* in Raze.
2. Start a new game.
3. Run to the first monsters and get hurt.
4. Save the game.
5. Exit Raze.
6. Open *Exhumed* in Raze again.
7. Load the save created in step 4.

Given that the bug seems to occur upon *loading* a save in a particular way, there's probably no value in providing a save file in which the bug has not already occurred. Meanwhile, only when the bug occurs on a save with no hearts does it really leave any evidence of having happened. So, after completing the *second* set of steps above, I saved again ([save0000.zip](https://github.com/ZDoom/Raze/files/10718677/save0000.zip)). In this save, my inventory shows a heart even though I never picked one up, and inspection of the unzipped save file will show that the heart counter is at `255`, while my magic appears to be at `-500` (which makes sense in that the game spent magic I never picked up in order to use the heart I never picked up).

### Your configuration

This was tested with the default `raze.ini` created by Raze.

**Comment by mjr4077au** [comment]
@michaelneverwins I believe this should be resolved now. A personal thank you for your detailed analysis and fact presentation as well!
