### ISSUE TITLE
[BUG] Duke Nukem 3D: Strange projectile behavior in Duke3D

### ISSUE THREAD

**Issue by Dynamo128** [ZDoom/Raze#890]
**Raze version**

Raze 1.6.2
**Which game are you running with Raze?**

Duke Nukem 3D
**What Operating System are you using?**

Windows 10
**Please describe your specific OS version**

_no response_
**Relevant hardware info**

_no response_
**Have you checked that no other similar issue already exists?**

    I have searched and not found similar issues.

**A clear and concise description of what the bug is.**

I was playing the map WGCity.map and there is some weird behavior going on with the Octabrain projectile. I've uploaded a video demonstrating the problem on Discord.

https://cdn.discordapp.com/attachments/674163641934807050/1080848280776364102/wtf.mp4

The octabrain projectile seems to be getting stuck, this happened elsewhere in the map too but I didn't realize what was going on at first. The reason I can tell is because the projectile repeatedly plays one of the octabrain idle sounds even after the octabrain is dead, which I had happen elsewhere in the map but I assumed it was just an audio trigger. I have included a save file where the problem occurs as seen in the video (if you don't approach the projectile it remains stuck for even longer) plus the map in question:

https://cdn.discordapp.com/attachments/674163641934807050/1080862046897315870/save.zip

I assume that the problem is not exclusive to the octabrain projectile but this is what I have observed.
**Steps to reproduce the behaviour.**

Provide a Log

_no response_

**Comment by Dynamo128** [comment]
https://cdn.discordapp.com/attachments/674163641934807050/1080868125450448956/2023-03-02_16-01-15.mp4

Here's a projectile stuck in a building, constantly producing the sound.

**Comment by coelckers** [comment]
That weird bouncing behavior is intended. I can reproduce it with older builds as well and there's explicit coding for it.

The actual bug in here, i.e. that the animation does not continue when the projectile is blocked, cannot be reproduced in master, I guess it had been fixed along the way.
