### ISSUE TITLE
[BUG] Giant Sprite Shadows (continued...)

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#892]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The previous giant sprite bug report was closed as the was thought to be a side effect of actors never updating their z after death, however I've just confirmed this glitch for actors who haven't died yet as well.

I'll attach a save file. In the save, there is a ghost _wayyy_ above the player, in the trees. Its shadow reaches the ground near the player and is massive, it just looks like a massive black transparent ghost is attacking you. The real ghost will slowly float down to you and the shadow will slowly shrink in size as it does so.

I think it should be made clear that in vanilla Shadow Warrior, shadows DO NOT noticeably change size like this. Their size is derived from the size of the sprite that is casting them; and if they do change in size based on elevation of the casting sprite, there is at least a distance limit so there are never giant phantom shadows on the ground from sprites miles up in the air. Gave me a fright.

[Save.zip](https://github.com/ZDoom/Raze/files/10984017/Save.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load my save (in Wanton Destruction, as it is a Wanton Destruction save) and look around
2. Get chased around by giant scary living ghost sleep paralysis creature
3. Realize its not real, and the real ghost is way above you in the trees

**Comment by ninjakitty844** [comment]
Actually, it seems even ghosts that are sort of close to the ground are casting way bigger shadows than they should, odd...

**Comment by mjr4077au** [comment]
I've reverted the shadow changes for now. While the change fixes weird issues such as no sprites on elevators because they're drawn at the lowest point, its not worth the issues you've raised.
