### ISSUE TITLE
[BUG] SW: Sprites that are shaded too dark can become alpha (game uses full black as alpha)

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#894]
### Raze version

Raze 1.6.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Certain sprites have some pixels that are almost completely pitch black. Certain lighting conditions (like dark lighting) will turn those pixels into pitch black. Since Shadow Warrior uses completely pitch black pixels as alpha (as well as certain shades of purple), these pixels will become transparent when they were never supposed to be.

I think Raze should figure out the alpha of a pixel BEFORE applying lighting to it. This is likely what happens in DOS, and it would likely solve this bug.

Example screenshot:
![ShadowWarrior_0027](https://user-images.githubusercontent.com/89247988/225466298-cf73d756-1bc5-4cd7-8aa8-9156e5e79c90.png)
(I've also had this bug happen with the snake in the first level of Code of Honor)

Save file (matches screenshot):
[Save.zip](https://github.com/ZDoom/Raze/files/10985322/Save.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load my save
2.
3.

### Your configuration

```ini
Happens even with default config
```

**Comment by mjr4077au** [comment]
@ninjakitty844 just for reference, we're up to 1.6.2 if you wished to upgrade to a newer build that may include fixes. There's also devbuilds here which has a lot of texture system refactoring that isn't in any 1.6.x release https://devbuilds.drdteam.org/raze/.

**Comment by ninjakitty844** [comment]
Oh, i hadn't realized there had been updates. Will definitely update.

**Comment by mjr4077au** [comment]
Keen to hear whether this happens on a devbuild. Also, is the save you uploaded correct? It doesn't take me to the spot in the picture.

**Comment by ninjakitty844** [comment]
Can confirm bug is present in latest devbuild.

**Comment by coelckers** [comment]
fixed in c6054595d070963edab85d3c850f0e1d308c06ae
