### ISSUE TITLE
[BUG] Console points to wrong path on macOS if no games are found

### ISSUE THREAD

**Issue by warrex1979** [ZDoom/Raze#895]
### Raze version

Raze 1.6.2

### Which game are you running with Raze?

Other

### What Operating System are you using?

Mac OS

### Please describe your specific OS version

13.2.1

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Starting Raze on macOS with no games installed results in the following console output:

> Unable to find any game data. Please verify your settings.
> Install game data files in subfolders of '/Users/user name/Library/Application Support/raze'

This however does not match the path Raze searches in as given in the .ini file:

> [GameSearch.Directories]
> Path=.
> Path=./*
> Path=/Users/user name/Documents/Raze/*
> Path=/Users/user name/Library/Application Support/Raze/EDuke32
> Path=/Users/user name/Library/Application Support/Raze/JFDuke32
> Path=/Users/user name/Library/Application Support/Raze/NBlood
> Path=/Users/user name/Library/Application Support/Raze/Raze/*
> Path=$PROGDIR
> Path=$PROGDIR/*
> Path=/Library/Application Support/Raze/EDuke32
> Path=/Library/Application Support/Raze/JFDuke32
> Path=/Library/Application Support/Raze/NBlood
> Path=/Library/Application Support/Raze/JFSW
> Path=/Library/Application Support/Raze/VoidSW
> Path=/Library/Application Support/Raze/Raze/*
> Path=$STEAM

To avoid confusion please add /Users/user name/Library/Application Support/raze/* to the default .ini or change the console output so that it points to /Users/user name/Documents/Raze/*.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game on macOS with no games installed.

### Your configuration

```ini
N/A
```

### Provide a Log

N/A

**Comment by mjr4077au** [comment]
@coelckers how's the best way to address this without breaking things for existing Raze and GZDoom users?

The line that throws the error upon not finding data is here: https://github.com/ZDoom/Raze/blob/d17650f8858ffe4ef5fa1a4ba40ef4e9ffcbce1e/source/core/gamecontrol.cpp#L717. Within it, it calls `M_GetAppDataPath()`,

The internals for `M_GetAppDataPath()` (https://github.com/ZDoom/Raze/blob/d17650f8858ffe4ef5fa1a4ba40ef4e9ffcbce1e/source/common/platform/posix/osx/i_specialpaths.mm#L107) uses `GAMENAMELOWERCASE`, which is where our problem lies.

The internals for `M_GetMacSearchDirectories()` (https://github.com/ZDoom/Raze/blob/d17650f8858ffe4ef5fa1a4ba40ef4e9ffcbce1e/source/common/platform/posix/osx/i_specialpaths.mm#L67-L87) uses `GAME_DIR`, which for Apple is defined as `GAMENAME` (see https://github.com/ZDoom/Raze/blob/d17650f8858ffe4ef5fa1a4ba40ef4e9ffcbce1e/source/core/version.h#L86-L87 and https://github.com/ZDoom/Raze/blob/d17650f8858ffe4ef5fa1a4ba40ef4e9ffcbce1e/source/core/version.h#L60)

Just not sure how to fix this inconsistency.

**Comment by coelckers** [comment]
Addressed in 9b751d6469093c370dc9ea2e8a49b5eff70942e6
