### ISSUE TITLE
[BUG] Exhumed: Ramses spirit head at end of LEV1 not working

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#897]
Looks like it's fine in 1.6.2 when I tested it, probably the texture system refactor. Can confirm its not from any of the refactoring I've done so far.

![Exhumed_0002](https://user-images.githubusercontent.com/48643140/227696090-b36ecd26-1b73-483a-bdd3-b1a954a468fc.png)

**Comment by coelckers** [comment]
Bug was introduced in 0869497ecb1aaba6565c3a11bb4775efab35ea72

**Comment by coelckers** [comment]
fixed in 32237421c9cf1da26924bda93e45799ad55453de
