### ISSUE TITLE
[BUG] Exhumed: M-60 lost when deselected

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#898]
### Raze version

1.7pre-798-g32237421c9

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the player picks up the machinegun and then selects another weapon, the machinegun is lost.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11068522/machinegun.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Pick up the machine gun (M-60)
3. Select another weapon
4. Try to select the machine gun again

**Comment by mjr4077au** [comment]
@Talon1024 thanks mate, super quick report following some big refactoring! Was a signedness issue on a variable, tested and working well again.
