### ISSUE TITLE
[BUG] [Blood] Inconsistent message colors

### ISSUE THREAD

**Issue by valter12437** [ZDoom/Raze#899]
### Raze version

raze-x64-1.7pre-683-g181f88b02

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

AMD Ryzen 3 3200g with Vega 8 graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game saved/quick save message and item pickup message are different colors. Reporting this because I'm not sure if this is intentional or not. That being said, the grey color from the "game saved" message resembles vanilla Blood better.

![Blood_0020](https://user-images.githubusercontent.com/82282361/227743790-1e31db0f-94e4-4640-a766-8448f4e5cc1d.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Save the game, then pick any item.
2.
3.

**Comment by mjr4077au** [comment]
This is original behaviour. Below is a screenshot from NBlood:

![image](https://user-images.githubusercontent.com/48643140/227753301-84916f2d-a7cc-48e7-9386-dd6b5bfb7b19.png)

They probably did this to visually separate notifications for the player.
