### ISSUE TITLE
[BUG] Forced looking up/down in Exhumed

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#901]
### Raze version

1.7pre-830-ge9a5f745fc

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Exhumed, the player is forced to look up/down at a certain pitch. Neither the mouse, nor the look up/look down keys can be used to manually look up or down.

It seems to have something to do with the player's current height.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start playing the Exhumed training level
2. Go to the underwater section
3. You should have experienced the bug by now

**Comment by mjr4077au** [comment]
I'm not able to reproduce it. Can you please show me a video or something? Does the player look up/down but it returns to centre?

https://user-images.githubusercontent.com/48643140/227762386-bed12406-0316-4788-9be3-459b1ab1e580.mp4

**Comment by mjr4077au** [comment]
Nevermind, I've got it now. Looking into it!
