### ISSUE TITLE
[BUG] Exhumed grenades are bugged

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#904]
### Raze version

1.7pre-838-g d45be79c24

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The grenades don't seem to be working properly. After picking up the first grenade and tossing it, I cannot use the grenades again, even if I pick up more.

Also, picking up more grenades does not increase the number of grenades you have.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11073073/nades.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Pick up a grenade
2. Select it (Weapon 5)
3. Throw it
4. Pick up another one
5. Try to select it
6. Does not work

**Comment by mjr4077au** [comment]
Thanks mate, might have helped if I opened my eyes better while reading the grenade pickup code a bit more when comparing it to the generic weapon handler!
