### ISSUE TITLE
[BUG] Crash or hang trying to load this autosave

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#905]
### Raze version

1.7pre-838-g d45be79c24

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game crashes or hangs when I try to load [this autosave](https://github.com/ZDoom/Raze/files/11073087/Autosave.2023-03-26.16.38.46.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. Try to load the autosave
3. Crash (see log below) or hang

### Provide a Log

[raze-crash.log](https://github.com/ZDoom/Raze/files/11073086/raze-crash.log)

**Comment by mjr4077au** [comment]
@coelckers I might need to ask you to look at this one. The actor pointer in the `PlayerAngles` object is null after the reload, but the serialiser absolutely includes it:

![image](https://user-images.githubusercontent.com/48643140/227860983-bc007c6c-0b57-4d15-9450-dcb0883e3c25.png)

https://github.com/ZDoom/Raze/blob/cb3fec39df6f3907f55c00b5b47ff0aa27c149b5/source/core/gameinput.cpp#L360-L375
I'm not too sure what's going on here. Even the player's object is null.

![image](https://user-images.githubusercontent.com/48643140/227861400-cfe8cd9c-d171-4d8d-b53e-f382545a98e0.png)

**Comment by coelckers** [comment]
fixed in a64f19c16d5581618072ad98bb00c7160caf757b

This is actually a bug in RapidJson. I reported it to their maintainers back in 2016 but it hadn't gotten fixed in all this time. Instead, due to an optimization, it got copied to a second function now which I missed when upgrading the library.
