### ISSUE TITLE
[BUG] Blood - Explosions do too much damage

### ISSUE THREAD

**Issue by VideoBrains** [ZDoom/Raze#911]
### Raze version

Raze 1.7.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Explosions do too much damage, making dynamite jumps impossible and making the explosive weapons too powerful.

It seems as if the explosion damage scaling from the center of the explosion is bugged, as enemies caught at the outer edge of the explosion should be minorly hurt, but are instead outright killed.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Observe explosion damage in either Raze 1.5.0 or Nblood against the innocents in E3M1, or how a rocket jump will leave the player with usually around 40-60 hp
2. Try the same thing in Raze 1.7.0 and notice that the explosion barely has to touch innocents to kill them
3. Try do a tnt jump in Raze 1.7.0 and die instantly due to unusual damage

**Comment by mjr4077au** [comment]
@VideoBrains is this different to the bug you posted earlier (https://github.com/ZDoom/Raze/issues/860)? We'll take a look at this soon.

**Comment by VideoBrains** [comment]
Yes thank you, the issue from my original tnt knock-back bug post has been corrected and it's a different bug I think

it was present when i made the other post but i had hoped that both problems were shared and the tnt knockback fix would have also solved the damage issue

**Comment by coelckers** [comment]
fixed in 75548081047296ec868bffcc483e2c5cc5a41a4d
