### ISSUE TITLE
[BUG] Crash upon stomping a shrunken enemy

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#912]
### Raze version

1.8pre-100-g 2ba204444c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When Duke stomps a shrunken enemy, the game crashes.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11179815/shrunken.enemy.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use the shrinker on an enemy
2. Approach the enemy, and Duke will automatically stomp it
3. Game crashes when the enemy should explode into tiny giblets

**Comment by coelckers** [comment]
fixed in 9c164ad2909f54931e33a39b2e88d4b4ae08ee46
