### ISSUE TITLE
[BUG] Floating underwater on E1L4 (Toxic Dump)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#914]
### Raze version

1.8pre-106-g 307276a276

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04.2 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On E1L4, when the player dives underwater, the player keeps floating upwards until the submarine is completely flooded, even if the player is outside the submarine.

I have a feeling this has something to do with the sector the player starts in, and the fact its floor starts rising at the start of the level.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11184038/toxic.dump.water.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to Duke Nukem 3D E1L4
2. Dive underwater
3. If you are not descending, you start rising as if you have a floatation device

**Comment by mjr4077au** [comment]
Bisected back to 2ba204444cd11ae678abcb7472d601f76f902614 but won't have time to see why at the moment, barely got the time to get as far as I did without my kid hating on me 😅

**Comment by coelckers** [comment]
fixed in 50d406be4e1d212f3ef30a1fe0fa88f3225df228
