### ISSUE TITLE
[BUG] Some Octabrains cannot be hit by bullets

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#915]
### Raze version

1.8pre-106-g 307276a276

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There's a few issues with the Octabrains.

First of all, some of the Octabrains cannot be hit by bullets, so you have to use explosives to kill them. Also, IIRC they become hittable with bullet weapons if they forget about you, and then you come back later.

Second, the Octabrain on E1L3 (Death Row) behind the cross in the chapel spawns too early. It's supposed to spawn when you press the Battlelord's face and the room turns red.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11184117/brainocta.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to the cross within the chapel on E1L3 (Death Row)
2. The Octabrain is behind the cross, even before you press the Battlelord's face
3. Try gunning down the Octabrain

**Comment by coelckers** [comment]
The non-hittable Octabrains should be fixed by merging a bit more code.

About the Octabrain behind the cross you are mistaken. This isn't a monster spawned by a player action but a map placed one. It's always there.
