### ISSUE TITLE
[BUG] Inactive enemies cannot be hurt

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#916]
### Raze version

1.8pre-127-g 684fb5eb74

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Inactive enemies in Duke Nukem 3D cannot be hurt before they see you. However, inactive enemies could be hurt in the original game.

A good place to test this bug is the arcade on Duke Nukem 3D E1L1. The explosions should kill the inactive liztroops.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11185127/arcade.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to the arcade on E1L1 or load the saved game
2. Shoot the gas canisters to trigger the scripted explosion sequence
3. The inactive liztroops are still alive

**Comment by coelckers** [comment]
fixed in 3df7539eb9d3f651880a7061c1298929758bae37
