### ISSUE TITLE
[BUG] Enemies can walk through barred windows on E1L3

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#917]
### Raze version

1.8pre-128-g 3df7539eb9

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The enemies can walk through the barred windows on E1L3. I don't think this happens in the original game.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11185685/window.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to the outdoor area in E1L3 (Yellow keycard needed)
2. Alert the liztroops in the cells
3. They are able to walk out of the barred cell windows

**Comment by coelckers** [comment]
fixed in 7b1ef9e020294e970f703bcb49e7512f933a51b8

This misbehavior suggests that Build's clipmove function is even more broken than we thought, because the value being passed in was larger than it should have been, not smaller...
