### ISSUE TITLE
[BUG] Explosions are inaudible underwater

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#918]
### Raze version

1.8pre-128-g 3df7539eb9

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Explosions cannot be heard underwater.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11185696/underwater.explosions.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to a level which has an underwater cracked wall or scripted explosion sequence like E1L4, or load the saved game
2. Trigger the scripted explosion sequence by opening the cracked wall or pressing the button if you loaded aforementioned saved game
3. Nothing is heard when the explosions happen

**Comment by Talon1024** [comment]
Fixed in 1d79d0cee347d8dcff9e85b2e9bc39caefbea9e5?

**Comment by coelckers** [comment]
Yes, apparently I forgot to close the ticket.
