### ISSUE TITLE
[BUG] Kills not counted

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#920]
### Raze version

1.8pre-131-g ec9ed9588c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the player kills an enemy, that kill is not counted. As a result, the level stats show no enemies killed, and all enemies missed.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a game of Duke Nukem 3D
2. Kill one of the enemies
3. Notice the kill count does not increase. The level stats displays are needed for a live kill count.

**Comment by coelckers** [comment]
fixed in 2f61a44329d9920c690b361333f8c5a11889e31d
