### ISSUE TITLE
[BUG] Slimer egg spawn inconsistency

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#923]
### Raze version

1.8pre-131-g ec9ed9588c

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Protozoid slimer egg spawns are inconsistent between Raze and vanilla Duke Nukem 3D. It looks like Raze deletes some of the eggs that are supposed to spawn.

A screenshot from one of the affected areas from Raze:
![Duke_0042](https://user-images.githubusercontent.com/6550500/230900764-04185571-9d60-43ad-9dde-8d1423be5be9.png)

A screenshot from the same area, from Duke Nukem 3D: Megaton Edition:
![20230410082110_1](https://user-images.githubusercontent.com/6550500/230900653-4cee99a3-ae7b-4d5a-aa59-1f3fd5437735.jpg)

[And a saved game, although I'm not sure it would help](https://github.com/ZDoom/Raze/files/11190426/eggies.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E2L2 or any level that has slimer eggs
2. Go to the area shown in the screenshot
3. Only 2 eggs are in the area. There should be 5 (or more?)

**Comment by coelckers** [comment]
fixed in 660227e1753df1f2a5aadbfad0b2e157367c6187
