### ISSUE TITLE
[BUG] Atomic Edition enemies appear regardless of skill

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#926]
### Raze version

1.8pre-138-g f7d1838266

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The new enemies in Duke Nukem 3D: Atomic Edition always appear, regardless of the player's skill setting. For example, enemy tanks on E4L2 should not appear before the latter part of E4L2 on "Piece of Cake", and there should be no protector drones in the women's bathroom in E4L2 on "Piece of Cake".

I tried to fix this issue in #925, but my "fix" was rejected. On the other hand, I think [this is](https://github.com/elhobbs/jfduke3d/blob/36aa403b5d97f51899c216f2645eca86dd0549e4/src/game.c#L3395-L3400) the part of the original game code which filters these new enemies according to the player's skill setting.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11211532/tanks.which.should.not.be.here.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on Episode 4 "The Birth" on the "Piece of Cake" skill
2. Skip to E4L2
3. Run around and notice the enemies which should not appear

**Comment by coelckers** [comment]
Thanks. I must have missed that 'default' part when looking for it. Actually, this will make things a lot easier than I feared.

**Comment by coelckers** [comment]
Let's hope I got it all now. I made the skill filtering option fully explicit now, so any actor not requiring it will have to be marked in the spawn map. No more inferring the behavior from other flags or base classes - this was an utter disaster in original Duke.

**Comment by Talon1024** [comment]
I think you missed keycards.
