### ISSUE TITLE
[Feature] (Blood) Add dynamite chargebar to alt hud

### ISSUE THREAD

**Issue by r3dnasa** [ZDoom/Raze#929]
### Raze version

Raze 1.7.0

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### If Other OS, please describe

Windows 10 Home

### Is your feature request related to a problem? Please describe.

When using the alt hud option in blood its annoying not being able to see how much i've charged my dynamite which can make it more difficult to line up dynamite throws

### Describe the solution you'd like

Add the chargebar for dynamite to the alt hud in blood

**Comment by coelckers** [comment]
added in 812b9d76d6e7b6ce7f1fd6dc95b6877458040158
