### ISSUE TITLE
[BUG] Dynamite pickup explosion animations not playing

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#930]
### Raze version

1.8pre-153-g c5c8ed16a3

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I can't tell exactly what's happening, but it looks like the explosion animations that should play when a box of TNT is detonated are not playing.

[Here's a saved game from before the explosion, on RRRA E1L1](https://github.com/ZDoom/Raze/files/11226980/before.things.zip)
[And a saved game from after the "explosion", on RRRA E1L1](https://github.com/ZDoom/Raze/files/11226982/things.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Shoot a box of TNT
2. Notice a puff of white above where the box of TNT used to be

**Comment by coelckers** [comment]
fixed in aad6c3da907ce4d5b89768498728cc1aad745b8b
