### ISSUE TITLE
[BUG] Missiles being deflected

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#931]
### Raze version

1.8pre-153-g c5c8ed16a3

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems like missiles fired by the RPG are being deflected at random for some reason. From what I've seen, it seems to happen when aiming at the chaingunners on E3L4 (L.A. Rumble (I HATE that level)), or when the missile hits a laser shot from an enemy liztroop, or just completely at random. For example:
![Duke_0044](https://user-images.githubusercontent.com/6550500/232128008-a5b73116-b2f8-43b3-9dbf-97fc473c9615.png)
Luckily, I seem to have found a spot where it can be consistently reproduced. [Here's a saved game](https://github.com/ZDoom/Raze/files/11236068/lasers.deflect.missiles.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Fire the RPG
3. Notice the missile being deflected right after it passes the ledge

**Comment by FitzRoyX** [comment]
I had this happen to me once yesterday but couldn't figure out how to reproduce it heh

**Comment by coelckers** [comment]
fixed in 1304577dacccc7302fe5e4120171082904f05432
