### ISSUE TITLE
[BUG] Items oddly rotating

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#932]
### Raze version

1.8pre-166-g 24fc780ede

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Many of the items, like the health pickups and weapon pickups, as well as the analog clocks on the walls, are weirdly rotating when they shouldn't be. The rotation appears to have some relation to the player's heading or position.

https://user-images.githubusercontent.com/6550500/232232320-50b4b770-913a-4323-a1ab-8dff264ce1ad.mp4

I bisected this issue to 8bd88b867830867858e59215a618cb77426668aa.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the [Enhanced Resource Pack](https://www.moddb.com/mods/enhanced-resource-pack-for-duke-nukem-3d)
2. Start a new game
3. Look at some of the aforementioned items without picking them up
4. They will be rotating for some reason

**Comment by coelckers** [comment]
fixed in 17cde1e3ca2f279b28669acff89d814d2ecc9e82
