### ISSUE TITLE
[BUG] Octabrain and Sentry drone cannot be hit with hitscans

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#936]
### Raze version

1.8pre-205-g 07102fbd39

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Octabrains and Sentry drones cannot be hit with hitscans. They can only be hurt with projectile weapons or explosions.

[Here's a saved game in front of an Octabrain](https://github.com/ZDoom/Raze/files/11243792/brains.zip)
[Ditto for the Sentry drone](https://github.com/ZDoom/Raze/files/11243793/suicide.bomber.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load either of the two above saved games
2. Try to attack the Octabrain or Sentry drone using a hitscan weapon (Pistol, Shotgun, Chaingun)
3. They cannot be hurt

**Comment by coelckers** [comment]
fixed in 86637cd20cfc7fae6a1d10de2ec66b0d8eb864ba
