### ISSUE TITLE
[BUG] Battlelord (E1 boss) is overpowered

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#937]
### Raze version

1.8pre-205-g 07102fbd39

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Battlelord (E1 boss) and Battlelord Sentries (minibosses) do too much damage, such that the boss fight on E1L5 (The Abyss) is now unwinnable even if you (ab)use the portable medkit, and cheese tactics with the Shrinker or pipebombs are required to win the miniboss fights on levels such as E4L5 (Pigsty).

I remember being able to win the E1 boss fight without having to even use the portable medkit, just by picking up the atomic healths scattered around the arena.

On a related note, I looked at the ZScript for the Battlelord, and I saw a new flag addition (+ALTHITSCANDIRECTION), but it looks like this new flag currently does nothing.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11243796/abyssal.abuse.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Start the boss fight and try to win
3. The attacks do so much damage, you can't win

**Comment by coelckers** [comment]
The ALTHITSCANDIRECTION flag is used in the DukeActor.HitscanAttack function.

**Comment by coelckers** [comment]
fixed in a3c08e5a9dd7d5e651b448329220f5d215e3283a

This had been wrong for quite some time - but when I wanted to fix it for the boss I not only got the factor wrong, but also missed that the spread for the other enemies was also not correct, so for the boss it got even worse.
