### ISSUE TITLE
[BUG] Turrets not autoaimed at

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#938]
### Raze version

1.8pre-208-g 316867581b

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The little green laser turrets are not being autoaimed at.

Although they weren't autoaimed at in DukeGDX, I just tried launching the original game in DOSBox, and the turrets do get autoaimed at in the original DOS version of the game.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11262161/turretest.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game or go to any level with the aforementioned turrets
2. Try to shoot the turrets with the pistol
3. Your shots will rarely hit the turret, unless you're in melee range

**Comment by FitzRoyX** [comment]
I noticed this too. It might be more accurate to say that autoaim is working, it's just that the shots landed with autoaim aren't doing any dmg, because I can't see any bullet holes in the nearby wall to suggest that the bullets are missing.

**Comment by Talon1024** [comment]
I just did a bisect, and 3af08ecbac7d27ea069f516f067244ef8466d111 is the commit where this issue started.

**Comment by coelckers** [comment]
fixed in 6faca3a93f6d68dbf20f8e5fa00b37ac741b2d97

Not really surprising because the trajectory calculations between autoaim and attack were not the same.
