### ISSUE TITLE
[BUG] Duke can go through vent fan in E4L1 without destroying it first

### ISSUE THREAD

**Issue by FitzRoyX** [ZDoom/Raze#940]
### Raze version

83365a9

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel HD 530

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Can go through small vent fans in E4L1 without destroying them. eduke32 seems to require kicking or shooting the fan out before being able to enter.
[save0000.zip](https://github.com/ZDoom/Raze/files/11302887/save0000.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Jump into vent

**Comment by coelckers** [comment]
The vent in that savegame blocks for me in the latest master.

**Comment by FitzRoyX** [comment]
Hmm, still happens for me in latest master:


https://github.com/ZDoom/Raze/assets/57089001/fd6a0c46-fc3c-481c-8b29-82ad4fdf9f00
