### ISSUE TITLE
[BUG] Duke captive women take no damage

### ISSUE THREAD

**Issue by FitzRoyX** [ZDoom/Raze#942]
### Raze version

latest master

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel HD 530

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Duke captive women take no damage

![sdd1](https://user-images.githubusercontent.com/57089001/235004834-50dd23fc-a37c-4c4d-9740-c49b998eb8c6.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Try shooting captives

**Comment by Talon1024** [comment]
Some of them do, some don't. The dancer in the center of the bar stage on E1L2 does not take damage, but the other dancers do. It's also possible to walk through them.

[Saved game from the bar on E1L2](https://github.com/ZDoom/Raze/files/11362594/women.zip)
[Saved game in front of a captive woman on E1L4](https://github.com/ZDoom/Raze/files/11362595/captive.zip)

**Comment by coelckers** [comment]
fixed in 4742c26081774616561ea92bd4bef2bc42f33979

This was overlooked when transitioning the mess of Duke's actor init code
