### ISSUE TITLE
[BUG] Duke's sprite is flipped when seen through mirror

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#943]
### Raze version

1.8pre-428-g 7bb678bb7e

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When you look at yourself (Duke) in the mirror, the sprite is facing the wrong way.

![Duke_0048](https://user-images.githubusercontent.com/6550500/235380116-19396042-118a-49e1-90a8-ffc439fa71bc.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/11362600/mirror.on.the.wall.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game
2. Stand in front of a mirror
3. Turn so that the mirror is almost parallel to you, but not so much that you lose sight of your sprites.

**Comment by coelckers** [comment]
fixed in 3e859511cdd769eb76eda4c03d123710b4f5cb66
