### ISSUE TITLE
[BUG] Endless debug assertions opening RRRA

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#944]
![image](https://user-images.githubusercontent.com/48643140/235432787-6b08f9ac-24e6-4d53-b913-bb36fbc79290.png)
![image](https://user-images.githubusercontent.com/48643140/235432797-06e8696e-0c30-4084-96fb-cc6269aa430c.png)
![image](https://user-images.githubusercontent.com/48643140/235432809-2a7ba2b8-0c70-4702-b835-ec9fc1a6abca.png)
![image](https://user-images.githubusercontent.com/48643140/235432834-24c474a9-f9c6-4bae-8bf1-6f288adebee9.png)

**Comment by coelckers** [comment]
Looks like a script compiler bug.
Hotfix added in 009920a078fa085329761b1d0892783f7a02d204
