### ISSUE TITLE
[BUG] Blood crashing upon load for release builds.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#945]
Looks like texidsdef.h for Blood is picking up Exhumed's file?

![image](https://user-images.githubusercontent.com/48643140/235432921-bdabbfb6-969f-4034-83bc-6915d37f0c60.png)
![image](https://user-images.githubusercontent.com/48643140/235432931-b2507348-e6c0-4d14-b14a-c7712dfc7e54.png)

**Comment by coelckers** [comment]
fixed in 0e3fa8d29b06a8c95ed76406cdba7dd583724004
