### ISSUE TITLE
[BUG] Slimers don't finish eating enemies

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#948]
### Raze version

1.8pre-470-g 809d90a240

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If a slimer tries to eat an enemy, it doesn't finish eating said enemy.

![Duke_0049](https://user-images.githubusercontent.com/6550500/235983814-baebb192-3846-473d-898e-f8d458f700ec.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/11384930/eating.chaingunner.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Let a slimer eat an enemy
3. It does not finish eating the enemy, as seen in the screenshot

**Comment by coelckers** [comment]
fixed in f545815e8c7603ecb7612360cded31949b99924f
