### ISSUE TITLE
[BUG] Players cannot freeze themselves

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#949]
### Raze version

1.8pre-470-g 809d90a240

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Players cannot hurt or freeze themselves with their own freezer shots.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11384999/freeze.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Get the freezethrower
2. Aim at a wall so that the shots bounce back at you
3. When you are hit by your own shots, you don't get hurt

**Comment by coelckers** [comment]
fixed in e1b2210b75acb4948874d0405051e6c0a3e99916
