### ISSUE TITLE
[BUG] Misplaced items

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#950]
### Raze version

1.8pre-470-g 809d90a240

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some items, like health bottles or atomic healths, get displaced by nearby enemies or other things. For example, the atomic health shown in the screenshot is supposed to be in the center, not off to the side.

![Duke_0051](https://user-images.githubusercontent.com/6550500/235988309-dd5db8a6-269d-43e5-9758-87b5c76adaa3.png)

This bug is also noticeable on E3L8 "Hotel Hell"

[Here's a saved game](https://github.com/ZDoom/Raze/files/11385112/displaced.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to any level with overlapping items like E2L8 "Dark Side" or E3L8 "Hotel Hell"
2. On E2L8, go to the area shown in the screenshot, or go to the upstairs health cabinets on E3L8
3. Notice some items are displaced by other nearby items or enemies

**Comment by coelckers** [comment]
fixed in 7c31a95d1bd737ca09f5df0f00a4aafd691df3a0

Due to the extent I tried to avoid making this change for too long but as it turns out it is absolutely necessary.
