### ISSUE TITLE
[BUG] Sprites flipped when seen on security monitor

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#951]
### Raze version

1.8pre-470-g 809d90a240

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When seeing sprites through a security monitor which is being rendered to a texture, they appear flipped horizontally. This applies to sprites and voxels.

Using a security monitor, the sprites appear correctly:
![Duke_0053](https://user-images.githubusercontent.com/6550500/236193787-6775d668-0118-49be-941e-729d8e79b69e.png)
But once you stop using the security monitor:
![Duke_0054](https://user-images.githubusercontent.com/6550500/236193844-35c00c38-9967-4996-99a7-c2c58d327924.png)
The same bug on E2L1:
![Duke_0052](https://user-images.githubusercontent.com/6550500/236193898-d11f6547-2d56-4321-8cff-5ce44c5b280a.png)

[Here's a saved game](https://github.com/ZDoom/Raze/files/11396984/seccam.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to E2L1 or load the saved game
2. Use the security monitor
3. Stop using the security monitor and just look at it
4. The sprites in the security monitor will be flipped

**Comment by coelckers** [comment]
fixed in 500b3672427593cda9c2107bbc61e13aa824056e
