### ISSUE TITLE
[BUG] Missing geometry in Blood E1M2

### ISSUE THREAD

**Issue by bkoropoff** [ZDoom/Raze#953]
### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 38

### Relevant hardware info

Intel CPU, Intel GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After beating E1M1, there is missing geometry at the start of E1M2:

![image](https://user-images.githubusercontent.com/2101303/236719367-51d8cd41-dbe2-4fa4-a0c9-ba4cfae4e93a.png)

Reloading from the latest autosave fixes it.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Beat E1M1
2. Observe bug

**Comment by coelckers** [comment]
It also does not happen if starting the map directly.

**Comment by coelckers** [comment]
fixed in 2c1425e2b8f53b0627d3739449536de6f0466c65

**Comment by bkoropoff** [comment]
Thanks!
