### ISSUE TITLE
[BUG] DN3D World Tour new Duke speech not working

### ISSUE THREAD

**Issue by LuigiIsHungry** [ZDoom/Raze#954]
### Raze version

Raze 1.7.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Starting with 1.7.0, Duke always uses his legacy voice lines where available, even when "play original sounds" is set to off. In episode 5 this results in him switching back and forth between 1996 and 2016 recordings which is really jarring.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Duke Nukem 3D (WT) in Raze
2. Make sure "Play original sounds" is set to off
3. Start any episode

**Comment by sinisterseed** [comment]
There is something to note here. 

WT also introduces new lines for Duke's speech, while some old lines have names that do not match the original, causing the new lines to be used instead. Last we checked, there wasn't a workaround for this particular senario.

That being said, the toggle being entirely non-functional is definitely a bug.

**Comment by coelckers** [comment]
fixed in b6900d06318367299fc4c2c51129385b3751290d
