### ISSUE TITLE
[BUG] Player floating on E1L4 when underwater

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#955]
### Raze version

Raze 1.8pre-482-g d58df1cb45

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While the water in the submarine is rising on E1L4, the player "floats" upwards if they are underwater.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11487471/rising.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on E1L4 or load the saved game
2. Dive underwater
3. Let go of the crouch/descend key
4. Notice you are "floating"

**Comment by coelckers** [comment]
fixed in 821e7b8b27e65e9bdba8095123c188de4c9e3258

Since the last fix didn't hold, this one neuters the Initialize method for players entirely.
