### ISSUE TITLE
[Feature] OpenXR support for VR

### ISSUE THREAD

**Issue by necros2k7** [ZDoom/Raze#956]
### Which game are you running with Raze?

None

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

no possibility to run in VR

### Describe the solution you'd like

subj

### Describe alternatives you've considered

RazeXR, DukeVR

**Comment by coelckers** [comment]
Find someone willing to work on it and we may talk.

**Comment by mjr4077au** [comment]
You've mentioned RazeXR as an alternative you've considered, what's the issue with it? DrBeef has been doing excellent work with it, including reworked weapon aiming etc specifically for VR.
