### ISSUE TITLE
[BUG] Leonard (RR) takes no damage from enemies

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#957]
### Raze version

1.8pre-479-g b69dbe1db3

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Leonard is seemingly immune to bullets, lasers, explosions and plasma shots. However, he does take damage from fires.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game of Redneck Rampage, "Outskirts" (E1) or "Downtown" (E2)
2. Encounter an enemy
3. Notice you don't take any damage

**Comment by coelckers** [comment]
fixed in 517b77bfdce6bceb1087513d7a612b81f9c35a5f
