### ISSUE TITLE
[BUG] Blinded when on fire

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#960]
### Raze version

1.8pre-479-g b69dbe1db3

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the player gets lit on fire by a dog, you get blinded by the fire until the fire goes out on its own.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11593923/I.m.on.fire.help.zip)

![Blood_0028](https://github.com/ZDoom/Raze/assets/6550500/65a2efa5-ba0a-47d8-83f7-16b4611db329)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Get burned by the dog's fire
3. Your screen will get filled with that yellow/orange colour
4. Enter chase view, and you'll see clearly again

**Comment by coelckers** [comment]
fixed in 117874bb72d23804db812afa5cf3a764e90bbd7a
