### ISSUE TITLE
[BUG] Duke3d planting tripmines crashes game

### ISSUE THREAD

**Issue by FitzRoyX** [ZDoom/Raze#961]
### Raze version

517b77b

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

planting tripmines crashes game

**Comment by coelckers** [comment]
fixed in f8de8eb7a389b562aa0bc288a2056b933f0e5fbf
