### ISSUE TITLE
[BUG] Duke3D television screen in E4L1 has missing scroll graphic

### ISSUE THREAD

**Issue by FitzRoyX** [ZDoom/Raze#962]
### Raze version

d7a00b7

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Should say "storm warning". No idea if this is recent or old raze bug.
![ddds1](https://github.com/ZDoom/Raze/assets/57089001/095b15e7-4cf6-42e5-a170-cba6a80c7d92)

**Comment by coelckers** [comment]
fixed in 5ac05971d2c45c78d9efbd186ef38fd4bf9e2e42
This setup is quite the hack - the scrolling message is a sprite that teleports back to the right, and that teleporter did not work.
