### ISSUE TITLE
[BUG] Oversized things (RR)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#963]
### Raze version

1.8pre-531-g f545815e8c

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The hula dancer dolls and powder kegs in Redneck Rampage are oversized.

[Here's a saved game, showing an oversized dancer doll](https://github.com/ZDoom/Raze/files/11643565/oversized.hula.zip)
[And another saved game, showing an oversized powder keg](https://github.com/ZDoom/Raze/files/11643567/oversized.keg.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to any level which has one of these items (E1L2 "Lumberland" for a hula dancer doll, E1L5(?) "Dairyair Farms" for a powder keg)
2. Go to one of these items
3. They are oversized

**Comment by coelckers** [comment]
fixed both (plus a movement issue with the powder keg) in 3f630c5cb6c5f5eedcda5fbe4ac65ab502a4bb73
