### ISSUE TITLE
[BUG] Enemies are never gibbed by crossbow shots

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#964]
### Raze version

1.8pre-531-g f545815e8c

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Redneck Rampage, basic enemies like the old coot (pistol) and Billy Ray (shotgunner) are supposed to be gibbed by crossbow shots if they receive a direct hit from a crossbow shot. However, this never happens any more...

[Here's a saved game on E1L4 where the player has a crossbow](https://github.com/ZDoom/Raze/files/11643876/crossbow.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Pick up a crossbow 
2. Open fire on an old coot or Billy Ray clone
3. When the missile hits, they die, but do not get gibbed

**Comment by coelckers** [comment]
fixed in d8e852fe10d7e5197c57e64bc42fecd340366065
