### ISSUE TITLE
[BUG] Thunderstorm on Wako (RRRA)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#969]
### Raze version

1.8pre-531-g 5ac05971d2

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There's a thunderstorm on the Wako level (E1L5), even though there shouldn't be.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11750753/thunderstorm.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to the Wako level (E1L5)
2. Wait a few seconds
3. Hear the thunder, see the lightning light up the level

**Comment by coelckers** [comment]
fixed in c4cb44f5f09b9316a9e85d13813d1d791cbc51a2
