### ISSUE TITLE
[BUG] Mama Jackalope's gas clouds are harmless (RRRA)

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#970]
### Raze version

1.8pre-531-g 5ac05971d2

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Jackalope boss/mama jackalope's gas clouds are seemingly harmless.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11750777/gas.clouds.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Go to any level where you have to fight a mama jackalope
2. Fight until she makes gas clouds
3. Approach the gas clouds
4. You take no damage

**Comment by coelckers** [comment]
fixed in 428425b6dc44755b0857f9f77b9fd83d992796be
