### ISSUE TITLE
[BUG] [Exhumed] Exit door on Kilmaatikahn Boss doesn't open

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#972]
### Raze version

Raze 1.7.1

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21.1

### Relevant hardware info

Intel CPU, AMD GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If I'm not mistaken (and I apologize if I am), the exit door on the 19th level (_Kilmaatikahn Boss_) should open when the boss is defeated. For me, it doesn't open.

The attached save file (renamed from `save0000.dsave` to `save0000.zip`) was made after killing the boss: [`save0000.zip`](https://github.com/ZDoom/Raze/files/11862757/save0000.zip)

I wonder if this is related to #971, because I hear a door/switch activation sound when the boss is done exploding, and maybe the door trigger is activated twice despite it not being associated with a key press. This is total speculation, however.

As of now, my only workaround is to enter `noclip` in the console and walk through the closed door to complete the level.

#### Edit:

_Prior to submitting this bug report, I tried killing the boss several times and never saw the door open, but was always loading from one of the save files I had created in the level. After writing the steps to reproduce the bug, in which I originally suggested warping to the map rather than playing from the start of the game, I figured I should take my own advice and rule out the possibility of a messed-up save file. So I used `map lev19` in the console to warp to the map, used cheats to cope with the fact that I was starting with no weapons, and killed the boss. This time, the door opened._

_So the good news is that this bug does not always occur, but unfortunately the game still got itself into a broken state in the playthrough in which I actually have all my items and weapons. Attached is one of the save files from an earlier point at which the level is apparently already bugged: [`save0001.zip`](https://github.com/ZDoom/Raze/files/11862900/save0001.zip)_

_I've updated the steps to reproduce the bug below._

### Steps to reproduce the behaviour.

1. ~~Play to _Kilmaatikahn Boss_ or enter `map lev19` in the console to warp there.~~ _Load the save file `save0001.zip` attached above._
2. ~~Play through the level~~ _Activate the switch_ and defeat the boss.
3. Observe that this door is not open.
![door](https://github.com/ZDoom/Raze/assets/73746653/a0a35bc6-c468-498f-9c32-d4baf1212380)
Note that the door is hidden behind the wall which is destroyed by blowing up this thing.
![explosive](https://github.com/ZDoom/Raze/assets/73746653/beca158d-f557-41ba-8851-01fe04da141d)

### Your configuration

As with #971, I've tried reproducing the bug with a nearly default configuration and confirmed that the bug still occurs. This configuration file (renamed from `raze.ini` to `raze.txt`) is attached: [`raze.txt`](https://github.com/ZDoom/Raze/files/11862749/raze.txt)

### Provide a Log

The terminal output shows nothing interesting, and I don't know what other logging I would check.

**Comment by coelckers** [comment]
I just tested this and the door does open after killing that ugly 'worm' or whatever it is that spawns out of the queen once it dies.

**Comment by coelckers** [comment]
This doesn't seem to be reliable. It may open but not always.

**Comment by coelckers** [comment]
fixed in 6984b7d6db7aec1722ac156a21b87efb0c289dfc
