### ISSUE TITLE
[BUG] [Exhumed] Kilmaatikahn Boss second-phase attacks not working

### ISSUE THREAD

**Issue by michaelneverwins** [ZDoom/Raze#973]
### Raze version

Raze 1.7.1

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Linux Mint 21.1

### Relevant hardware info

Intel CPU, AMD GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I was fighting the level 19 boss, it started spawning these floating orange balls that do nothing. See the attached video.

https://github.com/ZDoom/Raze/assets/73746653/fa6fc37b-b231-4866-b2ff-3ea15cd41290

I've never played this part of the game on any other engine, but I can see in someone else's video of BuildGDX (linked below) that these orange balls are meant to be exploding projectiles. This video of BuildGDX also shows the boss spawning smaller flying enemies (or perhaps seeking projectiles), which do not appear for me in Raze.

https://www.youtube.com/watch?v=Cvlecltllak&t=156

### Steps to reproduce the behaviour.

1. Go to level 19 (_Kilmaatikahn Boss_).
2. Damage the boss until it enters the second phase.
3. Observe the result of the boss's attacks.

To verify that the bug was not the result of some corruption in my save file (as may have been the case with #972), I warped to level 19 by entering `map lev19` in the console, and then used cheats to get all weapons and invincibility so that I wouldn't die while trying to record the attached video.

### Your configuration

My configuration file (renamed from `raze.ini` so that GitHub lets me upload it) is attached: [`raze.txt`](https://github.com/ZDoom/Raze/files/11876832/raze.txt)

### Provide a Log

N/A

**Comment by mjr4077au** [comment]
This issue hasn't been forgotten but its quite a complex one to resolve.

Between 1.1.0 and 1.2.0, the second phase attack stops properly targeting the player. This stems from `6f8a5ee2d24c6db348212c5f64f729ceaffb6361`.

Between 1.2.0 and 1.3.0 is where the second phase attack stops working at all. `ae271b272a75f96af7ac3031455da179c0d3444a` is where it starts to break. The second phase attack targeting works somewhat, though the actors don't face the player.

Further bisection is needed to find out where it fully breaks.

**Comment by coelckers** [comment]
fixed in ff0cb2f5809d62f40a4fecf23a7eec6fe2aebfa6
