### ISSUE TITLE
[BUG] [SW TD] Machinegun turret on $shore (Prison Camp) does not work

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#975]
### Raze version

1.8pre-538-g 1e2b5c2747

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The machinegun turret on the Shadow Warrior: Twin Dragon secret level ($shore AKA Prison Camp) does not aim to shoot at you, nor does it open fire.

[Here's a saved game](https://github.com/ZDoom/Raze/files/11995936/machinegun.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on Shadow Warrior: Twin Dragon $shore level, or load the saved game
2. Play until you reach the automatic machinegun turret
3. It does not aim at you or open fire like it should

**Comment by coelckers** [comment]
Fixed in 0380ef3b804a36524bf71553f869fb14f87e5b00

There seems to be an issue with aiming, though, as if it does not get the correct player z and height. Needs more investigation.

**Comment by coelckers** [comment]
Seems to be fine.
