### ISSUE TITLE
[BUG] [Exhumed] Some sprites are too high

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#977]
### Raze version

1.8pre-543-g ce34ef2921

### Which game are you running with Raze?

Exhumed/Powerslave

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Some sprites are too high. For example, there are supposed to be a few life blood goblets in the room behind the cracked pharaoh mask on the training level, but they are invisible because they are too high.

Screenshot from Raze, showing an "empty" room behind the cracked pharaoh mask on the training level:
![Exhumed_0005](https://github.com/ZDoom/Raze/assets/6550500/1fb572b7-46dc-47de-b9b0-62b0bf24da21)

Screenshot from BuildGDX, showing the life blood goblets inside the same room correctly:
![scr-map1-0000](https://github.com/ZDoom/Raze/assets/6550500/3c033aff-7673-45d2-b68a-f463d28420a0)

[Here's a saved game](https://github.com/ZDoom/Raze/files/12087842/blown.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game of Powerslave/Exhumed on the training level, or load the saved game
2. Play until you reach the room with the pushable block and cracked pharaoh mask
3. Open the cracked pharaoh mask wall to reveal a belt of bullets and life blood goblets
4. The life blood goblets will be invisible because they are too high

**Comment by mjr4077au** [comment]
Bisected back to 1b2a249243611071a3b2b6438f3c1161d3cbb25b, but can't see anything obvious that's causing this. @coelckers can you please take a look?

**Comment by coelckers** [comment]
fixed in d96a928738ed8904c9d655da6a0cc4c66614b36f
