### ISSUE TITLE
[BUG] ww2gi: When loading a mappack with a customer XUSER.CON - first level goes to WW2GI level and not one in the pack

### ISSUE THREAD

**Issue by wcapes** [ZDoom/Raze#978]
### Raze version

1.7.1

### Which game are you running with Raze?

WW2 GI

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 2H22 nothing special

### Relevant hardware info

Geforce 1660 super, Ryzen I5 5500 , 32GB DDR 4

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

ww2gi: When loading a mappack with a customer XUSER.CON - first level goes to WW2GI level and not one in the pack

https://www.moddb.com/games/world-war-ii-gi/downloads/germany

definelevelname 2 0 1.map  00:00 00:00 OMAHA BEACH    
definelevelname 2 1 2.map  00:00 00:00 UNDER FIRE
definelevelname 2 2 3.map  00:00 00:00 1942 BRIDGE 

Has these entries (edited) and the first map should be 1.map yet it loads WW2GI first map instead

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download ZIP and place in WW2GI folder
2. "raze.exe" -gamegrp WW2GI.GRP -file "Germany.zip"
3. Start game
4. Select GERMANY under New Game, any skill

**Comment by coelckers** [comment]
That's because this mod adds a third episode to the game, it does not replace the first one.

**Comment by wcapes** [comment]
Just to add that if I update this and change

definelevelname 2 0 1.map 00:00 00:00 OMAHA BEACH
definelevelname 2 1 2.map 00:00 00:00 UNDER FIRE
definelevelname 2 2 3.map 00:00 00:00 1942 BRIDGE

to 

definelevelname 0 0 1.map 00:00 00:00 OMAHA BEACH
definelevelname 0 1 2.map 00:00 00:00 UNDER FIRE
definelevelname 0 2 3.map 00:00 00:00 1942 BRIDGE

to force it to episode 1, that same occurs
