### ISSUE TITLE
[BUG] SW: Palette Emulation is broken in many ways.

### ISSUE THREAD

**Issue by Switch123456789** [ZDoom/Raze#981]
### Raze version

1.8pre-539

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch

### Relevant hardware info

Ryzen 2600X | GTX 1080 (6GB)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If palette emulation is on:
- In foggy areas and under water it seems like palette emulation is not working.
- Fog mode `radial` behaves like `standard`.
- Fog mode `off` behaves like `standard` as well but the fog is a bit further away and still affected by the ambient Light slider. It also disables the Sector light, doesn't matter the settings.

![fog_mode](https://github.com/ZDoom/Raze/assets/25269380/62d407f4-ffda-4c08-92a4-c953f0faf4f3)

**Comment by coelckers** [comment]
Not bugs.

Fog mode has no effect with palette emulation, and non-black fog does not use palette emulation.

**Comment by Switch123456789** [comment]
Thanks for clarifying! However, turning fog mode on or off (with palette emulation on) has an effect as mentioned in my last point and shown in screenshot 1 vs 2.
> the fog is a bit further away and still affected by the ambient Light slider.

Even if I turn off palette emulation & fog mode, there still is black fog, the sector light is gone and it is still affected by the ambient light slider. All of those things are not true for Duke Nukem 3D, there it works how you would expect. My apologies if I misunderstand something.

Is there a reason why some parts of the game are excluded from palette emulation? Doesn't that defeat the purpose? I thought this feature is to give the game the classic 256-colors-VGA-look.
