### ISSUE TITLE
[BUG] [Blood] Crash game when kill yourself with dynamite

### ISSUE THREAD

**Issue by rewdiees** [ZDoom/Raze#983]
### Raze version

1.7.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro

### Relevant hardware info

CPU - Intel i5-7400; GPU - GTX 1060 6GB; RAM - 8GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At level E1M1, I took dynamite from a secret place and immediately blew myself up. Crash happens after that

### Steps to reproduce the behaviour.

1. Select E1M1
2. Take dynamite from secret place
3. After taking blow yourself up immediately
Result: Crash

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/Raze/files/12205505/CrashReport.zip)

**Comment by rewdiees** [comment]
In Blood: Fresh Supply such actions do not lead to crash

**Comment by coelckers** [comment]
Does not crash in current master, so it's probably already fixed
