### ISSUE TITLE
[BUG] [RR] Several issues

### ISSUE THREAD

**Issue by Switch123456789** [ZDoom/Raze#984]
### Raze version

1.8pre-555

### Which game are you running with Raze?

Redneck Rampage

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Arch (latest)

### Relevant hardware info

Ryzen 2600x | GTX 1060 (6GB)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I recently played through Redneck Rampage and found some issues. I took notes of them and kept savestates when possible to report them.

The numbers in this enumeration correspond to the savestate-file-names [in this ZIP](https://github.com/ZDoom/Raze/files/12330537/saves.zip).

0. The Alien Hulk Guard get's stuck between teleporters sometimes.
![save0000](https://github.com/ZDoom/Raze/assets/25269380/8cac7b69-73db-43ce-9558-5a9c2c14e146)

1. The graphics of this roof in E1L1 look broken from certain angles.
![save0001](https://github.com/ZDoom/Raze/assets/25269380/82e34090-19fd-44a3-97ed-3877e85fed79)

2. I saw a few transparent looking dogs in E1L5, I think those are ghost-dogs and are not supposed to be in this level. Also if you get killed by a dog, dogs won't stop attacking you and Leonard keeps grunting as if he is still alive.
![save0002](https://github.com/ZDoom/Raze/assets/25269380/2af5ffed-ed3d-4df5-8197-63cf81ded1c5)

3. After I opened this door, the "opening-sound" got stuck in an infinite loop.
![save0003](https://github.com/ZDoom/Raze/assets/25269380/4dd9a5f1-cf45-4a23-842e-13b5aaf13e98)

4. when I used the key to open this door with the switch it said "LOCK" and the door never unlocked and I was softlocked.
![save0004](https://github.com/ZDoom/Raze/assets/25269380/3fd6332c-7376-4b67-a44b-b67b5dfc6cb4)

5. The "water-texture" in this spot looks very odd/broken.
![save0005](https://github.com/ZDoom/Raze/assets/25269380/6130c80e-fca5-4e3c-802b-7845871462c2)

6. After killing the chicken on the log, his feathers went "to the sky".
![save0006](https://github.com/ZDoom/Raze/assets/25269380/7f0eb31a-b06a-4356-8e5a-e412ece46cd3)

7. In E2L4 some window-textures are rendered as sprites for some reason, lol.
![save0007](https://github.com/ZDoom/Raze/assets/25269380/39544d5d-757b-4f83-9701-cf4114609fd7)

8. If I shoot bolds with the crossbow into this teleporter, it will reflect them back at me.
![save0008](https://github.com/ZDoom/Raze/assets/25269380/a9149798-83d3-4a3d-a202-03d0d5b2aa92)

9. I am not sure about this one but my running speed in E1L6 seems insanely fast.
![save0009](https://github.com/ZDoom/Raze/assets/25269380/5d25a585-5580-4f30-acf9-9b1f8a298cc5)

10. If you get hit by the car in E1L1, it wont kill you if I you're not moving at the momennt of impact. (It is the same in the original game but I feel like that's not right nontheless)
![save0010](https://github.com/ZDoom/Raze/assets/25269380/ff4bbb93-b08c-4e3a-b8d9-4a01171bfad8)

### [Configuration](https://github.com/ZDoom/Raze/files/12330549/raze.txt)

**Comment by Switch123456789** [comment]
I see, I was under the impression it is possible to incorporate some fixes that are not engine related. Can you tell me which are not fixable? I would remove them from the OP.

**Comment by coelckers** [comment]
#1 and #7 are fixed now.

**Comment by coelckers** [comment]
All others are game side bugs, mostly not fixable with a simple patch, and in some cases not really wanted (e.g. ghost dogs)
