### ISSUE TITLE
[Feature] Building with Vulkan support on Wayland

### ISSUE THREAD

**Issue by vanfanel** [ZDoom/Raze#987]
### Raze version

Latest GIT version: Commit 85b6c1944232bb9caa562647336f4b8ef828cd17

### Which game are you running with Raze?

None

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12 with Wayland desktop using an WLRoots-based compositor

### Is your feature request related to a problem? Please describe.

Hello there,

I was just trying to build RAZE on GNU/Linux x86_64 and aarch64.
On all my GNU/Linux systems I run a Wayland server: there are no X11 remainings (no, not XWayland for me, thanks).

So, trying to build RAZE, it detects Vulkan on my systems, but it insists on using legacy X11 stuff:
```

/root/src/Raze-1.7.1/libraries/ZVulkan/include/vulkan/vulkan.h:59:10: fatal error: X11/Xlib.h: No such file or directory
   59 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~

```

So, looking at `libraries/ZVulkan/include/vulkan/vulkan.h` seems that the dreaded `<X11/Xlib.h>` inclussion is inside an ifdef:

```
#ifdef VK_USE_PLATFORM_XLIB_KHR
#include <X11/Xlib.h>
#include "vulkan_xlib.h"
#endif

```

...but instead, Vulkan on Wayland would need this earlier one on the same file:
```
#ifdef VK_USE_PLATFORM_WAYLAND_KHR
#include <wayland-client.h>
#include "vulkan_wayland.h"
#endif
```

So, it seems that the build system is currently missing the possibility to pass a parameter to CMake to define VK_USE_PLATFORM_WAYLAND_KHR, right?

Currently, `VK_USE_PLATFORM_XLIB_KHR` is hard-defined in `libraries/ZVulkan/src/volk/volk.c`
On Linux, it should be `VK_USE_PLATFORM_WAYLAND_KHR` instead, since Wayland is what most distros used nowadays (with X11 in legacy mode).

### Describe the solution you'd like

A parameter in CMakeLists.txt to be able to pass `-DVK_USE_PLATFORM_WAYLAND_KHR=true` to ZVulkan, if I am not mistaken.

**Comment by vanfanel** [comment]
I can do my own builds by changing `VK_USE_PLATFORM_XLIB_KHR` to `VK_USE_PLATFORM_WAYLAND_KHR` in `libraries/ZVulkan/src/volk/volk.c`, but ohh well...

**Comment by coelckers** [comment]
Please report this here: https://github.com/dpjudas/ZVulkan
Raze just mirrors that repo's content so the change must be made there.
