### ISSUE TITLE
[BUG]  Fluidsynth unable to load soundfont on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [ZDoom/Raze#988]
### Raze version

Latest Git version, commit 85b6c1944232bb9caa562647336f4b8ef828cd17

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64 and aarch64

### Please describe your specific OS version

Debian 12

### Relevant hardware info

Intel CPU & GPU, 8GB of RAM

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have been trying to run Blood in RAZE with music in GNU/Linux, but I get:

```

fluidsynth: error: Not a RIFF file
fluidsynth: error: Failed to load SoundFont "raze"
Failed to load patch set raze.
                                                                                                               
Unable to create FluidSynth MIDI device. Falling back to System Default
```

I am using latest stable SDL2_Mixer (2.6.3) built with FluidSynth support and latest ZMusic built from latest GIT code (fc30a8f1e4350dba68e23bb702dfa24df3fe525e)
Seems to be unable to load raze soundfound, which I have copied over to **~/.config/blood/soundfonts/raze.sf2**
I have tried several other paths after adding them to **~/.config/raze/raze.ini** with no success, the same error appears.

Any idea on what's going on here? 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run RAZE on GNU Linux with the Blood data
2. Look at the TTY messages and the lack of music
3. Come here and report

### Your configuration

```ini
https://pastebin.com/5BePpsxW
```

### Provide a Log

https://pastebin.com/LvUVc2pF

**Comment by vanfanel** [comment]
I have also tried moving the **sounfonts** dir to **/usr/local/share/raze**, etc...

**Comment by coelckers** [comment]
This sounds like you got a library conflict. ZMusic integrates Fluidsynth statically (for various technical reasons.)
SDL_Mixer should not come into play here, neither ZMusic, GZDoom nor Raze use it

**Comment by vanfanel** [comment]
@coelckers Ok, what library conflict could I have it, as you said, ZMusic integrates Fluidsynth statically? Has somebody tried to build this on GNU/Linux?

**Comment by mjr4077au** [comment]
We do test on Linux and I provide first party maintenance to `raze-git` on Arch Linux's AUR: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=raze-git.

The correct directory is `/usr/share/raze/soundfonts/raze.sf2`.
