### ISSUE TITLE
[BUG] [Blood] Russian font problems

### ISSUE THREAD

**Issue by Blueberryy** [ZDoom/Raze#989]
### Raze version

latest devbuild

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

No "Т" russian character for bigfont of Blood and Dukenukem. (even with smallfont for duke's)
![raze_9oGpybm34h](https://github.com/ZDoom/Raze/assets/36592509/82c1544a-35ff-47ab-acf3-48f1747278ad)

Small "у" russian character is kind of big in smallfont of Blood.
![raze_9aiPUU9GFZ](https://github.com/ZDoom/Raze/assets/36592509/5e1f09ee-c3fa-4847-89f1-2ea09778c2ae)

**Comment by coelckers** [comment]
fixed both
