### ISSUE TITLE
[BUG] Voxels don't work for any games run on Raze 1.8, all display as sprites only

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#990]
### Raze version

raze-x64-1.8pre-568

### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

No matter what game I launch, even with default config settings, all voxelized pickup items will just show as sprites instead.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. launch game
2. look at items
3. they're probably not voxels

### Your configuration

```ini
Default configuration
```

**Comment by coelckers** [comment]
fixed in e19ce3ead4509b304242a6c2083bb00edf2ffb0d
