### ISSUE TITLE
[BUG] Raze 1.8 has no formatting in the config file

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#991]
### Raze version

raze-x64-1.8pre-568

### Which game are you running with Raze?

Other

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Raze 1.8 created a mostly unformatted config file for me, not sure how/why.
![image](https://github.com/ZDoom/Raze/assets/89247988/d209044f-b3d7-4640-9041-20ed2047d391)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Delete everything in your config
2. Let it regenerate
3. It looks messy now with 1.8

### Your configuration

```ini
default
```

**Comment by coelckers** [comment]
Are you by any chance using an old Notepad version? That's the only known editor to mess it up. My config looks fine, btw.

**Comment by ninjakitty844** [comment]
In notepad++ it looks like this: 
![image](https://github.com/ZDoom/Raze/assets/89247988/1c11bdef-9f26-48f9-a2ec-4e59c7754996)

something is definitely wrong

**Comment by coelckers** [comment]
That was more helpful. I fixed it in GZDoom, it will filter down to Raze with the next update.
