### ISSUE TITLE
[BUG] [SW] Palette emulation makes hanging Coolie in level 3 pitch black

### ISSUE THREAD

**Issue by ninjakitty844** [ZDoom/Raze#994]
### Raze version

raze-x64-1.8pre-568

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://github.com/ZDoom/Raze/assets/89247988/e3adf989-c1e8-4073-97f5-82ee4d23dfdf)
This is with a default config, just palette emulation turned on.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Turn on palette emulation
2. Look at hanging coolie in level 3
3. It is pitch black

### Your configuration

```ini
Default config, but with palette emulation turned on. No other changes.
```

**Comment by coelckers** [comment]
fixed in 1fe1359e5b543498ecd14ca7d2f947b9266ffa13
