### ISSUE TITLE
[BUG]  Quit choice (YES/NO) highlight is inverted

### ISSUE THREAD

**Issue by donizettilorenzo** [ZDoom/Raze#995]
### Raze version

1.8 pre

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11

### Relevant hardware info

i5 11600 / RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Quit choice highlight is inverted

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by coelckers** [comment]
It clearly is not. It will do what the arrow points to.
