### ISSUE TITLE
[Devbuilds Website Issue] No new Raze commits?

### ISSUE THREAD

**Issue by Blueberryy** [ZDoom/Raze#996]
Last devbuild was on Aug 24 2023... Is it automatically creates new one or someone have to upload new devbuild?

**Comment by madame-rachelle** [comment]
They may have stalled due to tooling system configuration changes (in this case cmake) - sometimes it requires manual intervention to get things going again.

@Blzut3

**Comment by Blueberryy** [comment]
Thanks for the new build ❤️

**Comment by Blzut3** [comment]
For the record, I believe the scripts may need some adjusting still, but at least he build machine is powered on again.
