### ISSUE TITLE
[BUG] - DN3D - Lights from explosions 

### ISSUE THREAD

**Issue by Axldomi** [ZDoom/Raze#997]
### Raze version

raze-x64-1.8pre-568-ge88d2fb6b.7z

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

10 Home

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using an explosive in DN3D, the screen alway highlights on impact, however using the latest version the flicker's duration is too long (couple of seconds).

### Steps to reproduce the behaviour.

Use an explosive in DN3D.

**Comment by coelckers** [comment]
The effect lasts as long as the explosion sprite can be seen, that's precisely what the code implies, so I'd guess it's correct.

**Comment by coelckers** [comment]
fixed in a41ebfeb73747eaf00ef40c70648e5ec26ee6ea6

This one was nasty.
