### ISSUE TITLE
[BUG] [Duke] Player can die from extreme heights even with god mode

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#999]
Against the current state of master, start E1L1 and toggle god mode and give yourself everything, then from the street go all the way up with the jetpack, then allow yourself to fall. You'll still be standing, but you'd have died. and can't move until you press use to start again.

**Comment by coelckers** [comment]
fixed in 2cf474bddcbf2de776da00e3adbb56f2a57e43ab
